### ISSUE TITLE
Acquired / No such file errors

### ISSUE THREAD

**Issue by dandaka** [OpenLightingProject/ola#1006]
After upgrade to OLA 0.10.0 with brew, I see this in console:

```
common/io/Serial.cpp:181: Acquired /tmp/LCK..ttyUSB0
common/io/IOUtils.cpp:48: open(/dev/ttyUSB0): No such file or directory
```

These two lines keep repeating.

**Comment by peternewman** [comment]
Can we see the full olad -l 4 log please.

This will be coming from either the usbserial or stageprofi plugins, so you could just disable those.

But I guess we shouldn't bother trying to acquire a lock for a device if the device doesn't exist. Perhaps we should add a FileExists at the top of AcquireUUCPLockAndOpen @nomis52 , which should do the trick shouldn't it.

**Comment by dandaka** [comment]
You are welcome
https://gist.github.com/dandaka/30aae7df958ba767239d

Since before update there was no such errors, I think this is a bug, that could be fixed without additional configuration from user.

**Comment by peternewman** [comment]
The UUCP locking is a new feature in 0.10.0, it wasn't doing it before, so you wouldn't have seen the messages. It's technically just being more verbose about something it was trying to do before anyway, it just didn't used to log that it was trying. Even if we "fix" it to check if the file exists before bothering to acquire a lock, we'll still want to log that the file doesn't exist.

So if you don't want the errors, you either need to change your logging level or disable the plugin(s) trying to open the device.

**Comment by dandaka** [comment]
Fixed for me!

**Comment by peternewman** [comment]
Where @dandaka ? How?

**Comment by peternewman** [comment]
I've made my suggested improvement in #1010 @dandaka .

**Comment by dandaka** [comment]
By editing two files [you suggested] I fixed the issue. First I thought, you say "it is not a bug", now I think you said "to quick fix do that, and for proper fix I've maid pull request".

**Comment by peternewman** [comment]
It's sort of a bug, in that there's not much point trying to lock a device that doesn't exist, but we'll always log something when we try that, and we'll keep trying that, so getting some log messages for a non-existent device isn't a bug.

Anyway all sorted now, or at least will be in 0.11.0.

**Comment by hepiyellow** [comment]
Hi,

I am getting this:
```
common/io/Serial.cpp:148: Device /dev/ttyUSB0 doesn't exist, so there's no point trying to acquire a lock
```

So now the error is clear. But how do I proceed from here? 
Why doesn't the file exist?
I connected the Enttec USB Pro and I am getting this, and the device is not reacting (led not blinking).

**Comment by peternewman** [comment]
What does lsusb show @hepiyellow ?

Or System Info assuming you're on a Mac again?

Have you followed the device specific config for a Pro on a Mac:
https://wiki.openlighting.org/index.php/OLA_Device_Specific_Configuration#USB_Pro

**Comment by hepiyellow** [comment]
HI,

First of all, yes, its on Mac. OS X 10.11.6,
with ola 0.10.2.

Second, the usb pro works, with different Deice name (not /dev/ttyUSB0), and while it is working, I get the mentioned error (`common/io/Serial.cpp:148: Device /dev/ttyUSB0 doesn't exist, so there's no point trying to acquire a lock`).
So it's not an issue.

For the record, I didn't follow the [device specific config](https://wiki.openlighting.org/index.php/OLA_Device_Specific_Configuration#USB_Pro) for the USB Pro, but I did install the FTDI drivers.
In fact, I don't have a `~/.ola/ola-usbpro.conf` file. only `ola-usbdmx.conf` and `ola-usbserial.conf`.
Should I add `~/.ola/ola-usbpro.conf`?

Oh, and for your first question, there is no `lsusb` on OS X, but there is `system_profiler SPUSBDataType` which prints: 
```
USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCIPPT
      PCI Device ID: 0x1e31 
      PCI Revision ID: 0x0004 
      PCI Vendor ID: 0x8086 

        DMX USB PRO:

          Product ID: 0x6001
          Vendor ID: 0x0403  (Future Technology Devices International Limited)
          Version: 6.00
          Serial Number: EN141121
          Manufacturer: ENTTEC
          Location ID: 0x14100000
```

**Comment by peternewman** [comment]
Sorry to be a pain actually @hepiyellow can you open a new issue, as this isn't related to the existing one you're posting in.

Have you restarted, and can we see:
 ls /dev/cu.usbserial-*

That's a typo in the docs, it should be ola-usbserial.conf .
