### ISSUE TITLE
Please update RPi Images

### ISSUE THREAD

**Issue by hadrimoppy** [OpenLightingProject/ola#1023]
Hey ola-team,

it's great that you updating the code all the time! But as a RPi & linux noob I wanted to ask if its possible to get an image of a running actual ola on a RPi?

Because I try to get the APA102 running via ola and the manual install via git repo doesn`t work (i compiled it twice but I really can't get it running)

So an actual image of the ola would be very very nice!

**Comment by nomis52** [comment]
You can download Pi images from http://dl.openlighting.org/ 

If you then follow the instructions in the tutorial  (https://www.openlighting.org/ola/tutorials/ola-on-raspberry-pi/#Updating ) you'll get v 0.9.8, which has APA support.

**Comment by hadrimoppy** [comment]
Hey nomis,

thanks for your fast reply. I tried that one, but the latest image is from 2015-03-28. And when I use the update I didn't get the apa102 support. I try this now one more time. But ain`t it possible to upload a new image file?

Best wishes
Kris

**Comment by nomis52** [comment]
What version of OLA is installed once you run apt-get upgrade?

We don't release new images with each OLA version since it too time consuming. The last image was released to support the Pi 2.

**Comment by hadrimoppy** [comment]
Hey wow, you're quick ;).
Now I set up everything.
I used this image: http://dl.openlighting.org/raspbian-git-01032014.zip
After sudo apt-get update & upgrade I get this version: 0.9.5
And after enabling the spi access (I can choose it via http://192.168.xxx.xxx:9090) I just can choose WS2801, LPD8806 and P9813 in DMX Personality....

**Comment by nomis52** [comment]
Hmm, that's weird. What does 

$ apt-cache show ola 

show?

**Comment by hadrimoppy** [comment]
> Package: ola
> Version: 0.9.8-1~wheezy1
> Architecture: armhf
> Maintainer: Wouter Verhelst <wouter@debian.org>
> Installed-Size: 1796
> Depends: libc6 (>= 2.13-28), libftdi1 (>= 0.20), libgcc1 (>= 1:4.4.0), libncurse                                                                             s5 (>= 5.5-5~), libola1 (>= 0.9.8), libprotobuf7, libstdc++6 (>= 4.4.0), libtinf                                                                             o5, libusb-0.1-4 (>= 2:0.1.12), zlib1g (>= 1:1.1.4), debconf (>= 0.5) | debconf-                                                                             2.0, adduser
> Suggests: bash-completion
> Homepage: https://www.openlighting.org/
> Priority: extra
> Section: electronics
> Filename: pool/main/o/ola/ola_0.9.8-1~wheezy1_armhf.deb
> Size: 580242
> SHA256: ad8fa1c83bd1e42376940fc71255c13d15b8f592c9742af9490c655e1c862ea3
> SHA1: 9db8608a8894395ddd9d19ef9fa68dc591c1b3e0
> MD5sum: f8bec5e76c05b90265225d579d13a4ad
> Description: Open Lighting Architecture
>  The DMX512 standard for Digital MultipleX is used for digital
>  communication networks commonly used to control stage lighting and
>  effects.
>  .
>  The Open Lighting Architecture (OLA) provides a plugin framework for
>  distributing DMX512 control signals.
>  .
>  This package contains olad, the OLA daemon used to control lighting,
>  and a number of command-line tools to control and manipulate olad.
> 
> Package: ola
> Status: install ok installed
> Priority: extra
> Section: electronics
> Installed-Size: 6439
> Maintainer: RenZO <renzo@imaginux.com>
> Architecture: armhf
> Version: 0.9.5-1~wheezy
> Depends: libavahi-client3 (>= 0.6.16), libavahi-common3 (>= 0.6.16), libc6 (>= 2                                                                             .13-28), libftdi1 (>= 0.20), libgcc1 (>= 1:4.4.0), liblo7 (>= 0.26~repack), libm                                                                             icrohttpd10, libncurses5 (>= 5.5-5~), libprotobuf7, libstdc++6 (>= 4.4.0), libti                                                                             nfo5, libusb-0.1-4 (>= 2:0.1.12), libusb-1.0-0 (>= 2:1.0.9~), libuuid1 (>= 2.16)                                                                             , zlib1g (>= 1:1.1.4), debconf (>= 0.5) | debconf-2.0, adduser
> Suggests: bash-completion
> Conffiles:
>  /etc/bash_completion.d/ola d698e4771b443f1f118a2c5c6bafa926
>  /etc/init.d/olad b0fe174a5af92777d661e39893069579
> Description: Open Lighting Architecture
>  The Open Lighting Architecture (OLA) provides a plugin framework for
>  distributing DMX512 control signals on Mac and Linux.
>  .
>  OLA is written and maintained by Simon Newton <nomis52@gmail.com>
> Homepage: https://github.com/OpenLightingProject/ola
>

**Comment by nomis52** [comment]
And what happens if you run 

apt-get install ola

**Comment by hadrimoppy** [comment]
that was easy now i got he update with the supported chipset apa102!
You're great!
Thanks a lot for your quick help! Made my day!

**Comment by peternewman** [comment]
Would it not be sense for us to at least update the pi debs to 0.10.0 @nomis52 ?

**Comment by nomis52** [comment]
Yes, I want to do that as well but this is enough to get them going.
