### ISSUE TITLE
"readdir_r" deprecated in newer glibc versions

### ISSUE THREAD

**Issue by daveol** [OpenLightingProject/ola#1055]
In fedora's rawhide version of glibc `readdir_r` is deprecated ([build.log](https://kojipkgs.fedoraproject.org//work/tasks/9706/13179706/build.log)), the [patch](https://www.sourceware.org/ml/libc-alpha/2016-02/msg00093.html) or [bug](https://sourceware.org/bugzilla/show_bug.cgi?id=19056) don't really explain why or what to use else.

**Comment by peternewman** [comment]
This seems like it might address why:
https://womble.decadent.org.uk/readdir_r-advisory.html

The patch explicitly says "It is recommended to use readdir and readdir64 instead."

**Comment by nomis52** [comment]
Switching to readdir() is a step backwards.

I'd prefer that we use dirfd() to determine the size of the buffer for  readdir_r().

I've confirmed dirfd() is available on Mac & linux.

**Comment by daveol** [comment]
> I'd prefer that we use dirfd() to determine the size of the buffer for readdir_r().

Okay, but that doesn't take away that readdir_r() is deprecated in the newer versions of glibc and will probably be removed in the future.

I see only one option, switching back to readdir()

**Comment by nomis52** [comment]
Hmm, ok I'm sold. I'll look at the patch later today..

**Comment by daveol** [comment]
The patch doesn't include thread handling at the moment (readdir is not threadsafe), which could be a problem if we use the function in two threads at the same time... do we?

**Comment by peternewman** [comment]
Would it be worth using readdir_r where available (via configure) and only switching back to readdir on machines where the former has been deprecated, or is that overly complex?

**Comment by peternewman** [comment]
We're getting other users hitting this in the wild now http://text.michd.me/isiqejojof.mel . @loansindi .

**Comment by peternewman** [comment]
More issues:
https://groups.google.com/forum/#!topic/open-lighting/GYt4Ne3qQzM

**Comment by daveol** [comment]
I now have written a different approach to a fix for this, it is however of very temporary nature. you can find that fix in PR #1167

**Comment by peternewman** [comment]
@daveol put in a warnings skipping based fix as an interim workaround to this in https://github.com/OpenLightingProject/ola/pull/1168 . We'll still need to fix this properly for when readdir_r gets removed.

**Comment by kripton** [comment]
There's a pretty good explanation on http://man7.org/linux/man-pages/man3/readdir_r.3.html now.
So I'd say that going back to `readdir` might not be a step backwards.
