### ISSUE TITLE
feature request: bi-directional linux tty uart 

### ISSUE THREAD

**Issue by david-sumolight** [OpenLightingProject/ola#1075]
We would like OLA to have a plugin like usbdmx, but over UART, for bidirectional communication with an rdm/dmx widget.

In other words, we would like to be able to communicate with a device over UART, similar to the ja-rule (OLE) device. Using UART instead of USB would make the communication much easier and cheaper and allow a wider variety of microcontrollers to be used.

For example, currently we have OLA running on an OpenWRT device that has one USB port and two UARTs, and we want to use the USB for a wifi stick, not for communicating with the DMX/RDM widget.

It seems that the main obstacle to doing this is that there no library function for bi-directional communication via UART.

**Comment by peternewman** [comment]
Given the UART presents as a serial port, why don't you just implement the Enttec Pro protocol and use the Serial USB plugin?

**Comment by david-sumolight** [comment]
Can you explain how to use the Serial USB plugin with an actual serial port, rather than with an emulated serial port? Does that require writing a new library function?

**Comment by peternewman** [comment]
Just add another line to the ola-usbserial.conf with device_prefix = ttyAMA or whatever your UART name begins with, then it should try to discover a USB Pro device there.

**Comment by peternewman** [comment]
Did you get this sorted @david-sumolight ?

**Comment by peternewman** [comment]
I'm closing this now @david-sumolight . Please feel free to comment if you're still having issues and we can re-open it.
