### ISSUE TITLE
JsonPatchParser.h tries to include project header file

### ISSUE THREAD

**Issue by daveol** [OpenLightingProject/ola#1086]
The file [include/ola/web/JsonPatchParser.h](https://github.com/OpenLightingProject/ola/blob/master/include/ola/web/JsonPatchParser.h#L40) tries to include the project header file (that doesn't get installed) [common/web/OptionalItem.h](https://github.com/OpenLightingProject/ola/blob/master/common/web/OptionalItem.h)  this fails because the file doesn't get installed by auto-tools/make

**Comment by peternewman** [comment]
Fix proposal, move the OptionalItem.h file to include/ola/web (leaving a placeholder version in the old location for backwards compatibility), which should solve the issue.

Alternatively rewrite JsonPatchParser to use auto_ptr or something and NULLs to track if the items have been provided or not.

**Comment by nomis52** [comment]
Move OptionalItem.h to include.

You don't need to leave the original in place common/ is only used internally.
