### ISSUE TITLE
C.H.I.P GPIO nonfunctional

### ISSUE THREAD

**Issue by loansindi** [OpenLightingProject/ola#1095]
Attempting to use the GPIO plugin on a CHIP, which starts at either 408 or 1023 depending on kernel version (http://docs.getchip.com/chip.html#gpio) fails. I think this might be because of this line:

https://github.com/OpenLightingProject/ola/blob/master/plugins/gpio/GPIOPlugin.cpp#L81

I'm going to try and recompile with 'pin' initialized as a uint16_t tonight and see if that clears up the problem, but there may be things I've overlooked.

**Comment by peternewman** [comment]
https://github.com/OpenLightingProject/ola/pull/1097

**Comment by peternewman** [comment]
Now https://github.com/OpenLightingProject/ola/pull/1123/files .

**Comment by peternewman** [comment]
Closing as this has now been merged and will be in 0.10.3.
