### ISSUE TITLE
Attempting to run as root, aborting.

### ISSUE THREAD

**Issue by Tolmino** [OpenLightingProject/ola#1102]
hi
i have compiled on a raspberry pi3 olad git version
and when i try to start i have:

# /usr/local/bin/olad -f
olad/Olad.cpp:100: Attempting to run as root, aborting.

but i'm root !!
any suggest?

**Comment by peternewman** [comment]
Don't compile as root!

Alternatively, there's a configure option to override the non-root checks, but it's bad practice so I wouldn't advise doing so.

**Comment by Tolmino** [comment]
how i can override the not-root-check?

**Comment by Tolmino** [comment]
is the --disable-root-check ?
but maybe --disable-root-compiler ??

**Comment by peternewman** [comment]
./configure --help | grep root
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --docdir=DIR            documentation root [DATAROOTDIR/doc/ola]
  --disable-root-check    Disable the check that prevents olad from running as
                          root

You want the last one, --disable-root-check.

**Comment by nomis52** [comment]
If you don't have the experience to find the flag, you certainly aren't qualified to be running the binary as root.
