### ISSUE TITLE
gcc6 build issues

### ISSUE THREAD

**Issue by yoe** [OpenLightingProject/ola#1106]
Hi,

`std::auto_ptr` is deprecated in the latest C++ standard. As of version 6, GCC emits a warning for this. Due to ola's default of enabling `-Werror` for builds, this causes builds with gcc6 to fail.

By adding `-Wno-error=deprecated-declarations`, this can be worked around without having to disable *all* warning->error conversions, but perhaps ola should consider migrating away from deprecated classes.

**Comment by yoe** [comment]
also see https://bugs.debian.org/831103

**Comment by peternewman** [comment]
See discussion here https://github.com/OpenLightingProject/ola/issues/1028 and the fix here 
https://github.com/OpenLightingProject/ola/pull/1090

I guess that means we ought to try and get 0.10.3 out soon to fix it for any packages.

**Comment by peternewman** [comment]
I'm going to close this, as the fix is in, just not released yet.
