### ISSUE TITLE
ola_set_dmx documentation

### ISSUE THREAD

**Issue by yoe** [OpenLightingProject/ola#1109]
Hi,

I received the [following](https://bugs.debian.org/830972) bug report at Debian:

```
there is no manpage for ola_set_dmx, and the brief help text basically says:

 -d, --dmx <values>        Comma separated DMX values.

What does that mean? Should I enter "-d Channel,Value,Channel2,Value2, ..."
Or should I enter "-d Channel0,Channel1,Channel2, ... Channel512",
or is it something completely different? 

To add insult to injury, googling does not bring up much more than
people using 255,0,255,0 or similar for testing. But what does this do?

Especially when starting out and testing hardware of unknown working order
a more explicit description would be helpful.
```

**Comment by peternewman** [comment]
There has been a man page since at least 0.10.0 (see https://github.com/OpenLightingProject/ola/blob/0.10.0/man/ola_set_dmx.1 ). But it still has the same issue. I'll look at improving the documentation in the --help and man page.

**Comment by peternewman** [comment]
Sorted by @FloEdelmann just stuck behind another change to fix Travis before it goes in.

For next time @yoe you could also point them to ola_dmxconsole.

**Comment by yoe** [comment]
@peternewman well, yes, but documentation is never a bad thing :-)

**Comment by peternewman** [comment]
We should fix https://docs.openlighting.org/ola/man/man1/ola_streaming_client.1.html too really. Fancy doing the honours @FloEdelmann ?

**Comment by peternewman** [comment]
@yoe this has been merged, so will be fixed for ola_set_dmx in 0.10.3 thanks to @FloEdelmann 's work.

@FloEdelmann are you up for doing the same thing for ola_streaming_client?

**Comment by FloEdelmann** [comment]
I'll try this evening

**Comment by FloEdelmann** [comment]
See #1160

**Comment by peternewman** [comment]
They've both been merged now. Closing this. Thanks @FloEdelmann for the hard work!

**Comment by FloEdelmann** [comment]
No problem :)
