### ISSUE TITLE
Please add DMXControl Nodle Interface to list of supported devices

### ISSUE THREAD

**Issue by dmxcfrank** [OpenLightingProject/ola#1114]
Please add DMXControl Nodle Interface to list of supported devices:
https://www.openlighting.org/ola/

Linux: TX/RX
MacOS: ? (not tested)
Windows: ?
It's also listed in recent release nodes: https://github.com/OpenLightingProject/ola/releases/tag/0.10.0

The intreface is described here (in German): 
http://www.dmxcontrol-projects.org/hardware/nodle-u1.html
The project link is: http://www.dmxcontrol.org/

Thanks
info@dmxcontrol-projects.org

**Comment by peternewman** [comment]
Done, thanks for the heads up @dmxcfrank .
