### ISSUE TITLE
test suite failure on s390x

### ISSUE THREAD

**Issue by yoe** [OpenLightingProject/ola#1115]
Hi,

The most recent upload into Debian failed the test suite on the s390x architecture:

    FAIL: common/network/HealthCheckedConnectionTester

The full build log is at <https://buildd.debian.org/status/fetch.php?pkg=ola&arch=s390x&ver=0.10.2-2&stamp=1472209225>. If needed, I can arrange access to the hardware in question for tests.

**Comment by yoe** [comment]
Is it possible/likely that this could be an intermittent failure? If so, I'll ask the s390x people to just rebuild this...

**Comment by peternewman** [comment]
It's quite possible, we get occasional errors of that test on some of the buildbots.

**Comment by yoe** [comment]
okay, did that then. Will see what happens next.

**Comment by yoe** [comment]
That fixed it, apparently
