### ISSUE TITLE
Compiling ola on beaglebone black

### ISSUE THREAD

**Issue by Summer88** [OpenLightingProject/ola#1118]
Hi, 

I'm triyng to compile ola on a Beaglebone with python bindings 
Linux beaglebone 4.4.15-ti-r37 #1 SMP Tue Jul 19 17:04:02 UTC 2016 armv7l GNU/Linux

but i stuck  at make check, can somebody tell me what is missing?

cd /usr/local/src/ola
sudo ./configure --enable-rdm-tests --enable-python-libs 
sudo make 

debian@beaglebone:/usr/local/src/ola$ sudo make check
make  check-recursive
make[1]: ingresso nella directory "/usr/local/src/ola"
Making check in java
make[2]: ingresso nella directory "/usr/local/src/ola/java"
make[2]: Nessuna operazione da eseguire per "check".
make[2]: uscita dalla directory "/usr/local/src/ola/java"
make[2]: ingresso nella directory "/usr/local/src/ola"
make  common/base/CredentialsTester common/base/FlagsTester common/base/LoggingTester common/dmx/RunLengthEncoderTester common/export_map/ExportMapTester common/file/UtilTester common/io/DescriptorTester common/io/IOQueueTester common/io/IOStackTester common/io/MemoryBlockTester common/io/SelectServerTester common/io/StreamTester common/io/TimeoutManagerTester common/messaging/DescriptorTester common/network/HealthCheckedConnectionTester common/network/NetworkTester common/network/TCPConnectorTester common/rdm/DiscoveryAgentTester common/rdm/PidStoreTester common/rdm/QueueingRDMControllerTester common/rdm/RDMAPITester common/rdm/RDMCommandSerializerTester common/rdm/RDMCommandTester common/rdm/RDMFrameTester common/rdm/RDMHelperTester common/rdm/RDMMessageTester common/rdm/RDMReplyTester common/rdm/UIDAllocatorTester common/rdm/UIDTester common/rpc/RpcTester common/rpc/RpcServerTester common/strings/UtilsTester common/thread/ExecutorThreadTester common/thread/ThreadTester common/thread/FutureTester common/timecode/TimeCodeTester common/utils/UtilsTester common/web/JsonTester common/web/ParserTester common/web/PtchParserTester common/web/PtchTester common/web/PointerTester common/web/PointerTrackerTester common/web/SchemaParserTester common/web/SchemaTester common/web/SectionsTester data/rdm/PidDataTester libs/acn/E131Tester libs/acn/E133Tester libs/acn/TransportTester libs/usb/LibUsbThreadTester ola/OlaClientTester olad/plugin_api/ClientTester olad/plugin_api/DeviceTester olad/plugin_api/DmxSourceTester olad/plugin_api/PortTester olad/plugin_api/PreferencesTester olad/plugin_api/UniverseTester plugins/artnet/ArtNetTester plugins/dummy/DummyPluginTester plugins/espnet/EspNetTester plugins/kinet/KiNetTester plugins/openpixelcontrol/OPCClientTester plugins/openpixelcontrol/OPCServerTester plugins/osc/OSCTester plugins/shownet/ShowNetTester plugins/spi/SPITester plugins/usbpro/ArduinoWidgetTester plugins/usbpro/BaseRobeWidgetTester plugins/usbpro/BaseUsbProWidgetTester plugins/usbpro/DmxTriWidgetTester plugins/usbpro/DmxterWidgetTester plugins/usbpro/EnttecUsbProWidgetTester plugins/usbpro/RobeWidgetDetectorTester plugins/usbpro/RobeWidgetTester plugins/usbpro/UltraDMXProWidgetTester plugins/usbpro/UsbProWidgetDetectorTester plugins/usbpro/WidgetDetectorThreadTester olad/OlaTester tools/ola_trigger/ActionTester  \
  python/ola/rpc/SimpleRpcControllerTest.py python/ola/DUBDecoderTest.py python/ola/MACAddressTest.py python/ola/UIDTest.py
make[3]: ingresso nella directory "/usr/local/src/ola"
make[3]: "common/base/FlagsTester" è aggiornato.
make[3]: "common/base/LoggingTester" è aggiornato.
make[3]: "common/dmx/RunLengthEncoderTester" è aggiornato.
make[3]: "common/export_map/ExportMapTester" è aggiornato.
make[3]: "common/file/UtilTester" è aggiornato.
make[3]: "common/io/DescriptorTester" è aggiornato.
make[3]: "common/io/IOQueueTester" è aggiornato.
make[3]: "common/io/IOStackTester" è aggiornato.
make[3]: "common/io/MemoryBlockTester" è aggiornato.
make[3]: "common/io/SelectServerTester" è aggiornato.
make[3]: "common/io/StreamTester" è aggiornato.
make[3]: "common/io/TimeoutManagerTester" è aggiornato.
make[3]: "common/messaging/DescriptorTester" è aggiornato.
make[3]: "common/network/HealthCheckedConnectionTester" è aggiornato.
make[3]: "common/network/NetworkTester" è aggiornato.
make[3]: "common/network/TCPConnectorTester" è aggiornato.
make[3]: "common/rdm/DiscoveryAgentTester" è aggiornato.
make[3]: "common/rdm/PidStoreTester" è aggiornato.
make[3]: "common/rdm/QueueingRDMControllerTester" è aggiornato.
make[3]: "common/rdm/RDMAPITester" è aggiornato.
make[3]: "common/rdm/RDMCommandSerializerTester" è aggiornato.
make[3]: "common/rdm/RDMCommandTester" è aggiornato.
make[3]: "common/rdm/RDMFrameTester" è aggiornato.
make[3]: "common/rdm/RDMHelperTester" è aggiornato.
make[3]: "common/rdm/RDMMessageTester" è aggiornato.
make[3]: "common/rdm/RDMReplyTester" è aggiornato.
make[3]: "common/rdm/UIDAllocatorTester" è aggiornato.
make[3]: "common/rdm/UIDTester" è aggiornato.
make[3]: "common/rpc/RpcTester" è aggiornato.
make[3]: "common/rpc/RpcServerTester" è aggiornato.
make[3]: "common/strings/UtilsTester" è aggiornato.
make[3]: "common/thread/ExecutorThreadTester" è aggiornato.
make[3]: "common/thread/ThreadTester" è aggiornato.
make[3]: "common/thread/FutureTester" è aggiornato.
make[3]: "common/timecode/TimeCodeTester" è aggiornato.
g++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread  -DTEST_SRC_DIR=\".\" -DTEST_BUILD_DIR=\".\" -Werror -g -O2 -std=gnu++98 -pthread -MT common/utils/common_utils_UtilsTester-StringUtilsTest.o -MD -MP -MF common/utils/.deps/common_utils_UtilsTester-StringUtilsTest.Tpo -c -o common/utils/common_utils_UtilsTester-StringUtilsTest.o `test -f 'common/utils/StringUtilsTest.cpp' || echo './'`common/utils/StringUtilsTest.cpp
g++: internal compiler error: Ucciso (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:12544: set di istruzioni per l'obiettivo "common/utils/common_utils_UtilsTester-StringUtilsTest.o" non riuscito
make[3]: *** [common/utils/common_utils_UtilsTester-StringUtilsTest.o] Errore 4
make[3]: uscita dalla directory "/usr/local/src/ola"
Makefile:16511: set di istruzioni per l'obiettivo "check-am" non riuscito
make[2]: *** [check-am] Errore 2
make[2]: uscita dalla directory "/usr/local/src/ola"
Makefile:15479: set di istruzioni per l'obiettivo "check-recursive" non riuscito
make[1]: *** [check-recursive] Errore 1
make[1]: uscita dalla directory "/usr/local/src/ola"
Makefile:16515: set di istruzioni per l'obiettivo "check" non riuscito
make: *** [check] Errore 2

**Comment by peternewman** [comment]
Hi @Summer88 , sorry you're having issues compiling OLA.

Firstly you don't need to, and indeed shouldn't sudo, but it normally fails later on if you do so.

Which version of OLA did you download/are you trying to build?

Are you on the latests GCC? Until the other week, it built fine for us on Travis with GCC 4.9.

**Comment by Summer88** [comment]
thank you for your reply, I've done it again from start without sudo


this time **make check** fail with:
est.cpp
mv -f common/utils/.deps/common_utils_UtilsTester-MultiCallbackTest.Tpo common/utils/.deps/common_utils_UtilsTester-MultiCallbackTest.Po
g++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread  -DTEST_SRC_DIR=\".\" -DTEST_BUILD_DIR=\".\" -Werror -g -O2 -std=gnu++98 -pthread -MT common/utils/common_utils_UtilsTester-StringUtilsTest.o -MD -MP -MF common/utils/.deps/common_utils_UtilsTester-StringUtilsTest.Tpo -c -o common/utils/common_utils_UtilsTester-StringUtilsTest.o `test -f 'common/utils/StringUtilsTest.cpp' || echo './'`common/utils/StringUtilsTest.cpp
g++: internal compiler error: Ucciso (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:12544: set di istruzioni per l'obiettivo "common/utils/common_utils_UtilsTester-StringUtilsTest.o" non riuscito
make[3]: *** [common/utils/common_utils_UtilsTester-StringUtilsTest.o] Errore 4
make[3]: uscita dalla directory "/usr/local/src/ola"
Makefile:16511: set di istruzioni per l'obiettivo "check-am" non riuscito
make[2]: *** [check-am] Errore 2
make[2]: uscita dalla directory "/usr/local/src/ola"
Makefile:15479: set di istruzioni per l'obiettivo "check-recursive" non riuscito
make[1]: *** [check-recursive] Errore 1
make[1]: uscita dalla directory "/usr/local/src/ola"
Makefile:16515: set di istruzioni per l'obiettivo "check" non riuscito
make: *** [check] Errore 2
-------------------------------------------------------
OLA Version 0.10.2

Prefix: '/usr/local'
Compiler: 'g++ -g -O2 -std=gnu++98 -pthread '
Linker: '/usr/bin/ld   -ldl '
Python: /usr/bin/python

Python API: yes
Java API: no
Enable HTTP Server: no
RDM Responder Tests: yes
Ja Rule: no
Enabled Plugins: artnet dummy e131 espnet ftdidmx gpio karate kinet milinst opendmx openpixelcontrol osc pathport renard sandnet shownet spi stageprofi uartdmx usbdmx usbpro
UUCP Lock Directory: /var/lock

Now type 'make [<target>]'
  where the optional <target> is:
    all          - build everything
    check        - run the tests
    doxygen-doc  - generate the html documentation

**Comment by peternewman** [comment]
Is it a clone of our 0.10 branch, the 0.10.2 release or something else?

Could we have a copy of the log in English (rather than Italian?) in case anyone asks please.

Can you try gcc-4.8 please, also is there a later 4.9 available for your system if you apt-get update?

**Comment by Summer88** [comment]
Sorry for log in italian, the version is the 0.10.2  downloaded with:

git clone https://github.com/OpenLightingProject/ola.git ola

I've been following these instruction:
http://opendmx.net/index.php/OLA_on_Beaglebone

this time I've tried with:
$ alias gcc='gcc-4.8'
$ alias cc='gcc-4.8'
$ alias g++='g++-4.8'
$ alias c++='c++-4.8'

make check

  python/ola/rpc/SimpleRpcControllerTest.py python/ola/DUBDecoderTest.py python/ola/MACAddressTest.py python/ola/UIDTest.py
make[3]: Entering directory '/usr/local/src/ola'
make[3]: 'common/base/FlagsTester' is up to date.
make[3]: 'common/base/LoggingTester' is up to date.
make[3]: 'common/dmx/RunLengthEncoderTester' is up to date.
make[3]: 'common/export_map/ExportMapTester' is up to date.
make[3]: 'common/file/UtilTester' is up to date.
make[3]: 'common/io/DescriptorTester' is up to date.
make[3]: 'common/io/IOQueueTester' is up to date.
make[3]: 'common/io/IOStackTester' is up to date.
make[3]: 'common/io/MemoryBlockTester' is up to date.
make[3]: 'common/io/SelectServerTester' is up to date.
make[3]: 'common/io/StreamTester' is up to date.
make[3]: 'common/io/TimeoutManagerTester' is up to date.
make[3]: 'common/messaging/DescriptorTester' is up to date.
make[3]: 'common/network/HealthCheckedConnectionTester' is up to date.
make[3]: 'common/network/NetworkTester' is up to date.
make[3]: 'common/network/TCPConnectorTester' is up to date.
make[3]: 'common/rdm/DiscoveryAgentTester' is up to date.
make[3]: 'common/rdm/PidStoreTester' is up to date.
make[3]: 'common/rdm/QueueingRDMControllerTester' is up to date.
make[3]: 'common/rdm/RDMAPITester' is up to date.
make[3]: 'common/rdm/RDMCommandSerializerTester' is up to date.
make[3]: 'common/rdm/RDMCommandTester' is up to date.
make[3]: 'common/rdm/RDMFrameTester' is up to date.
make[3]: 'common/rdm/RDMHelperTester' is up to date.
make[3]: 'common/rdm/RDMMessageTester' is up to date.
make[3]: 'common/rdm/RDMReplyTester' is up to date.
make[3]: 'common/rdm/UIDAllocatorTester' is up to date.
make[3]: 'common/rdm/UIDTester' is up to date.
make[3]: 'common/rpc/RpcTester' is up to date.
make[3]: 'common/rpc/RpcServerTester' is up to date.
make[3]: 'common/strings/UtilsTester' is up to date.
make[3]: 'common/thread/ExecutorThreadTester' is up to date.
make[3]: 'common/thread/ThreadTester' is up to date.
make[3]: 'common/thread/FutureTester' is up to date.
make[3]: 'common/timecode/TimeCodeTester' is up to date.
g++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread  -DTEST_SRC_DIR=\".\" -DTEST_BUILD_DIR=\".\" -Werror -g -O2 -std=gnu++98 -pthread -MT common/utils/common_utils_UtilsTester-StringUtilsTest.o -MD -MP -MF common/utils/.deps/common_utils_UtilsTester-StringUtilsTest.Tpo -c -o common/utils/common_utils_UtilsTester-StringUtilsTest.o `test -f 'common/utils/StringUtilsTest.cpp' || echo './'`common/utils/StringUtilsTest.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile:12544: recipe for target 'common/utils/common_utils_UtilsTester-StringUtilsTest.o' failed
make[3]: *** [common/utils/common_utils_UtilsTester-StringUtilsTest.o] Error 4
make[3]: Leaving directory '/usr/local/src/ola'
Makefile:16511: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/usr/local/src/ola'
Makefile:15479: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/ola'
Makefile:16515: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by peternewman** [comment]
If you didn't switch to a branch, that's actually our master branch, which is later than 0.10.2, but anyway it should still work fine.

Thanks for the English, it didn't really change anything, but it's still useful to have.

I'm not convinced you've built with gcc-4.8 given this line is still present "See file:///usr/share/doc/gcc-4.9/README.Bugs for instructions.". We use export CXX="g++-4.8" CC="gcc-4.8" before configure which works fine. Although the configure log with your alias would also show if it has worked as expected or just found the normal later one.

**Comment by peternewman** [comment]
Scrap all the above comments (although I think gcc-4.8 would fix it), just follow the note here https://github.com/OpenLightingProject/ola/issues/1103 .

**Comment by Summer88** [comment]
` ./configure  --enable-python-libs --enable-rdm-tests CXXFLAGS='-ftrack-macro-expansion=0' `

this time make check ends fine:
============================================================================
Testsuite summary for OLA 0.10.2
============================================================================
# TOTAL: 87
# PASS:  87
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
then sudo make install also goes right!
Thank you, have a nice day!

**Comment by peternewman** [comment]
Excellent @Summer88 , I'll close this.
