### ISSUE TITLE
g++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by philipptrenz** [OpenLightingProject/ola#1122]
Hi, 
I'm trying to compile OLA 0.10.2 with Python API on a Raspberry Pi. Except it takes half a day, the last issue I faced was the above. It seems the Raspberry runs out of RAM.
I'm not very familiar with compiling programs, what can I do? 
The repositories are much outdated and can't install them either.
Thanks!

Just saw #158, is there any simple solution? Increasing swap size?

**Comment by peternewman** [comment]
Take a look at https://github.com/OpenLightingProject/ola/issues/1103 which should do it.

I'm going to be confident it will and close the issue, but feel free to comment if it doesn't and I'll reopen it.

**Comment by philipptrenz** [comment]
Worked nicely, thanks! Bringing it to the wiki would be great for all others.
