### ISSUE TITLE
fatal error: stdlib.h: No such file or directory

### ISSUE THREAD

**Issue by joerg-krause** [OpenLightingProject/ola#1125]
Building OLA with a GCC 6 cross-toolchain fails:

```
/usr/bin/arm-linux-g++ -DHAVE_CONFIG_H -I.   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I./include -I./include -Wall -Wformat -W -isystem /usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include -pthread  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -pthread -c -o libs/acn/e131_transmit_test.o libs/acn/e131_transmit_test.cpp
/usr/bin/arm-linux-g++ -DHAVE_CONFIG_H -I.   -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I./include -I./include -Wall -Wformat -W -isystem /usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include -pthread  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -pthread -c -o libs/acn/E131TestFramework.o libs/acn/E131TestFramework.cpp
In file included from /opt/ext-toolchain/arm-buildroot-linux-gnueabihf/include/c++/6.1.0/ext/string_conversions.h:41:0,
                 from /opt/ext-toolchain/arm-buildroot-linux-gnueabihf/include/c++/6.1.0/bits/basic_string.h:5402,
                 from /opt/ext-toolchain/arm-buildroot-linux-gnueabihf/include/c++/6.1.0/string:52,
                 from ./tools/ola_trigger/config.ypp:2:
/opt/ext-toolchain/arm-buildroot-linux-gnueabihf/include/c++/6.1.0/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
```

The C++ library in GCC 6 now provides its own `<stdlib.h>` header that wraps the C library header of the same name, so in `<cstdlib>` the header include

```
#include <stdlib.h>
```

has become

```
#include_next <stdlib.h>
```

`#include_next` is sensitive to the order of directories in the preprocessor's search path, so if that order is changed with `-isystem` then the compiler can't find the right header:

```
#include <...> search starts here:
[1] /usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include
[2] /opt/ext-toolchain/arm-buildroot-linux-gnueabihf/include/c++/6.1.0
[..]
End of search list.
```

`<cstdlib>` is located in [2] whereas `<stdlib.h>` (C library header) is in [1]. In this case, the `#include_next <stdlib.h>` statement in `<cstdlib>`, located in [2], is evaluated **after** the search path [1], so the compiler does not find the right system header.

Using `-isystem` in `libprotobuf_CFLAGS` in [ola.m4](https://github.com/OpenLightingProject/ola/blob/97ecc060f80a142a89a87994d937114a1cd8a2be/config/ola.m4#L27-L29) to supress a compiler warning (treated as error because of `-Werror`) for a library header is totally wrong. `-isystem` should be used to suppress warning in system headers only and `include/google/protobuf/repeated_field.h` is not a system header.

**Comment by joerg-krause** [comment]
I propose to revert 2dddadac08fe7d75057aae68bc342ba00b606fe6 as it tries to solve an issue in the wrong way.

There are no errors in the header files of protobuf, just warnings treated as errors due to the use of `-Werror`. The usage of `-isystem` suppress this warning and therefore the "error" message.

However, `-isystem` should be used for system headers only, and the libprotobuf header files are not system files.

**Comment by peternewman** [comment]
Closed via #1132 , thanks @joerg-krause !

**Comment by peternewman** [comment]
I assume you'll take care of removing https://git.buildroot.net/buildroot/tree/package/ola/0002-Remove-replacing-I-with-isystem.patch when we do our next release @joerg-krause ?

Given you've done some buildroot stuff already, would you mind updating the OLA URL in buildroot ( https://git.buildroot.net/buildroot/tree/package/ola/Config.in#n20 should be https://openlighting.org/ola )?

Also BR2_PACKAGE_OLA_SLP has gone (in https://github.com/OpenLightingProject/ola/pull/552 ) and we've got lots of other plugins added that aren't in the options list if you want to update the rest of it. Plus OLA 0.10.3 is already out that it's not referring to.

**Comment by joerg-krause** [comment]
Thanks for the hints! I will update the package in Buildroot.
