### ISSUE TITLE
Add a native UART input port

### ISSUE THREAD

**Issue by FloEdelmann** [OpenLightingProject/ola#1183]
Currently, the UART plugin can only be used to send DMX data (i.e. as an output port), but we could in theory also use it to receive DMX data (i.e. as an input port).

However, I ran into some problems when I tried because I was not able to identify the break signal that separates one DMX packet from another. I guess this is a feasible problem, though.

**Comment by peternewman** [comment]
You might find something useful in https://github.com/OpenLightingProject/ja-rule/blob/master/firmware/src/transceiver.c which is the code for the PIC based number one, but it can detect breaks on the UART.

I think others have got Enttec OpenDMXUSB and clones to do DMX in (on Windows at least).

**Comment by FloEdelmann** [comment]
I searched a bit and found the specification of the first-gen Raspberry Pi's processor. On page 10, it says explicitly that there is no break-detection possible. So I guess we have to close this issue.
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2835/BCM2835-ARM-Peripherals.pdf#10
