### ISSUE TITLE
Render GFM out to HTML and serve up via docs.openlighting.org

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#1191]
Render GFM out to HTML and serve up via docs.openlighting.org/ola/ as part of the Buildbot workflows

http://pandoc.org/

**Comment by yoe** [comment]
you could also use github pages and render to openlightingproject.github.io/ola...

**Comment by peternewman** [comment]
True, I think we'd have to do some fiddling to link them all together and serve them centrally (plus deal with 0.10/master versioning. It would probably be better to keep all the documentation in one place.

**Comment by peternewman** [comment]
Awaiting https://github.com/OpenLightingProject/buildbot/pull/65 and some backend server config.

**Comment by peternewman** [comment]
Complete and live:
http://docs.openlighting.org/ola/conf/
