### ISSUE TITLE
protobuf 3.2.0 issue

### ISSUE THREAD

**Issue by ilovezfs** [OpenLightingProject/ola#1192]
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -DPID_DATA_DIR=\"/usr/local/Cellar/ola/HEAD-5f490bd_1/share/ola/pids\" -g -O2 -std=gnu++98 -D_THREAD_SAFE -c common/rpc/Rpc.pb.cc  -fno-common -DPIC -o common/rpc/.libs/common_libolacommon_la-Rpc.pb.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -DPID_DATA_DIR=\"/usr/local/Cellar/ola/HEAD-5f490bd_1/share/ola/pids\" -g -O2 -std=gnu++98 -D_THREAD_SAFE -c common/rpc/Rpc.pb.cc -o common/rpc/common_libolacommon_la-Rpc.pb.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -g -O2 -std=gnu++98 -D_THREAD_SAFE  -c -o common/protocol/common_protocol_libolaproto_la-Ola.pb.lo `test -f 'common/protocol/Ola.pb.cc' || echo './'`common/protocol/Ola.pb.cc
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -g -O2 -std=gnu++98 -D_THREAD_SAFE -c common/protocol/Ola.pb.cc  -fno-common -DPIC -o common/protocol/.libs/common_protocol_libolaproto_la-Ola.pb.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -g -O2 -std=gnu++98 -D_THREAD_SAFE -c common/protocol/Ola.pb.cc -o common/protocol/common_protocol_libolaproto_la-Ola.pb.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -g -O2 -std=gnu++98 -D_THREAD_SAFE  -c -o common/protocol/common_protocol_libolaproto_la-OlaService.pb.lo `test -f 'common/protocol/OlaService.pb.cpp' || echo './'`common/protocol/OlaService.pb.cpp
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -isystem /usr/local/Cellar/protobuf/3.2.0/include -g -O2 -std=gnu++98 -D_THREAD_SAFE -c common/protocol/OlaService.pb.cpp  -fno-common -DPIC -o common/protocol/.libs/common_protocol_libolaproto_la-OlaService.pb.o
common/protocol/OlaService.pb.cpp:27:3: error: use of undeclared identifier 'protobuf_AddDesc_Ola_2eproto'
  protobuf_AddDesc_Ola_2eproto();
  ^
1 error generated.
make[2]: *** [common/protocol/common_protocol_libolaproto_la-OlaService.pb.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I'm seeing this while trying to upgrade protobuf to 3.2.0 in Homebrew and revision bumping all reverse dependencies. It looks like the Fedora team has hit the same problem for the same reason: https://www.spinics.net/lists/fedora-devel/msg229952.html

**Comment by peternewman** [comment]
Can we see your common/protocol/Ola.pb.h please? I take it you rebuilt OLA from scratch? It looks like our protoc service generator isn't compatible with protobuf 3.2.0 currently.

**Comment by ilovezfs** [comment]
Yeah this is from scratch.

Here's the Ola.pb.h 0.10.3:
https://gist.github.com/ilovezfs/da43f9f82582dd814ef41391b0e72789

**Comment by ilovezfs** [comment]
I've gone ahead and merged protobuf 3.2.0 into Homebrew, since this was the only blocker, and I've opened https://github.com/Homebrew/homebrew-core/pull/9406 pending resolution of this issue.

**Comment by peternewman** [comment]
Does this mean OLA no longer works on Homebrew then @ilovezfs ? Or is the old version still available too?

I had a look and we need to write another version of our service generator to be compatible with protobuf 3.2 or whenever it broke. Which I'm guessing won't be backwards compatible with 2.4, so we'll need to ship both and do some configure magic until everyone has migrated.

**Comment by ilovezfs** [comment]
It means the existing binaries will continue to work and be installable, but any attempt to build it from source will fail.

**Comment by peternewman** [comment]
I'm guessing you mean the OLA binaries?

Is there a way to install protobuf 3.1.0, or do we have to create our own tap, as this change has also unsurprisingly broken our Travis builds:
https://travis-ci.org/peternewman/ola/jobs/196458412

Interestingly this seems to just be broken since 3.1.0, rather than 3.0.0 generally.

**Comment by ilovezfs** [comment]
I mean the "bottles" that we build for 10.10, 10.11, and 10.12. Users will always get those by default, rather than a local source build, unless they explicitly request --build-from-source or pass one of the formula options.

I could probably convince the other maintainers that a protobuf@3.1 formula is warranted. However, I suspect the fix isn't that big of a thing. If I simply comment out the offending function, the build finishes successfully after re-running make. So there's probably some minor description declaration missing that determines whether or not that function gets synthesized.

**Comment by peternewman** [comment]
Thanks for the clarification.

Unfortunately it seems a bit bigger than that here's the diff for that file alone between v3.1.0 and v3.2.0:
https://github.com/google/protobuf/compare/v3.1.0...v3.2.0#diff-303ffdea4c2a4f93c4ace8acbbf5c4a9

Could we try and get that formula as an interim to buy us some time to rework this bit?

**Comment by ilovezfs** [comment]
Sure. I'll do that now.

**Comment by ilovezfs** [comment]
@peternewman https://github.com/ilovezfs/homebrew-protobuf
```
brew tap ilovezfs/protobuf
```
and then
```
depends_on "ilovezfs/protobuf/protobuf@3.1"
```

You will need to vendor protobuf-c as in the ola formula in ilovezfs/protobuf:
https://github.com/ilovezfs/homebrew-protobuf/blob/master/Formula/ola.rb#L34-L45

I've opened https://github.com/Homebrew/homebrew-core/pull/9450.

**Comment by ilovezfs** [comment]
@peternewman did you have a chance to test this?

**Comment by ilovezfs** [comment]
@peternewman I've gone ahead and shipped a protobuf@3.1 formula and updated the ola formula to depend on it. See

https://github.com/Homebrew/homebrew-core/commit/575375fa726faa362432fabdbacffefa508a6bcb
https://github.com/Homebrew/homebrew-core/commit/e4f9b88fcafd07eb0da69d9efaf16c8d7117e778
https://github.com/Homebrew/homebrew-core/commit/f99ec2b63da25a8dba874b5ac7307bb81cd920f6
https://github.com/Homebrew/homebrew-core/commit/9bc0af4a4d981fce3d42460ca1a971efa5e73bcd
https://github.com/Homebrew/homebrew-core/blob/master/Formula/protobuf@3.1.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/ola.rb

**Comment by peternewman** [comment]
Thanks @ilovezfs . Sorry I hadn't had a chance to test before, I had a rather crazy week.

I'm primarily interested in just fixing our Travis builds in the short term, until we can fix our protobuf service generator, which means I need to install protobuf@3.1 and protobuf-c. I got protobuf@3.1 on fine, but as soon as I install protobuf-c, it pulls in normal protobuf as 3.2.0 and breaks. I see mention of symbols for dependencies in the homebrew documentation, but couldn't see how to implement them. Can you do the equivalent of Debian provides somehow, so protobuf-c will use protobuf@3.1 for it's protobuf requirement? Or a protobuf-c@protobuf3.1 or something? Or just tell it to ignore that dependency? It seems rather backwards if I have to install protobuf-c entirely manually from scratch, extracting the tar file etc when the rest of it can be so well automated.

You can see my efforts so far here:
https://github.com/OpenLightingProject/ola/pull/1194/files

**Comment by ilovezfs** [comment]
I think you can do this:

```
brew link -f protobuf@3.1
export PKG_CONFIG_PATH=/usr/local/opt/protobuf@3.1/lib/pkgconfig
brew install --build-from-source --ignore-dependencies --env=std protobuf-c
```

**Comment by peternewman** [comment]
Thanks @ilovezfs that did the trick.

Now we just need to fix the 3.2.0 issue...

**Comment by ilovezfs** [comment]
Cool. I'm glad your CI is working again. My apologies for breaking it.

**Comment by peternewman** [comment]
No worries, thanks for helping to fix that and fixing the OLA release on Homebrew.

Hopefully we can get the underlying issue fixed fairly soon.

**Comment by daveol** [comment]
in protobuf 3.2 you need to define the proto version, we are still using proto2 which means we'll have to put ``` syntax = "proto2"; ``` at the beginning of every .proto file

Here is the sed command to patch this
```bash
find -name *proto -exec sed '1 i\syntax = "proto2";' {} \;
```

**Comment by ilovezfs** [comment]
Cool. Can that be handled with an environment variable?

**Comment by daveol** [comment]
wait... it seems like that doesn't fix it.... it does get rid of some warnings but the problem with the undeclared identifier still seems to persist. [here](https://kojipkgs.fedoraproject.org//work/tasks/871/17610871/build.log) is the log for fedora

**Comment by ilovezfs** [comment]
@daveol yup same error!

**Comment by peternewman** [comment]
So it looks like we can't add that proto2 line to proto files being parsed by protobuf 2 or it breaks them:
https://github.com/google/protobuf/issues/2064

So as @ilovezfs suggests, if we want to fix that warning, we'll need to make it some sort of configure magic that's run on demand depending on what's detected on each machine. Or possibly add it to all files and then strip it out if unnecessary which may be easier to manage.

**Comment by peternewman** [comment]
As mentioned @daveol unfortunately our custom protobuf service generator creates some C++ code which calls functions called protobuf_AddDesc_<proto filename>. These functions don't exist in the 3.2.0 version of protobuf, so it throws an error when we try to call them.

@daveol seeing as you've hit the same issue with your Fedora install, fancy taking a crack at https://github.com/OpenLightingProject/ola/issues/1193 ? My suspicion is it should be quite an easy fix, but for me getting a suitable test build environment may be quite a faff.

**Comment by ilovezfs** [comment]
any update here?

**Comment by peternewman** [comment]
Sorry @ilovezfs I've not even looked at it since, a combination of stuff outside of OLA and other things in OLA that I think are higher priority.

I'm hoping as a starting point that @nomis52 may be able to tell us what version of protobuf he used originally, so a diff of what it shipped as it's example to what we run can be generated and then reapplied to protobuf3's service generator.

**Comment by daveol** [comment]
Since I have the feeling that this won't be fixed soon, I have retired OLA package in the rawhide and f26 branches of Fedora. As soon as this is fixed I'll get it in to fedora 26 and rawhide again.

**Comment by peternewman** [comment]
Thanks for letting us know @daveol , that's a bit of a shame. You can't do a backport type thing like Homebrew has done then?

**Comment by ConnyOnny** [comment]
> other things in OLA that I think are higher priority

How is anything in the project more important than making it compile again? I can't upgrade any other software using protobuf (e.g. Mumble) because I need OLA. This bug breaks my system, which makes me very sad.

**Comment by peternewman** [comment]
Patches/pull requests welcome @ConnyOnny ! :-)

A chunk of other, smaller/simpler fixes which are also stopping OLA compile for other people and then getting a release out to distribute those fixes for starters. As well as getting some final tests finished for an RDM plugfest.

There is, unfortunately, a large tech debt in the protobuf generator code, so it needs a decent chunk of time dedicated to it, something I can't currently give, whereas in comparison I can spend an hour or two here and there fixing smaller issues, without spending half the available time reminding myself where I got to last time.

I was going to say I still don't have a platform with the problem version of Protobuf, but it turns out the Mac I have access to, which is using Macports, they've gone down the sensible IMHO option of it being a separate package (python2/3 style), so I think you may be able to install both simultaneously.

You don't say which OS you're on, if it's a Mac you could try the above, otherwise I'd imagine you should be able to point OLA at a local copy of protobuf 2, and upgrade your system one. I realise it's not ideal, but you should be able to work around it somehow.

**Comment by ilovezfs** [comment]
Should this issue really be closed? Package managers really cannot be relied on to carry old versions of protobuf indefinitely.

**Comment by ilovezfs** [comment]
@peternewman I think it was closed accidentally because GitHub detected the `fix #number` pattern hehe

**Comment by peternewman** [comment]
Oops, good spot @ilovezfs . Hopefully the error message I've added does actually work on Protobuf 3.2 in the interim until we fix this.

**Comment by ilovezfs** [comment]
@peternewman yes it works. I tested it with protobuf 3.2.0 and 3.3.0.

**Comment by peternewman** [comment]
So here is our first commit of our protoc code (Oct 27 2013):
https://github.com/OpenLightingProject/ola/commit/f9d5e9ff9b2e65664d1b589bd9e5548b293ac663

Which must mean it's protobuf https://github.com/google/protobuf/releases/tag/v2.5.0 or earlier (Feb 27, 2013).

This is going to be more challenging as e.g. 2.0.1 of protobuf:
http://protobuf.sourcearchive.com/documentation/2.0.1/cpp__file_8cc-source.html

Through 2.5.0:
https://github.com/google/protobuf/blob/v2.5.0/src/google/protobuf/compiler/cpp/cpp_file.cc

Still feature significant differences to OLA's code. E.g.
`message_generators_[i].reset(`

Compared to:
https://github.com/OpenLightingProject/ola/blob/f9d5e9ff9b2e65664d1b589bd9e5548b293ac663/protoc/CppFileGenerator.cpp#L65

So either @nomis52 made a LOT of local modifications, or I've failed to find the right codebase.

**Comment by peternewman** [comment]
Hi all, in particular @ConnyOnny , @daveol and to a lesser extent @ilovezfs , @cmuellner thinks he's fixed this issue (see #1336), please can some of you confirm it now compiles, and generally hammer it and try and break OLA with Protobuf >=3.2. I can deal with testing the older version still works.

I suspect this will go into 0.11.0, as it feels like a potentially big and risky change to go into 0.10.x, but it's something I felt out to get fixed before 0.11.0 got released.

**Comment by ilovezfs** [comment]
@peternewman https://github.com/cmuellner/ola/tree/fix-fedora-build builds successfully and `make check` runs without failures except for the one noted in https://github.com/OpenLightingProject/ola/issues/1165

**Comment by ilovezfs** [comment]
(tested with protobuf 3.5.1)

**Comment by peternewman** [comment]
Closed via https://github.com/OpenLightingProject/ola/pull/1336 and into master. Huge thanks to @cmuellner for the PR, and apologies again to @ilovezfs for me failing to notice he spotted the fix initially! This will be in the 0.11.0 release, which should hopefully be along fairly soon.

**Comment by peternewman** [comment]
Hi @pmetzger ,

Yes, sorry for the 0.11.0 delays (there always seems to be something else good we should get into it). The changes in here (ignoring .travis.yml) will fix it:
https://github.com/OpenLightingProject/ola/pull/1336/files

Alternatively here is what another build system is using, although this doesn't fix our Java API (I can't remember if we have an option to build that with MacPorts anyway):
https://github.com/bk138/packages/commit/ab721eaebe8cb89af18628aabb1de7ff15e88783

**Comment by yoe** [comment]
Is this planned for 0.10.7? It's [blocking for Debian](https://bugs.debian.org/900436)

**Comment by yoe** [comment]
Okay, I'm blind -- the MacPorts question just above already answered that :-)

Nvm

**Comment by peternewman** [comment]
@yoe and others, you may also want the commits in https://github.com/OpenLightingProject/ola/pull/1467 for Protobuf 3.6 compatibility.

**Comment by yoe** [comment]
Personally, I'd rather not cherry-pick patches do that unless and until protobuf 3.6

**Comment by peternewman** [comment]
Ah fair enough, I wasn't sure off hand what version you were on. Hopefully 0.11.0 will be out before then anyway!
