### ISSUE TITLE
build failures with gcc7

### ISSUE THREAD

**Issue by yoe** [OpenLightingProject/ola#1193]
Hi,

I received Debian bug [853583](https://bugs.debian.org/853583) today, which claims that ola fails to build with GCC7.

It's not urgent (gcc7 won't be made the default until after the stretch release), but you might want to look into it. The bug report also contains instructions on how to install gcc7 from experimental on a Debian unstable system, so you can try building things.

**Comment by peternewman** [comment]
Looks like the failure may actually be this:
```
common/utils/StringUtils.cpp: In function 'void ola::CapitalizeLabel(std::__cxx11::string*)':
common/utils/StringUtils.cpp:420:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
         *iter = ' ';
         ~~~~~~^~~~~
common/utils/StringUtils.cpp:422:7: note: here
       case ' ':
       ^~~~
```

**Comment by peternewman** [comment]
From https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

> Since there are occasions where a switch case fall through is desirable, GCC provides an attribute, __attribute__ ((fallthrough)), that is to be used along with a null statement to suppress this warning that would normally occur:
> 
>           switch (cond)
>             {
>             case 1:
>               bar (0);
>               __attribute__ ((fallthrough));
>             default:
>               ...
>             }
> C++17 provides a standard way to suppress the -Wimplicit-fallthrough warning using [[fallthrough]]; instead of the GNU attribute. In C++11 or C++14 users can use [[gnu::fallthrough]];, which is a GNU extension.

You can also do comments, but these aren't sufficient in the strictest checking.

**Comment by peternewman** [comment]
I think we probably want to add something to include/ola/base/Macro.h, maybe call it OLA_FALLTHROUGH and we can add detection as necessary to populate the appropriate attribute or whatever depending on the detected compiler version.

**Comment by peternewman** [comment]
See support from some other compilers here too:
https://groups.google.com/forum/#!topic/mozilla.dev.platform/YT7SXFhyr_I

As well as __builtin_fallthrough() in Clang.

**Comment by yoe** [comment]
after

    apt -t experimental install gcc-7 g++-7

and running `./configure CC=gcc-7 CXX=g++-7` in @daveol's `fix_fallthrough` branch, the following compile issues still occur (pardon my Dutch):

    wouter@gangtai:~/debian/ola$ make -k
    make  all-recursive
    make[1]: Map '/home/wouter/debian/ola' wordt binnengegaan
    Making all in java
    make[2]: Map '/home/wouter/debian/ola/java' wordt binnengegaan
    make[2]: Er hoeft niets gedaan te worden voor 'all'.
    make[2]: Map '/home/wouter/debian/ola/java' wordt verlaten
    make[2]: Map '/home/wouter/debian/ola' wordt binnengegaan
    /bin/bash ./libtool  --tag=CXX   --mode=compile g++-7 -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/local/share/ola/pids\" -g -O2 -std=gnu++98 -pthread -MT common/file/common_libolacommon_la-Util.lo -MD -MP -MF common/file/.deps/common_libolacommon_la-Util.Tpo -c -o common/file/common_libolacommon_la-Util.lo `test -f 'common/file/Util.cpp' || echo './'`common/file/Util.cpp
    libtool: compile:  g++-7 -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/local/share/ola/pids\" -g -O2 -std=gnu++98 -pthread -MT common/file/common_libolacommon_la-Util.lo -MD -MP -MF common/file/.deps/common_libolacommon_la-Util.Tpo -c common/file/Util.cpp  -fPIC -DPIC -o common/file/.libs/common_libolacommon_la-Util.o
    common/file/Util.cpp: In function ‘bool ola::file::FindMatchingFiles(const string&, const std::vector<std::__cxx11::basic_string<char> >&, std::vector<std::__cxx11::basic_string<char> >*)’:
    common/file/Util.cpp:138:41: error: ‘int readdir_r(DIR*, dirent*, dirent**)’ is deprecated [-Werror=deprecated-declarations]
       if (readdir_r(dp, &dir_ent, &dir_ent_p)) {
                                             ^
    In file included from common/file/Util.cpp:23:0:
    /usr/include/dirent.h:183:12: note: declared here
     extern int readdir_r (DIR *__restrict __dirp,
                ^~~~~~~~~
    common/file/Util.cpp:153:43: error: ‘int readdir_r(DIR*, dirent*, dirent**)’ is deprecated [-Werror=deprecated-declarations]
         if (readdir_r(dp, &dir_ent, &dir_ent_p)) {
                                               ^
    In file included from common/file/Util.cpp:23:0:
    /usr/include/dirent.h:183:12: note: declared here
     extern int readdir_r (DIR *__restrict __dirp,
                ^~~~~~~~~
    cc1plus: all warnings being treated as errors
    Makefile:10227: recept voor doel 'common/file/common_libolacommon_la-Util.lo' is mislukt
    make[2]: *** [common/file/common_libolacommon_la-Util.lo] Fout 1
    /bin/bash ./libtool  --tag=CXX   --mode=compile g++-7 -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/local/share/ola/pids\" -g -O2 -std=gnu++98 -pthread -MT common/utils/common_libolacommon_la-StringUtils.lo -MD -MP -MF common/utils/.deps/common_libolacommon_la-StringUtils.Tpo -c -o common/utils/common_libolacommon_la-StringUtils.lo `test -f 'common/utils/StringUtils.cpp' || echo './'`common/utils/StringUtils.cpp
    libtool: compile:  g++-7 -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/local/share/ola/pids\" -g -O2 -std=gnu++98 -pthread -MT common/utils/common_libolacommon_la-StringUtils.lo -MD -MP -MF common/utils/.deps/common_libolacommon_la-StringUtils.Tpo -c common/utils/StringUtils.cpp  -fPIC -DPIC -o common/utils/.libs/common_libolacommon_la-StringUtils.o
    common/utils/StringUtils.cpp: In function ‘void ola::CapitalizeLabel(std::__cxx11::string*)’:
    common/utils/StringUtils.cpp:420:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
             *iter = ' ';
             ~~~~~~^~~~~
    common/utils/StringUtils.cpp:422:7: note: here
           case ' ':
           ^~~~
    cc1plus: all warnings being treated as errors
    Makefile:10871: recept voor doel 'common/utils/common_libolacommon_la-StringUtils.lo' is mislukt
    make[2]: *** [common/utils/common_libolacommon_la-StringUtils.lo] Fout 1
    depbase=`echo plugins/usbpro/BaseRobeWidget.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
    /bin/bash ./libtool  --tag=CXX   --mode=compile g++-7 -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -g -O2 -std=gnu++98 -pthread -MT plugins/usbpro/BaseRobeWidget.lo -MD -MP -MF $depbase.Tpo -c -o plugins/usbpro/BaseRobeWidget.lo plugins/usbpro/BaseRobeWidget.cpp &&\
    mv -f $depbase.Tpo $depbase.Plo
    libtool: compile:  g++-7 -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -g -O2 -std=gnu++98 -pthread -MT plugins/usbpro/BaseRobeWidget.lo -MD -MP -MF plugins/usbpro/.deps/BaseRobeWidget.Tpo -c plugins/usbpro/BaseRobeWidget.cpp  -fPIC -DPIC -o plugins/usbpro/.libs/BaseRobeWidget.o
    plugins/usbpro/BaseRobeWidget.cpp: In member function ‘void ola::plugin::usbpro::BaseRobeWidget::ReceiveMessage( ’:
    plugins/usbpro/BaseRobeWidget.cpp:120:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
           m_state = RECV_PACKET_TYPE;
           ~~~~~~~~^~~~~~~~~~~~~~~~~~
    plugins/usbpro/BaseRobeWidget.cpp:121:5: note: here
         case RECV_PACKET_TYPE:
         ^~~~
    plugins/usbpro/BaseRobeWidget.cpp:125:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
           m_state = RECV_SIZE_LO;
           ~~~~~~~~^~~~~~~~~~~~~~
    plugins/usbpro/BaseRobeWidget.cpp:126:5: note: here
         case RECV_SIZE_LO:
         ^~~~
    plugins/usbpro/BaseRobeWidget.cpp:130:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
           m_state = RECV_SIZE_HI;
           ~~~~~~~~^~~~~~~~~~~~~~
    plugins/usbpro/BaseRobeWidget.cpp:131:5: note: here
         case RECV_SIZE_HI:
         ^~~~
    plugins/usbpro/BaseRobeWidget.cpp:143:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
           m_state = RECV_HEADER_CRC;
           ~~~~~~~~^~~~~~~~~~~~~~~~~
    plugins/usbpro/BaseRobeWidget.cpp:144:5: note: here
         case RECV_HEADER_CRC:
         ^~~~
    plugins/usbpro/BaseRobeWidget.cpp:159:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
           if (m_data_size)
           ^~
    plugins/usbpro/BaseRobeWidget.cpp:163:5: note: here
         case RECV_BODY:
         ^~~~
    plugins/usbpro/BaseRobeWidget.cpp:176:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
           m_state = RECV_CRC;
           ~~~~~~~~^~~~~~~~~~
    plugins/usbpro/BaseRobeWidget.cpp:177:5: note: here
         case RECV_CRC:
         ^~~~
    cc1plus: all warnings being treated as errors
    Makefile:14030: recept voor doel 'plugins/usbpro/BaseRobeWidget.lo' is mislukt
    make[2]: *** [plugins/usbpro/BaseRobeWidget.lo] Fout 1
    depbase=`echo examples/ola-dmxconsole.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    g++-7 -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -g -O2 -std=gnu++98 -pthread -MT examples/ola-dmxconsole.o -MD -MP -MF $depbase.Tpo -c -o examples/ola-dmxconsole.o examples/ola-dmxconsole.cpp &&\
    mv -f $depbase.Tpo $depbase.Po
    examples/ola-dmxconsole.cpp: In function ‘void changepalette(int)’:
    examples/ola-dmxconsole.cpp:447:22: error: this statement may fall through [-Werror=implicit-fallthrough=]
           palette_number = 0;
           ~~~~~~~~~~~~~~~^~~
    examples/ola-dmxconsole.cpp:449:5: note: here
         case 0:
         ^~~~
    cc1plus: all warnings being treated as errors
    Makefile:14014: recept voor doel 'examples/ola-dmxconsole.o' is mislukt
    make[2]: *** [examples/ola-dmxconsole.o] Fout 1
    depbase=`echo examples/ola-dmxmonitor.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    g++-7 -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -g -O2 -std=gnu++98 -pthread -MT examples/ola-dmxmonitor.o -MD -MP -MF $depbase.Tpo -c -o examples/ola-dmxmonitor.o examples/ola-dmxmonitor.cpp &&\
    mv -f $depbase.Tpo $depbase.Po
    examples/ola-dmxmonitor.cpp: In member function ‘void DmxMonitor::ChangePalette(int)’:
    examples/ola-dmxmonitor.cpp:564:24: error: this statement may fall through [-Werror=implicit-fallthrough=]
           m_palette_number = 0;
           ~~~~~~~~~~~~~~~~~^~~
    examples/ola-dmxmonitor.cpp:566:5: note: here
         case 0:
         ^~~~
    cc1plus: all warnings being treated as errors
    Makefile:14014: recept voor doel 'examples/ola-dmxmonitor.o' is mislukt
    make[2]: *** [examples/ola-dmxmonitor.o] Fout 1
    make[2]: Doel 'all-am' is niet opnieuw gemaakt vanwege fouten.
    make[2]: Map '/home/wouter/debian/ola' wordt verlaten
    Makefile:15458: recept voor doel 'all-recursive' is mislukt
    make[1]: *** [all-recursive] Fout 1
    make[1]: Map '/home/wouter/debian/ola' wordt verlaten
    Makefile:6776: recept voor doel 'all' is mislukt
    make: *** [all] Fout 2

**Comment by peternewman** [comment]
Thanks for testing @yoe . You'll need to also manually pull in the fixes from #1168 until #1174 gets merged.

Are you sure you've applied @daveol 's patch to StringUtils.cpp, your line numbers seem to match the old numbers, rather than his patched ones.

I guess it's the parallel build allowing it to throw multiple errors at once?

**Comment by yoe** [comment]
You're right, I made a mistake and did not properly check out the right branch. Whoops. Will retry and report after fixing that :-)

`make -k` instructs make to continue after errors. It doesn't tell gcc that it should continue within a single compilation unit, but at least make will continue in that case, so you know which files have at least one issue.

**Comment by yoe** [comment]
after fixing the build to switch to @daveol's branch, things do seem to work. Sorry 'bout that.

**Comment by peternewman** [comment]
That's useful to know @yoe . I assume with -k it still exits with a failure at the end. I'm tempted to add that to Travis, but torn between failing fast and showing all the errors. I suspect failing fast is better for now and less confusing.

**Comment by yoe** [comment]
yes, with -k it continues compiling but the exit state will indicate build failure. I think it's probably a good idea to add -k for travis, since that allows you to fix more than just one build failure with a single commit-build cycle, but it's certainly up to you.

**Comment by peternewman** [comment]
I can certainly see the benefits, I'm just wondering if it makes the log noiser and harder to spot the actual error, given there may be lots of other noise, or just generally a very big log file.

E.g.
https://travis-ci.org/OpenLightingProject/ola/jobs/205770471

Although having looked, perhaps we should actually be -Wno-foo for everything we're doing -Wno-error=foo which might improve that.

**Comment by yoe** [comment]
you could just run `./configure --enable-silent-rules` to create less verbose make output instead. That will make errors and warnings much easier to spot, too.

**Comment by peternewman** [comment]
Catch 22 though, depending on what's broken you may want verbose make output. :(

**Comment by peternewman** [comment]
This has been fixed via https://github.com/OpenLightingProject/ola/pull/1204 .

**Comment by hepiyellow** [comment]
I am getting this error running `make`:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/opt/local/include -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -D_THREAD_SAFE -I/opt/local/include -Werror -Werror -Wno-error=unused-parameter -Wno-error=deprecated-declarations -Wno-error=sign-compare -DPID_DATA_DIR=\"/usr/local/share/ola/pids\" -g -O2 -std=gnu++98 -D_THREAD_SAFE -MT common/utils/common_libolacommon_la-StringUtils.lo -MD -MP -MF common/utils/.deps/common_libolacommon_la-StringUtils.Tpo -c common/utils/StringUtils.cpp  -fno-common -DPIC -o common/utils/.libs/common_libolacommon_la-StringUtils.o
common/utils/StringUtils.cpp:420:9: error: use of undeclared identifier 'OLA_FALLTHROUGH'
        OLA_FALLTHROUGH
        ^
common/utils/StringUtils.cpp:424:9: error: use of undeclared identifier 'OLA_FALLTHROUGH'
        OLA_FALLTHROUGH
        ^
2 errors generated.
make[2]: *** [common/utils/common_libolacommon_la-StringUtils.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

My gcc:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Running on OS X 10.11.6 (El Capitan)
and Xcode 7.3.1

Using OLA master from Git,
`commit ce879956fb035194fd1aa486e77357dce7dc61e8 `

Any ideas?
