### ISSUE TITLE
OLA fails to build with GCC 6.2.x

### ISSUE THREAD

**Issue by mcallegari** [OpenLightingProject/ola#1210]
Hi, the QLC+ project uses the OpenSUSE build service to automate builds for several Linux distros.
Recently I have updated the targeted distros to support a let's say 3 years window, but found that GCC 6.2 is not happy about OLA.
In particular the `common/file/Util.cpp` file.
As there haven't been changes since 5 months on that file, I decided to open this.

You can find all the related build logs here: https://build.opensuse.org/package/show/home:mcallegari79/ola

If you need more info, I'm here

**Comment by mcallegari** [comment]
For the sake of it, here's an extract of the error

`
[  159s] libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/share/ola/pids\" -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -std=gnu++98 -pthread -c common/file/Util.cpp  -fPIC -DPIC -o common/file/.libs/common_libolacommon_la-Util.o
[  159s] libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/share/ola/pids\" -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -std=gnu++98 -pthread -c common/io/Descriptor.cpp  -fPIC -DPIC -o common/io/.libs/common_libolacommon_la-Descriptor.o
[  159s] libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -Werror -Werror -Wno-error=unused-parameter -DPID_DATA_DIR=\"/usr/share/ola/pids\" -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -std=gnu++98 -pthread -c common/base/Flags.cpp -o common/base/common_libolacommon_la-Flags.o >/dev/null 2>&1
[  159s] common/file/Util.cpp: In function 'bool ola::file::FindMatchingFiles(const string&, const std::vector<std::__cxx11::basic_string<char> >&, std::vector<std::__cxx11::basic_string<char> >*)':
[  159s] common/file/Util.cpp:138:7: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
[  159s]    if (readdir_r(dp, &dir_ent, &dir_ent_p)) {
[  159s]        ^~~~~~~~~
[  159s] In file included from common/file/Util.cpp:23:0:
[  159s] /usr/include/dirent.h:183:12: note: declared here
[  159s]  extern int readdir_r (DIR *__restrict __dirp,
[  159s]             ^~~~~~~~~
[  159s] common/file/Util.cpp:138:41: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
[  159s]    if (readdir_r(dp, &dir_ent, &dir_ent_p)) {
[  159s]                                          ^
[  159s] In file included from common/file/Util.cpp:23:0:
[  159s] /usr/include/dirent.h:183:12: note: declared here
[  159s]  extern int readdir_r (DIR *__restrict __dirp,
[  159s]             ^~~~~~~~~
[  159s] common/file/Util.cpp:153:9: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
[  159s]      if (readdir_r(dp, &dir_ent, &dir_ent_p)) {
[  159s]          ^~~~~~~~~
[  159s] In file included from common/file/Util.cpp:23:0:
[  159s] /usr/include/dirent.h:183:12: note: declared here
[  159s]  extern int readdir_r (DIR *__restrict __dirp,
[  159s]             ^~~~~~~~~
[  159s] common/file/Util.cpp:153:43: error: 'int readdir_r(DIR*, dirent*, dirent**)' is deprecated [-Werror=deprecated-declarations]
[  159s]      if (readdir_r(dp, &dir_ent, &dir_ent_p)) {
[  159s]                                            ^
[  159s] In file included from common/file/Util.cpp:23:0:
[  159s] /usr/include/dirent.h:183:12: note: declared here
[  159s]  extern int readdir_r (DIR *__restrict __dirp,
[  159s]             ^~~~~~~~~
[  160s] cc1plus: all warnings being treated as errors
[  160s] Makefile:10230: recipe for target 'common/file/common_libolacommon_la-Util.lo' failed
[  160s] make[2]: *** [common/file/common_libolacommon_la-Util.lo] Error 1
`

**Comment by mcallegari** [comment]
Alright, this seems to be in #1193  and in #1055, which is 1 year old now

**Comment by peternewman** [comment]
We've worked around the readdir_r issue in https://github.com/OpenLightingProject/ola/pull/1168 and the GCC7 failures in https://github.com/OpenLightingProject/ola/pull/1204 .

They'll both be in 0.10.4 which should be released soon.

**Comment by mcallegari** [comment]
Great, thanks ! :+1:

**Comment by mcallegari** [comment]
Hi again, any clue about when 0.10.4 will be released ?
I still have 4 builds failing :sob:

**Comment by peternewman** [comment]
Hi @mcallegari , sorry, there's just a few final bits I want to get into 0.10.4 it should be out soon. I'm updating the NEWS file as I type!

**Comment by mcallegari** [comment]
Hi @peternewman, thanks, great to hear ! As soon as OLA releases, I will release a new QLC+ version too :wink:

**Comment by peternewman** [comment]
0.10.4 is out now @mcallegari .

**Comment by mcallegari** [comment]
Awesome, thank you very much ! :+1:
