### ISSUE TITLE
New two devices 

### ISSUE THREAD

**Issue by miglourenco** [OpenLightingProject/ola#1234]
Can you add?

Elation emulation USB 
And 
Sunlite suite first class +

Reguards,
Miguel Lourenço

**Comment by peternewman** [comment]
Thanks @miglourenco . Can you open these as two separate requests, to make them more manageable to track in future please. Can we also have any links or information you've got on the devices or protocols they use please.

**Comment by peternewman** [comment]
Now covered in https://github.com/OpenLightingProject/ola/issues/1235 and https://github.com/OpenLightingProject/ola/issues/1236
