### ISSUE TITLE
Help Contributing

### ISSUE THREAD

**Issue by DannyAntoine** [OpenLightingProject/ola#1241]
Hello I am new to GitHub and I have been following this project for a while in order to get familiar with it
however i am still lost and i would like to contribute.I tried reading the code to get an idea of what's going on how ever I'm still lost. Please instruct me on what the project is really about also a uml would be great

**Comment by peternewman** [comment]
Hi @DannyAntoine that's great news.

Is there a particular "thing" that you'd like to do? What's you're prefferred language, C++, Python, Javascript, Java or something else?

There are some easy issues you could have a go at if you fancy any of them. We've also got language labels so you can filter for a particular language:
https://github.com/OpenLightingProject/ola/issues?q=is%3Aopen+is%3Aissue+label%3ADifficulty-Easy

Our docs are here:
http://docs.openlighting.org/ola/doc/latest/

There are diagrams there, as well as some standalone pages with more general overview info.

**Comment by DannyAntoine** [comment]
hello @peternewman 
Thanks for replying .C++ and Java are my preferred languages  
thanks for pointing out the documentations as well .
if i have any other question i post them here

**Comment by peternewman** [comment]
Excellent.

It sounds like you've got the ideal selection of skills almost (add Python in and you'd be perfect!). :)

**Comment by peternewman** [comment]
I'm going to close this for now @DannyAntoine to tidy up our issue list. Please feel free to re-open it if you've got any further queries and we'd love to see a contribution from you in future!

**Comment by DannyAntoine** [comment]
hello, @peternewman I'm sorry I have not contributed to the project. Now it's even more difficult for me because hurricane Maria destroyed my country and Internet service and electricity has not been installed in my area. In order I may use internet I have to travel to the capital city

**Comment by peternewman** [comment]
Hi @DannyAntoine ,

No worries, sorry to hear that, that sounds like a much better/worse excuse than most of us can come up with. I hope the situation improves for you soon!
