### ISSUE TITLE
Download share is outdated

### ISSUE THREAD

**Issue by mrinc** [OpenLightingProject/ola#1255]
Hey guys,

It seems like the download share is very outdated: http://dl.openlighting.org/?C=M;O=A

Can we get this checked out so that its up to date again?

Thanks

**Comment by peternewman** [comment]
Hi @mrinc , unfortunately we don't currently have the people or time to keep this up to date, as well as releasing updates and continuing development. For now can I suggest you use the version of OLA in Raspbian, or compile from source if you need the most up to date OLA.

**Comment by mrinc** [comment]
Hey @peternewman 

I have been trying to build from source but having fun :/ - I may be in touch for some help with that if I really get stuck.

If you can give me a list of requirements and scripts that you use to build and package, I'd be happy to use my CI infrastructure to build OLA automatically.

**Comment by peternewman** [comment]
Hi @mrinc ,

IRC or our mailing list are probably the best place for source based building assistance, we've got a number of guides on the website you can follow.

In terms of automating builds, our Pi image build config is in here:
https://github.com/OpenLightingProject/raspberrypi

We also run a buildbot:
https://buildbot.openlighting.org/
and config:
https://github.com/OpenLightingProject/buildbot

New slaves certainly wouldn't hurt here, a lot are offline most/all of the time. I'd quite like to get buildbot building nightly/weekly debs etc.

**Comment by joshdurbin** [comment]
@peternewman this might help --> https://github.com/baaahs/light-server-infrastructure/blob/master/roles/ola-install/tasks/main.yml

**Comment by mrinc** [comment]
Just closing this issue as using apt-get now works with UART so the download share is no longer necessary.
Re the build bots, I can open a new issue about them 👍
