### ISSUE TITLE
Change socket of port 9010

### ISSUE THREAD

**Issue by LaurensVanAcker** [OpenLightingProject/ola#1315]
Hi

How can I change the binding address of the service running at port 9010?
I had OLA running together with OpenHab. But now I virtualized OpenHab and I have problems getting the OpenDMX USB to the virtual machine. So it's running on another machine. I can specify port and address in the [OpenHab OLA plugin](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.dmx.ola/src/main/java/org/openhab/binding/dmx/ola/OlaConnection.java), but I don't seem to get OLA running at 0.0.0.0:9010 instead of localhost?

`pi@usbpi:~ $ netstat -l`
`Active Internet connections (only servers)`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State      `
`tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN    ` 
`tcp        0      0 localhost:9010          0.0.0.0:*               LISTEN   `

**Comment by peternewman** [comment]
Essentially you can't/shouldn't, see here for some more detailed explanation:
http://docs.openlighting.org/ola/doc/latest/rpc_system.html#rpc_OLA_RPC

TBH I'm rather confused, I can't even see the connect(host, port) implementation they're calling!

Anyway, our recommended solution would be to instead, run OLAd on the box you're trying to, with the OpenDMX connected, then patch the OpenDMX to an E1.31 or ArtNet universe on this box. Then run OLAd on the OpenHab box too, and patch the E1.31/ArtNet universe to OpenHab's control instead.

**Comment by LaurensVanAcker** [comment]
Aha! Ok, that makes clear for me know: you can combine and glue plugins! 
I now made an E1.31 server of OLA by adding it the universe and connected that an [OpenHab E1.31 plugin I found](https://github.com/J-N-K/smarthome/blob/feature-dmx-binding/extensions/binding/org.eclipse.smarthome.binding.dmx/README.md).
As more than 50% of my house lights are DMX-controlled I'm happy having light again :-).

**Comment by peternewman** [comment]
Excellent, glad you've got it working @LaurensVanAcker .

I was actually suggesting running OLAd on the OpenHab server too, and using OLAd to do the OpenHab to E1.31 interfacing, but as long as it's working either way that's all that really matters!

OT: are they all LED strips and stuff, or do you have dimmers too? If so what do you do about inserting them into the power feed?

**Comment by LaurensVanAcker** [comment]
Yes, I had understand that workflow. I was actually creating that workflow, but I was thinking of minimising the steps and transformations. Because in my previous workflow (OLA on the OpenHab server with USB attached) I had the idea sometimes it was a bit slow (could be the KNX-bus).

So:
KNX > KNX Router > OpenHab > Plugin > TCP-protocol E1.31 > OLA > USB > DMX seemed faster then:
KNX > KNX router > Openhab > Plugin > OLA > TCP-protocol E1.31 + maybe serialising objects to the RPC port > OLA > USB > DMX

I have 8 Brumberg VITALED RGBW spots controlled by DMX. All my dimmers are KNX dimmers, not DMX. All my LED-strips are also KNX-controlled.

What do you mean by "inserting into the power feed"? My KNX cables are in the same tube as the 230V.
My DMX-cables are not in the same tubes, they are on the attic not in tubes and on CAT7-cable not in tubes.

**Comment by peternewman** [comment]
It was the dimmers I was curious about. I guess the KNX ones are designed for installing in a house, whereas most DMX ones generally aren't. That explains it anyway.
