### ISSUE TITLE
Example UART in uartdmx plugin readme is wrong?

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#1320]
Hi @richardash1981

Looking at some of the discussion in :
https://groups.google.com/forum/#!topic/open-lighting/myWi-K570Rc

It seems the example device in the uartdmx plugin may be wrong, as it's /dev/ttyACM0, whereas it appears it should be /dev/ttyAMA0.

It looks like this appeared with the plugin in this PR:
https://github.com/OpenLightingProject/ola/pull/385

After my (rather terse comment) in this commit:
https://github.com/OpenLightingProject/ola/pull/385/commits/39b4bf5296dded813057cb768e099a10cb6feb9a#r12026667

This also contradicts your own instructions:
http://eastertrail.blogspot.nl/2014/04/command-and-control-ii.html

Have I missed something, or should this really be /dev/ttyAMA0?

**Comment by FloEdelmann** [comment]
I've built the extension circuit by @richardash1981 to use the Native UART plugin with the Raspberry Pi B+ and did indeed have to change the default setting to `/dev/ttyAMA0`.

**Comment by peternewman** [comment]
When you say change the default setting @FloEdelmann I assume you just mean what you copied from the readme? I don't believe we pre-populate that field on that plugin.

Terry seems to confirm this here too:
https://groups.google.com/d/msg/open-lighting/myWi-K570Rc/UlNMOl5rAQAJ

**Comment by FloEdelmann** [comment]
@peternewman Correct, that's what I meant.

**Comment by peternewman** [comment]
This may also be /dev/serial0 in later Pi software...

**Comment by peternewman** [comment]
Also confirmed in the blog post here: http://eastertrail.blogspot.com/2014/04/command-and-control-ii.html

**Comment by peternewman** [comment]
Closed via #1498 .
