### ISSUE TITLE
Typo: usbdmx plugin's SyncronizedWidgetObserver

### ISSUE THREAD

**Issue by FloEdelmann** [OpenLightingProject/ola#1331]
*SyncronizedWidgetObserver* should actually be named *Sync**h**ronizedWidgetObserver*.

- [ ] file name
- [ ] class name
- [ ] all calling and referencing files

Should be a simple grep / sed task.

**Comment by peternewman** [comment]
Resisting the urge to suggest we correct it to Synchronised too! :stuck_out_tongue:

**Comment by FloEdelmann** [comment]
Closed by #1350. I didn't know that there are so many places where this is misspelled. Nice to see it corrected!
