### ISSUE TITLE
OLA web management page doesn't work

### ISSUE THREAD

**Issue by laheller** [OpenLightingProject/ola#1333]
I just installed ola package (0.9.8) on **Ubuntu 16.04** using:
`sudo apt-get install ola`

The olad service seems to be OK, I can start/stop it and its status also seems to be OK, when I call:
```
sudo /etc/init.d/olad status

● olad.service - LSB: OLA daemon
   Loaded: loaded (/etc/init.d/olad; bad; vendor preset: enabled)
   Active: active (running) since So 2017-11-25 14:11:05 CET; 40min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3759 ExecStop=/etc/init.d/olad stop (code=exited, status=0/SUCCESS)
  Process: 3830 ExecStart=/etc/init.d/olad start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/olad.service
           └─3836 /usr/bin/olad --syslog --log-level 3 --config-dir /etc/ola

nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping SPI because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping StageProfi because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping Serial USB because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping USB because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping Pathport because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping FTDI USB DMX because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:73: Skipping UART native DMX because it was disabled
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:195: Trying to start Dummy
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/DeviceManager.cpp:105: Installed device: Dummy Device:1-1
nov 25 14:11:05 laheller-GX720 olad[3836]: olad/PluginManager.cpp:200: Started Dummy

```

But the ola web management page at:
[http://127.0.0.1:9090/](http://127.0.0.1:9090/)

**Simply doesn't work - nothing is loaded!**

I should see something like below, but no content appears in firefox:
![image](https://user-images.githubusercontent.com/5788998/33231212-c745d0ac-d1f1-11e7-8718-89e2d3f42b08.png)

Update:
The web content is also available at
_/usr/share/olad/www_

**Comment by peternewman** [comment]
Hi @laheller .

This will be because of this bug I believe:
https://bugs.launchpad.net/ubuntu/+source/ola/+bug/1598184

So either upgrade, ask them to re-open the bug and backport the fix to the 16.04 LTS if you need to stay on that, or compile from source (which will also get you a much newer OLA release).

**Comment by laheller** [comment]
Hi and thanks for reply!

Will try first to compile from sources.

BR,

Ladislav

**Comment by peternewman** [comment]
This is probably the best guide:
https://www.openlighting.org/ola/linuxinstall/

You can install the majority of the dependencies as packages on Ubuntu to simplify the install.

**Comment by laheller** [comment]
@peternewman
Installed it using sources based on guide.
Now ola web works but I have no plugins :-(

**Comment by peternewman** [comment]
Glad you've got it going. You just need to move this file to /etc/init.d/olad :
https://github.com/OpenLightingProject/ola/blob/master/debian/ola.olad.init

**Comment by laheller** [comment]
@peternewman
Moved it, but something is still missing since when i try to execute
`sudo /etc/init.d/olad {start}/{stop}/{restart}/{status}`
nothing happens and server is of course not accessible :-(

Anyway thanks for help, since now I am able to talk with my DMX lights via a Mono.NET application and OLA.

**Comment by peternewman** [comment]
I assume the Mono app is using the C++ API?

You probably need to put some stuff in /etc/default/ola:
RUN_DAEMON = "true";

What output do you get when you run it?

**Comment by laheller** [comment]
@peternewman 
The Mono app is calling the servers's JSON api endpoints, like for example the
`http://127.0.0.1:9090/set_dmx`

When I add **RUN_DAEMON = "true";** to **/etc/default/ola** and try to get status on service, the output is
```
laheller@laheller-GX720:~$ sudo /etc/init.d/olad status
/etc/init.d/olad: 1: /etc/default/ola: RUN_DAEMON: not found

```

**Comment by peternewman** [comment]
Hi @laheller ,

Ah gotcha, have you wrapped that as a library? Care to share it for others to use?

Apologies, try with no semicolon like so:
`RUN_DAEMON="true"`

**Comment by laheller** [comment]
Hello @peternewman 

Not wrapped (yet), since at this moment I am using only the set_dmx endpoint.

Example code:
```
// send X,Y,Z to device @ universe # 1
var url = "http://127.0.0.1:9090/set_dmx"
var req = System.Net.HttpWebRequest.CreateHttp (url);
req.Method = "POST";
req.ContentType = "application/x-www-form-urlencoded";
var stm = req.GetRequestStream ();
// Channel#0=127 Channel#1=0 Channel#2=255 
var body = "u=1&d=127,0,255";
using (var stw = new System.IO.StreamWriter (stm)) {
	stw.Write (body);
}

var res = req.GetResponse ();
var stm2 = res.GetResponseStream ();
using (var str = new System.IO.StreamReader (stm2)) {
	Console.WriteLine (str.ReadToEnd ());
}
```

And the damon config:
Unfortunately the RUN_DAEMON="true" (without semicolon) did not help
can u pls send me your **/etc/default/ola** file ?

**Comment by peternewman** [comment]
Sorry @laheller this got lost somewhere. Our /etc/default/ola file is generated by the postinst:
https://github.com/OpenLightingProject/ola/blob/master/debian/ola.postinst#L33

So if you run:
sudo dpkg-reconfigure ola

But the relevant line is indeed (mine is false for $reasons, but otherwise copied as is):
RUN_DAEMON="true"
