### ISSUE TITLE
Device /dev/ttyUSB0 locked by PID 3112 and process exists, failed to acquire lock

### ISSUE THREAD

**Issue by ltd9938** [OpenLightingProject/ola#1368]
So I run ola with "olad -l 3" and I keep getting the error "Device /dev/ttyUSB0 locked by PID 3112 and process exists, failed to acquire lock."

However when I look up the PID it's olad that's locking the device.

Below is the error and the olad process.

https://i.imgur.com/XmpVQiZ.png

Any ideas?

**Comment by peternewman** [comment]
What type of dongle is /dev/ttyUSB0 and what does ola_dev_info show? I suspect it's been grabbed by a different plugin than the one you wanted to control it with (e.g. stageprofi). Try disabling all the other plugins that aren't the one you want and see if it behaves any better.

You've not got another copy of olad running either have you (I don't think so, based on ps, although I normally use "ps aux", but the man page suggests you're covering it all).

**Comment by ltd9938** [comment]
Perfect!!! Disabling all the other plugins worked!!! Thank you so much, been sitting here struggling the last few days trying to figure out what was going on.

Thanks again!
