### ISSUE TITLE
SPI Plugin: Port count maximum is 8

### ISSUE THREAD

**Issue by s-light** [OpenLightingProject/ola#1379]
Why is the Port count maximum set to 8?
i think it is the `UIntValidator` in this line that constrains this:
[plugins/spi/SPIDevice.cpp#L240](https://github.com/OpenLightingProject/ola/blob/master/plugins/spi/SPIDevice.cpp#L240)
```
m_preferences->SetDefaultValue(PortCountKey(), UIntValidator(1, 8), 1);
m_preferences->SetDefaultValue(SyncPortKey(), IntValidator(-2, 8), 0);
```

i would like to use about 10 universes without 'pixel-stacking' and map them to 10 ports with the software backend.
are there any things limiting this? (besides speed..)
otherwise i would make a pull request changing this to 32 or even higher like 256 ?!

**Comment by peternewman** [comment]
From looking at this history, I think this was just an arbitrary value that seemed about right, but @nomis52 may be able to confirm.

I'd be inclined to not go much higher than 32 to keep it realistic, based on your previous testing.

We should probably also make the two 8's consts/enums, so the upper limit of port count and sync port stay in sync.

**Comment by s-light** [comment]
pull request is in: #1380

**Comment by peternewman** [comment]
I never asked @s-light I assume you tested with a value higher than 8? Or did I read it in a blog entry linked to from elsewhere?

**Comment by s-light** [comment]
till now i did not test.. i searched through the code and did not find any place that could not handle more than 8... - maximum from variable type point of view is 255.
but i will do some real-live-tests - 
i plan to write a short python script that generates data for ~ 0..32 universes - some color fades or something similar - with an color-offset for every universe - so its easy to know which universe is which and to easily spot errors...
than i will try with some apa102 pixel strips i have laying around and i will also record a short video to document it...
i did a first test with the 8 and that seamed to work.. but i had some unknown as have done it with only 2 scripts generating data.. and get confused myself with what colors to expect on which strip part ;-)

i will post here again...

**Comment by s-light** [comment]
did now some tests with high port-counts and universe numbers:
my [OLA_test_pattern_generator](https://github.com/s-light/OLA_test_pattern_generator) script now can generate for multiple universes..

i have tested up to 20 universes - more was not possible as i got
```
olad/plugin_api/PortManager.cpp:119: Patched 11-1-I-19 to universe 20
common/network/Socket.cpp:405: 
  Failed to join multicast group 239.255.0.21: No buffer space available
libs/acn/E131Node.cpp:358: Failed to join multicast group 239.255.0.21
```
additional i hit the SPI-Message length limit.
maximum i got working was 1003 APA102 Pixels.

## all tests were made with / on
- APA102 Individual PixelBrightness Setting (144 Pixel/meter Strips)
- acme systems arietta board (400MHz ARM CPU, 128MB RAM)
  - sd-card image create with [this guide](https://github.com/s-light/acme_ola_crosscompile)
  - connected with USB-Ethernet adapter directly to my Laptop
- Laptop running Kubuntu 17.10 64bit
  - running [OLA_test_pattern_generator](https://github.com/s-light/OLA_test_pattern_generator) with the mentioned configurations from the [sub directory `olad_configurations`](https://github.com/s-light/OLA_test_pattern_generator/tree/master/olad_configurations)
## some test i did:
- `spi_20ports_5x4x36pixel`
  20 Universes that each mapped to 36 Pixel (=720Pixel)
  (4 Universes Per Strip == 5 Strips)
  ~60% CPU(target) @ 50Hz update_interval (host) with no spi-drops
- `spi_20ports_sum1003pixel`
  19Universes @ 50Pixel + 1Universe with 53Pixel (=1003Pixel)
  ~70% CPU(target) @ 50Hz update_interval (host) with no spi-drops

## result
so it seams that also high port counts and high universe counts are possible with medium performance embedded arm boards...

hope that this information is useful for some out there ;-)
