### ISSUE TITLE
0.10.6: data/rdm/PidDataTest.sh failing

### ISSUE THREAD

**Issue by kripton** [OpenLightingProject/ola#1383]
Hi, I'm trying to build an run the tests of ola-0.10.6 on Gentoo. However, data/rdm/PidDataTest.sh fails every time. I tried with Python 2.7 and Python 3.5, result is the same.
dev-libs/protobuf and dev-python/protobuf-python is installed, both in version 3.1.0 (because of #1192).
test-suite.log contains:

```==================================
   OLA 0.10.6: ./test-suite.log
==================================

# TOTAL: 86
# PASS:  85
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: data/rdm/PidDataTest.sh
=============================

Traceback (most recent call last):
  File "./data/rdm/PidDataTest.py", line 23, in <module>
    from ola import PidStore
  File "/var/tmp/portage/app-misc/ola-0.10.6/work/ola-0.10.6/python/ola/PidStore.py", line 29, in <module>
    from ola import Pids_pb2
  File "/var/tmp/portage/app-misc/ola-0.10.6/work/ola-0.10.6/python/ola/Pids_pb2.py", line 11, in <module>
    from google.protobuf import descriptor_pb2
  File "/usr/lib64/python2.7/site-packages/google/protobuf/descriptor_pb2.py", line 230, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
FAIL data/rdm/PidDataTest.sh (exit status: 1)
```
Anybody got an idea why the interface/parameters are wrong here?

**Comment by peternewman** [comment]
Well https://github.com/OpenLightingProject/ola/issues/1192 is merged now, so 0.11.0 should be out fairly soon so it may be easiest to forward port the relevant patch into your release, but if you want to keep going with your existing issue instead...

Can we see line 230 of /usr/lib64/python2.7/site-packages/google/protobuf/descriptor_pb2.py ?

See discussion, e.g. https://github.com/aws/sagemaker-python-sdk/issues/16
or
https://github.com/onnx/onnx/issues/363

This sounds like the key:
https://github.com/onnx/onnx/issues/363#issuecomment-357714608

Which was sort of my guess. So what are your versions of protoc, libprotobuf and python-protobuf and do they all match?

**Comment by kripton** [comment]
I've uploaded the complete file here:
https://gist.github.com/kripton/a263074d268e23658830ba897fb2e3da

Sure I can wait until 0.11 :)
Actually libprotobuf, protoc and protobuf-python should all be at 3.1.0. But it could be that an older libprotobuf is left older from an old installation. I'll check

**Comment by kripton** [comment]
But you're right, all other hits on the web point to a version mismatch. I'll also try on other machines

**Comment by peternewman** [comment]
Hmm curious, or perhaps an older python-protobuf.

It would still be good to know if applying the diff from https://github.com/OpenLightingProject/ola/pull/1336/files or indeed just building from master works for you.

**Comment by kripton** [comment]
Okay, on another system, the test all passed. seems to be a local problem. I'll retry with protobuf 3.5.x and ola master

**Comment by peternewman** [comment]
So 0.10.6 works on Gentoo? Shall we close this then?

**Comment by kripton** [comment]
I've just finished testing master with protobuf-3.5.x on the machine where 0.10.6 with protobuf-3.1.x was failing. All tests pass.
I'd vote for closing this
