### ISSUE TITLE
KiNET Plugin is only supporting one PSU

### ISSUE THREAD

**Issue by DirectCurrent13** [OpenLightingProject/ola#1414]
When multible Kinet PSUs are defined only the first PSU is selectable as an output.
![image](https://user-images.githubusercontent.com/36908396/39656958-5e414252-4fc9-11e8-82d1-bcc17b5bfc86.png)
![image](https://user-images.githubusercontent.com/36908396/39657013-ba74418c-4fc9-11e8-9df6-58f864388e86.png)

**Comment by peternewman** [comment]
Which version of OLA are you running @DirectCurrent13 ?

**Comment by peternewman** [comment]
I think you might find you can patch a second KiNET PSU to another universe.

If you add
`bool AllowMultiPortPatching() const { return true; }`

To:
https://github.com/OpenLightingProject/ola/blob/master/plugins/kinet/KiNetDevice.h#L42

And recompile, I think you'll be able to do what you want.

Can you test it and let us know please?

**Comment by peternewman** [comment]
Or just compile this branch of my repo @DirectCurrent13 :+1: 
https://github.com/peternewman/ola/tree/0.10-kinet-multiport

**Comment by DirectCurrent13** [comment]
I am running version 0.10.5. Honestly though I have no ideal how to build the program from the source. I cloned the GIT repository to my home directory and attempted to follow the instructions in README.debian. However I could not get it to work. My apologies. I original installed OLA as a package through apt-get.

**Comment by peternewman** [comment]
Okay @DirectCurrent13 .

Install the dependencies from apt following the steps here:
https://www.openlighting.org/ola/linuxinstall/#Debian_Ubuntu

Then follow the other steps below to compile and build.

**Comment by peternewman** [comment]
Oh, and make sure you've uninstalled the apt version of OLA before doing the above @DirectCurrent13 .

**Comment by DirectCurrent13** [comment]
Sorry for the delay. I followed you instructions and added 
`bool AllowMultiPortPatching() const { return true; }`
 to line 42 in ola/blob/master/plugins/kinet/KiNetDevice.h  of the main fork. I was able to add at least 5 PSUs

Thanks for all the help.

**Comment by peternewman** [comment]
Excellent @DirectCurrent13 glad that's fixed it (well I assume the second and subsequent PSUs worked as expected?).

We'll get that merged in and released properly soon.

**Comment by peternewman** [comment]
Closed via #1423 . This will be in 0.10.7.

**Comment by DirectCurrent13** [comment]
I tried it with 3 power supplies last night and it works great.
