### ISSUE TITLE
Seg fault when running a basic fade script

### ISSUE THREAD

**Issue by ltd9938** [OpenLightingProject/ola#1431]
I'm writing a basic fade script using the basic ola_send_dmx script as a template. I run into a seg fault at the same point in the script every time I run it.

Script: https://gist.github.com/ltd9938/7d492f27e82dbfa5ed421d758bfeb5f7/

Below is the `olad -l 4` log from the seg fault
https://gist.github.com/ltd9938/917beb454c80f12c0cccc83efdac2669

In the script I added a line that ouputs the channel and the current dmx value and it crashes every time it hits "C: 512 V: 128" in the second for loop.

Any idea on what could be causing this? 

Thank you.

**Comment by peternewman** [comment]
Hi @ltd9938,

You're running a new wrapper each loop, so you'll be overwhelming olad. See this example instead:
https://www.openlighting.org/ola/developer-documentation/python-api/#Sending_Multiple_Frames

Or this:
https://github.com/OpenLightingProject/ola/blob/master/python/examples/ola_simple_fade.py

In future, can you post a full example with includes too please?

**Comment by peternewman** [comment]
I'm closing this now @ltd9938 . Please feel free to comment if you're still having issues and we can re-open it.
