### ISSUE TITLE
ttyUSB0 message floods syslog

### ISSUE THREAD

**Issue by rbalykov** [OpenLightingProject/ola#1491]
common/io/Serial.cpp:149: device /dev/ttyUSB0 doesnt exist ... bla bla bla.
This message turns syslog to unreadable gigabytes of text.

**Comment by peternewman** [comment]
Hi @rbalykov ,

You need to either reduce your logging level (it's already an info level message), disable the plugin that's attempting to access it, or update the config for that plugin so it doesn't try to access it.

**Comment by peternewman** [comment]
I'm closing this now @rbalykov . Please feel free to comment if you're still having issues and we can re-open it.
