### ISSUE TITLE
/etc/init.d/olad will not load configured universes

### ISSUE THREAD

**Issue by naardehaaien** [OpenLightingProject/ola#1492]
Using the manual, I could get to the point to run OLA using "olad -l 3"

when I open the webservice xx.xx.xx.xx:9090/ola.html , on the left side at "universes", the configured universe is available.

I wanted to have OLA running when the raspberry pi starts up, so I copied this file https://github.com/OpenLightingProject/ola/blob/master/debian/ola.olad.init to /etc/init.d

now after booting the raspberry pi, the webservice works, but  the configured universe is not showing. When I kill the olad service, and start it manually by executing "olad -l 3" in a terminal,.. the universe is available again.

what can cause  the configured universe for not showing up, using the /etc/init.d/olad file?

**Comment by peternewman** [comment]
I'm closing this now @naardehaaien . Please feel free to comment if you're still having issues and we can re-open it.
