### ISSUE TITLE
ImportError with rdm_test_server.py

### ISSUE THREAD

**Issue by ssilverman** [OpenLightingProject/ola#1503]
When I try to run rdm_test_server.py, I get this error:

> Traceback (most recent call last):
  File "./rdm_test_server.py", line 41, in <module>
    from ola.testing.rdm.DMXSender import DMXSender
ImportError: No module named testing.rdm.DMXSender

I configured my `ola` build both with and without `--enable-python-libs` (I still don't know what that option really does), and copied all the files inside `tools/rdm` recursively into my `ola` install directory, under `lib/python2.7/site-packages/ola/testing/rdm`. Note that I had to create the `testing` and `testing/rdm` directory.

Still get that error. I don't know if this is a library naming or file location bug.

**Comment by ssilverman** [comment]
Well, isn't that interesting. I spent lots of time on this, but only when I posted the issue do I find a solution a short time after. Here's how I got it working:

1. Copied, recursively, all the files inside `tools/rdm/` to a new <code><i>ola-site-packages</i>/testing/rdm/</code> directory.
2. Created a zero-length `__init__.py` file that goes inside the new `testing/` directory.
3. Execute `run_test_server.py` but with the `PYTHONPATH` variable (can do this on the same commandline) set to the `site-packages/` directory in my `ola` install (absolute path).
4. The server wasn't serving pages, but then I discovered the `-d` option, which not only must be set to the `static` directory, but also specified as an absolute path; a relative path doesn't work.

Here's my commandline:
<pre>PYTHONPATH=<i>ola-site-packages</i> <i>rdm_programs</i>/rdm_test_server.py -d <i>rdm_programs</i>/static</pre>

Don't forget to have `olad` running.

**Comment by peternewman** [comment]
Hi @ssilverman 

You should be adding `--enable-rdm-tests` if you want the RDM tests (which will also add `--enable-python-libs` as the tests need the python libs.

What OS are you on? We've got packages for many OSes now, which is often the easier way to install OLA unless you want the bleeding edge.

However those steps are generally approximately what I do for development, only with symlinks rather than copying files.

The absolute path is for security, see here:
https://github.com/openlightingproject/ola/blob/master/tools/rdm/rdm_test_server.py#L468-L469

**Comment by ssilverman** [comment]
I'm on OSX (the latest) and have used homebrew to install the main `ola` distribution (my guess is that it does not have the RDM tests built in). That's where I ultimately copied over the `testing/rdm/` files.

When I build my own distro from git, and when I add the `--enable-rdm-tests` option to `./configure`, `make` doesn't create any `testing/` or `testing/rdm/` directories. How, then, can `rdm_test_server.py` import anything from the `ola.testing.rdm` package? Maybe I'm missing some Python understanding here?

**Comment by peternewman** [comment]
There's a `with-rdm-tests` on the Homebrew option:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/ola.rb#L23

I think when you do `make install` it will add the files where it needs to, but I've never tried as I only do it for dev, and would normally install a deb package if I needed a normal install.

**Comment by ssilverman** [comment]
I reinstalled with the `--with-rdm-tests` option and things work well now. I'll chalk this up to not knowing about that homebrew option. Hopefully, those who see this won't fall into the same trap.

**Comment by peternewman** [comment]
Glad to hear it. I don't use homebrew, but I wonder if it's worth raising a documentation or feature bug with them to make options more obvious @ssilverman ?

I suspect most people who use OLA on Mac don't use the RDM tests, and given they require Python and some other stuff, it probably still makes sense for them not to be a default option, which means you need to know there are options and that there is an RDM tests option to get them installed via that route.

Would you be willing to write a brief summary of what to do so we can update our docs with how to install it (including the RDM tests) via Homebrew on a Mac?

**Comment by ssilverman** [comment]
It's easy to miss the requirement of Homebrew install options unless you know they're there. So here's what I suggest. In the OLA documentation, when talking about install options, simply remind users to "add any RDM test options when provided by the installer". Give as many examples as possible. For example: "When installing with Homebrew, add the `--with-rdm-tests` option."

A second suggestion is just to make the `--with-rdm-tests` option the default. I haven't looked what the size difference of the install would be, but I can't imagine it's very large.

The fix was simple, but knowing it's there is the hard part.
