### ISSUE TITLE
ImportError of 'ola.ClientWrapper' with pyenv

### ISSUE THREAD

**Issue by soutaroumaejima** [OpenLightingProject/ola#1516]
There is import error of 'ola.ClientWrapper' with Python API when running example program.
This is error message.
```
maejima-dmx@maejimadmx-DS61:~/ola/python/examples$ python ola_send_dmx.py 
Traceback (most recent call last):
  File "ola_send_dmx.py", line 25, in <module>
    from ola.ClientWrapper import ClientWrapper
ImportError: No module named 'ola'
```

I want to use Python API on python3 and I uses `pyenv` to control version of python.
I think pyenv is maybe cause of this problem but I don't know how to solve it.
This is the information of paths.
```
maejima-dmx@maejimadmx-DS61:~/ola$ grep ^pythondir config.log
pythondir='${prefix}/lib/python3.5/site-packages'
maejima-dmx@maejimadmx-DS61:~/ola$ python -c "import sys; print (sys.path)"
['', '/home/maejima-dmx/.pyenv/versions/3.5.2/lib/python3.5/site-packages', '/home/maejima-dmx/ola', '/path/to/your/pythondir', '/home/maejima-dmx/.pyenv/versions/3.5.2/lib/python35.zip', '/home/maejima-dmx/.pyenv/versions/3.5.2/lib/python3.5', '/home/maejima-dmx/.pyenv/versions/3.5.2/lib/python3.5/plat-linux', '/home/maejima-dmx/.pyenv/versions/3.5.2/lib/python3.5/lib-dynload']
```

If you know solution about it, please tell me.

**Comment by peternewman** [comment]
What OS are you on and how did you install OLA @soutaroumaejima ?

**Comment by soutaroumaejima** [comment]
I'm sorry for insufficiency of set-up information. OS is Ubuntu 16.04.

This is installing packages before install OLA.
<details>
<summary>Install packages</summary>
<pre>
<code>
sudo apt-get install libcppunit-dev libcppunit-1.13-0v5 uuid-dev pkg-config libncurses5-dev libtool autoconf automake g++ libmicrohttpd-dev libmicrohttpd10 protobuf-compiler libprotobuf-lite9v5 python-protobuf libprotobuf-dev libprotoc-dev zlib1g-dev bison flex make libftdi-dev libftdi1 libusb-1.0-0-dev liblo-dev libavahi-client-dev python-numpy
</code>
</pre>
</details>
After install those, I downloaded OLA package by `git clone`.
Next, I run those command in `ola` and edited `enabled = True` in `ola-stageprofi.conf`.
<details>
<summary>Runnning commands</summary>
<pre>
<code>
cd ola
autoreconf -i
./configure --disable-all-plugins --enable-usbpro --enable-python-libs
export PYTHONPATH=$PYTHONPATH:/path/to/your/pythondir
make
make check
sudo make install
sudo ldconfig
</code>
</pre>
</details>

**Comment by peternewman** [comment]
> I'm sorry for insufficiency of set-up information. OS is Ubuntu 16.04.
Don't worry, you're not the first and somehow I suspect you won't be the last.

> export PYTHONPATH=$PYTHONPATH:/path/to/your/pythondir

Did you really run exactly that command? You're generally supposed to update it with your actual python directory.

In your case I think it will be /usr/local/ola something. Try doing `locate ClientWrapper.py` to see where it installed to.

**Comment by soutaroumaejima** [comment]
Thank you for your prompt response.
I tried `locate ClientWrapper.py` and I find that OLA modules are in  `/usr/local/lib/python3.5/site-packages` but my python don't recognize it because of pyenv. 
I inserted `sys.path.append('/usr/local/lib/python3.5/site-packages') in source code` and it went well!
I am very afraid of asking this kind of basic question...
Thank you very much!

**Comment by soutaroumaejima** [comment]
> It just installed into the python3.5 folder automatically did it?
Yes. OLA module was installed into python3.5 folder automatically

> Don't worry about basic questions, I've not played with the sys.path stuff in Python before, I'd have probably done it with PYTHONPATH or left it to the OS.
I'm glad to hear that. Editing PYTHONPATH maybe another solution.

>  Would you have just installed the pre-compiled packages if they supported Python 3? 
Yes, I would. In addition, if such package support changing of python 2 and 3 by pyenv, I was glad that its convenience.
 
> We may still have odd Python 3 issues, so let us know here if you have problems with that: #1506 
OK. I will do that from next time. Thank you!
