### ISSUE TITLE
IPv4Address should use Host order internally

### ISSUE THREAD

**Issue by ola-importer** [OpenLightingProject/ola#152]
_From [si...@nomis52.net](https://code.google.com/u/100927661077854655312/) on October 22, 2011 14:47:15_

The endianess isn't defined in the API at all which can lead to bugs. At the moment the InterfacePicker uses network order.

Define this to be host order, and convert where required.

_Original issue: http://code.google.com/p/open-lighting/issues/detail?id=151_

**Comment by peternewman** [comment]
Fixed in https://github.com/OpenLightingProject/ola/commit/de2a0a2f80896ba7b9b953e7bcb02dcab543f253 to sort in a human logical way.
