### ISSUE TITLE
ArtNet Plugin crashes?!

### ISSUE THREAD

**Issue by Maerchensarg** [OpenLightingProject/ola#1530]
Hello,

I have set up a new OLA instance according to the following scheme (RPiB3):

Fresh setup of 2018-11-13-raspbian-stretch-full.

```
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install git autoconf autotools-dev libsigsegv2 m4 libtool bison flex libossp-uuid-dev libprotoc-dev libcppunit-dev protobuf-compiler libmicrohttpd-dev qt4-qmake libqt4-dev
$ git clone https://github.com/OpenLightingProject/ola.git ola
$ cd ola
$ autoreconf -i
$ ./configure --disable-all-plugins --enable-artnet --enable-http --enable-spi
$ make
$ make check
$ sudo make install
$ sudo ldconfig
```

```
$ olad
Received Segmentation fault
/usr/local/lib/libolacommon.so.0(+0x7f498)[0x76de8498]
/lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0x0)[0x769ec6b0]
```

```
$ olad -l 4
[...]
olad/PluginManager.cpp:195: Trying to start ArtNet
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abgebrochen
```

The ArtNet plugin crashes. If I deactivate it in the "ola-artnet.conf", OLA starts without problems.

ArtNet configuration:
```
$ cat .ola/ola-artnet.conf 
always_broadcast = true
enabled = true
ip = 192.168.178.37
long_name = OLA - ArtNet node
net = 0
output_ports = 4
short_name = OLA - ArtNet node
subnet = 0
use_limited_broadcast = false
use_loopback = false
```

Unfortunately I'm not so experienced as to know what to do now. I have successfully installed OLA and ArtNet several times in this way in the last weeks, which is why I have no idea.

**Comment by peternewman** [comment]
Hmm, that probably confirms it then, I saw similar but hadn't had time to investigate properly yet. I think I've broken it in https://github.com/OpenLightingProject/ola/pull/1528 . Although the tests didn't pick it up.

If you build against a checkout of commit 3de3c866d574f346fb34d2a99d200ab994c06888 instead it should be fine.

Can you also confirm how your machine is setup, or run common/network/NetworkTester and share the output.

**Comment by Maerchensarg** [comment]
Thanks for your help. As I said, I don't have much idea, so I've done the following:

```
$ git checkout a6df5c448c98f9698ca2891d4de2727cc023c635 .
$ autoreconf -i
Makefile.am:196: warning: .PHONY was already defined in condition DX_COND_doc, which is included in condition TRUE ...
aminclude.am:161: ... '.PHONY' previously defined here
Makefile.am:15:   'aminclude.am' included from here
$ ./configure --disable-all-plugins --enable-artnet --enable-http --enable-spi
$ make
$ make check
$ sudo make install
$ sudo ldconfig
```

And it is working again. Thank you.

- - - 

I set up an old Raspberry Pi 3 B Model V1.2 with 2018-11-13-raspbian-stretch-full. Nothing special about it. Currently 320 LEDs are installed (SPI). The RPI is connected via LAN. WLAN is active, but not connected. If you need more details, please tell me.

**Comment by peternewman** [comment]
Great, that's good to hear @Maerchensarg .

I can reproduce it myself too, which should hopefully make this fairly easy to fix, sorry the bug slipped through. That's enough network info too, I wondered if you didn't have any active network connections, which seemed unlikely as you were trying to use Art-Net.

**Comment by peternewman** [comment]
Closed via https://github.com/OpenLightingProject/ola/pull/1531 . I'll re-open #1466 and make sure I test it a bit more thoroughly before merging next time. Apologies again.

**Comment by Maerchensarg** [comment]
No problem and thanks for the help. The RPi3 and OLA only are used to control an 8x42 WS2801 matrix (via Glediator / Jinx). I suspect to have some other small problems/questions. Is it possible to address them somewhere or should an issue simply be created on GitHub? I know about that Google Group.
