### ISSUE TITLE
Light Flattering - Enttec opendmx

### ISSUE THREAD

**Issue by SplotyCode** [OpenLightingProject/ola#1539]
Some of our lights use an external dimmer some not. 
The lamps with an external dimmer are sometimes Flattering with of the lamps seems to be random.
We have an old mixer and the light don't flatter when we use it. It is not the software that is running on the pc the values are not changing on the "Ola Dmx Monitor".

OS: Linux david-thinkpad 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Device: Enttec opendmx Adapter

OlA: 0.10.5

Plugins: FTDI USB DMX

**Comment by peternewman** [comment]
Hi @SplotyCode ,

Sorry to hear this. You say it happens sometimes, is there any logic as to when, e.g. at certain times or levels?

Do you have some other DMX devices, are they alright or not?

I assume you mean they're flashing? Roughly how quickly/often? Can you post a video?

Are you using ola_dmxconsole or the webpage to set the values? Can you try the former if you aren't using it, and if you are, can you try closing the webpage if you have it open.

Can we see some olad -l 4 logs please:
https://www.openlighting.org/ola/get-help/ola-faq/#How_do_I_get_olad_-l_4_logs

Please also have a read of this:
https://www.openlighting.org/ola/get-help/ola-faq/#What_are_the_recommended_USB_Device_to_use_with_OLA

**Comment by SplotyCode** [comment]
I will give your logs in a few days and a video. 
We are using an FTDI FT232RL USB to serial IC.
We have 3 led lights and 2 dimmers. The LEDs are working fine but the lights on the dimmer are 
flashing what lights are flashing is random but if we change the brightness it affects other lamps.
The light goes a bit down and then up to the set value. 

We are using the Java Api to set the values but we only set them but we don't rapidly set them so their is no change that our client could cause this.

**Comment by peternewman** [comment]
Thanks.

Are the LEDs fine still even if they're addressed to the same start addresses as the dimmers? Does the order of the fixtures make any difference?

How frequently are you setting the values roughly?

**Comment by SplotyCode** [comment]
I think we had a broken adapter. I will close this for now.
