### ISSUE TITLE
Lighting Designer

### ISSUE THREAD

**Issue by theoryshaw** [OpenLightingProject/ola#1549]
Hi,

My name is Ryan Schultz.  I'm an architect (the building kind) that has been practicing an open source approach to architecture/construction for a number of years. 

We host most of our projects on github.
https://github.com/OpeningDesign 

We have a number of jobs where we're looking to work with a lighting designer--looking for help on fixture layout and selection, and energy calculations. 

Was wondering if there's anyone on this Github project that would be interested in working with us. 

I do realize that a majority of contributors here are probably software engineers, but figured there might be some users here as well--users that might be equally excited about open source, and working 'out-in-the-open', as we do.

The following link will give you a better sense of what we do: http://openingdesign.com/about/

Feel free to email directly if interested. ryan@openingdesign.com
I'm also on https://riot.im/app/
username: @theoryshaw:matrix.org

Open to referrals as well.

Thank you Kindly, Ryan

**Comment by theoryshaw** [comment]
The following is one of our current projects we're looking for help on...
https://github.com/OpeningDesign/Organic_Grocery_Store/blob/d948bfb22245c7463bcd1675c41352c91a9d9126/Transfer/20190311%20-%20Permit%20Drawings/20190309%20-%20Organic%20Grocery%20Store%20-%20Drawings.pdf

**Comment by peternewman** [comment]
Hi @theoryshaw ,

I'll leave this here for a few weeks, but as it's not really a question or bug report, I'll close it soon.

You'll probably get more coverage if you post on our mailing list:
https://groups.google.com/forum/#!forum/open-lighting

**Comment by theoryshaw** [comment]
Thanks Peter, will do!  I appreciate the help.
