### ISSUE TITLE
New warnings with GCC9

### ISSUE THREAD

**Issue by yoe** [OpenLightingProject/ola#1553]
I received [Debian bug 925793](https://bugs.debian.org/925793), which produces a few new warnings of this type:

```
libs/acn/HeaderSetTest.cpp: In member function 'void HeaderSetTest::testTransportHeader()':
libs/acn/HeaderSetTest.cpp:78:29: error: implicitly-declared 'ola::acn::TransportHeader::TransportHeader(const ola::acn::TransportHeader&)' is deprecated [-Werror=deprecated-copy]
   78 |   TransportHeader header2 = header;
      |                             ^~~~~~
In file included from ./libs/acn/HeaderSet.h:30,
                 from libs/acn/HeaderSetTest.cpp:28:
../libs/acn/TransportHeader.h:58:8: note: because 'ola::acn::TransportHeader' has user-provided 'void ola::acn::TransportHeader::operator=(const ola::acn::TransportHeader&)'
   58 |   void operator=(const TransportHeader &other) {
      |        ^~~~~~~~
```

Basically, what happens here is that the compiler complains about a class which does have an assignment operator, but no copy constructor. You should probably add them.

**Comment by peternewman** [comment]
Thanks @yoe. Looks like we won't be able to test on Travis easily, as this seems to be the only PPA with a suitable package and it's not in Travis' approved list: https://launchpad.net/~doko/+archive/ubuntu/toolchain

**Comment by peternewman** [comment]
See also what looks to be the same thing on Fedora:
https://paste.fedoraproject.org/paste/yCwhpRW3hc3wALehI6sspw

**Comment by yoe** [comment]
What's the status on this? The severity of this bug in Debian just got bumped, and it is likely that it will be bumped again soon.

**Comment by peternewman** [comment]
> What's the status on this? The severity of this bug in Debian just got bumped, and it is likely that it will be bumped again soon.

Patches welcome! :stuck_out_tongue: 

I can try and have a go next week if no-one has done it before then if it's as simple as adding a copy constructor, but I'd need someone else to sanity test it.

**Comment by peternewman** [comment]
See #1583

**Comment by peternewman** [comment]
Done via #1578
