### ISSUE TITLE
Support for Eurolite USB-DMX512-PRO Interface Mk2

### ISSUE THREAD

**Issue by Rene2109** [OpenLightingProject/ola#1555]
Can't get this Eurolite interface to work. I think it should use the usbpro plugin as it contains a FTDI Serial Converter. Usbpro detects it, but gets no answer from the device. Is there someone who experienced this or a similar issue before?

Error message: Usb Widget didn't respond to messages, esta id 0, device id 0

**Comment by peternewman** [comment]
See #1292 and #1556 which work on adding support for the Mk2. It's a different protocol to the USB Pro based devices, so that plugin isn't really appropriate. But practically an identical protocol to the original Eurolite USB-DMX512-PRO, hence it's being added to the USB DMX plugin.

**Comment by peternewman** [comment]
This has now gone in via https://github.com/OpenLightingProject/ola/pull/1556 and will be in 0.11.0, or is in master now if you compile from git.
