### ISSUE TITLE
error: explicitly assigning value of variable of type 'ola::DmxBuffer' to itself

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#1564]
```
common/utils/DmxBufferTest.cpp:197:10: error: explicitly assigning value of
      variable of type 'ola::DmxBuffer' to itself
      [-Werror,-Wself-assign-overloaded]
  buffer = buffer;
  ~~~~~~ ^ ~~~~~~
1 error generated.
```

Is the error when I am up to date with origin/master (and for this branch as well)

_Originally posted by @kecramer in https://github.com/OpenLightingProject/ola/pull/1561#issuecomment-502122886_

**Comment by janosvitok** [comment]
https://github.com/OpenLightingProject/ola/blob/master/common/utils/DmxBufferTest.cpp#L197
I guess this is intentional check whether assignment operation survives self-assignment.

However I miss there any explicit checks for consistency after self assignment. Only implicit ones are present (i.e. the code does not crash).

**Comment by peternewman** [comment]
> https://github.com/OpenLightingProject/ola/blob/master/common/utils/DmxBufferTest.cpp#L197
> I guess this is intentional check whether assignment operation survives self-assignment.

I think that's the idea based on the comment @janosvitok .

> However I miss there any explicit checks for consistency after self assignment. Only implicit ones are present (i.e. the code does not crash).

Do you mean checking the contents of buffer is still equal to what it was initialised to? Do you fancy trying to add some further tests around this?

I think to workaround the warning/error we might need to add this flag to the relevant bit of test code (but ideally just that bit, not everywhere), although I think when I looked before, GCC complains if passed this flag (or LLVM if it was GCC throwing it):
-Wno-self-assign-overloaded

**Comment by peternewman** [comment]
> I think to workaround the warning/error we might need to add this flag to the relevant bit of test code (but ideally just that bit, not everywhere), although I think when I looked before, GCC complains if passed this flag (or LLVM if it was GCC throwing it):
> -Wno-self-assign-overloaded

We may be able to workaround this problem using the push/pop idea @yoe is using here:
https://github.com/OpenLightingProject/ola/pull/1583/commits/67234e2cd617b6330c721f003cfc5edd9afa9d28

**Comment by peternewman** [comment]
@kecramer or anyone else, which compiler does this happen on, I think it should be a fairly simple fix but it would be nice to test it.

**Comment by peternewman** [comment]
> https://github.com/OpenLightingProject/ola/blob/master/common/utils/DmxBufferTest.cpp#L197
> I guess this is intentional check whether assignment operation survives self-assignment.

Yeah agreed.

> However I miss there any explicit checks for consistency after self assignment. Only implicit ones are present (i.e. the code does not crash).

I've worked around the issue, and added some basic tests in https://github.com/OpenLightingProject/ola/pull/1426/files was that the sort of thing you meant @janosvitok ?

> @kecramer or anyone else, which compiler does this happen on, I think it should be a fairly simple fix but it would be nice to test it.

We already had it in #1426 so ignore that!

**Comment by janosvitok** [comment]
> > However I miss there any explicit checks for consistency after self assignment. Only implicit ones are present (i.e. the code does not crash).
> 
> I've worked around the issue, and added some basic tests in https://github.com/OpenLightingProject/ola/pull/1426/files was that the sort of thing you meant @janosvitok ?

Yes, something like that.

**Comment by peternewman** [comment]
Great, I'll close this then @janosvitok !
