### ISSUE TITLE
USB Pro Extra Byte

### ISSUE THREAD

**Issue by DaAwesomeP** [OpenLightingProject/ola#1566]
I was debugging some issues with my Arduino library and ran into something that doesn't match the Enttec spec. When I have my device as either emulating an DMXKing ultraDMX Micro or my DMXUSB device, It sends packet with an extra byte after the message length:
```
7e 06 02 00 00 ea e7
            ^^ 
This is an extra byte that is always 0. 
This is a packet to adjust only channel 1.
```
I did not check is channel 512 is actually 512 or if it is all shifted forward one.

**Comment by DaAwesomeP** [comment]
This could have been caused by my unmerged modifications from my own build, but I don't think I touched that code at all, and this is not using my plugin.

**Comment by DaAwesomeP** [comment]
Hmmm I'm not sure what caused this. I ran it again without the serial sniffer and my first LED is coming on now.

**Comment by DaAwesomeP** [comment]
The issue went away. Sorry for pinging everyone's emails.

**Comment by peternewman** [comment]
Glad you've sorted it @DaAwesomeP , let us know if it happens again.
