### ISSUE TITLE
Build fails when cross-compiling

### ISSUE THREAD

**Issue by DragoonBoots** [OpenLightingProject/ola#1567]
After a couple days of google-fu getting me incrementally closer, I've hit a wall while cross-compiling ola.  The configure steps run fine (no plugins but dummy at all for now, trying to keep complexity to a minimum by building only the base), but the build fails while linking.

[Here's a link to the full build output.](https://gist.github.com/DragoonBoots/6ec422c7e9286fa07a08d8dbb3e42e1a)  See below for a snippet when it starts failing.

Looking at the filesystem, `liboladummy.so.0` and `libolaserverplugininterface.so.0` were built and exist in the source tree at `plugins/dummy/.libs/liboladummy.so.0` and `olad/plugin_api/.libs/libolaserverplugininterface.so.0`.  I have a feeling this is related to an issue I ran into earlier with libtool's library archive files referring to the wrong path.  However, there's no opportunity to fix this during the build process because the libraries are build as part of the same make target as the rest of the program.

If it's relevant, I'm using [dockcross](https://github.com/dockcross/dockcross) to handle all of this, as my end goal is to integrate it into a CI workflow with a client program I've written.  Haven't gotten to that point yet.  [This gist](https://gist.github.com/simark/1167861bfabe21dd7658) has so far anticipated most of the issues I've run into (including the `.la` file issue).  [This is the dockerfile](https://gist.github.com/DragoonBoots/4097ca3a80855181c77c6ef6862343e8).

Any ideas?  I feel close but I'm running up against the limits of my knowledge here.

```
libtool: link: ( cd "olad/.libs" && rm -f "libolaserver.la" && ln -s "../libolaserver.la" "libolaserver.la" )
/bin/bash ./libtool  --tag=CXX   --mode=link /usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-g++ -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot/usr/local/include -Werror -Wno-error=deprecated-declarations -g -O2 -std=gnu++11 -Wno-error=deprecated-declarations -pthread -rdynamic -L/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot/usr/local/lib -o olad/olad olad/Olad.o olad/libolaserver.la common/libolacommon.la ola/libola.la -ldl 
libtool: link: /usr/xcc/arm-cortexa8_neon-linux-gnueabihf/bin/arm-cortexa8_neon-linux-gnueabihf-g++ -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot/usr/local/include -Werror -Wno-error=deprecated-declarations -g -O2 -std=gnu++11 -Wno-error=deprecated-declarations -pthread -rdynamic -o olad/.libs/olad olad/Olad.o  -L/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/arm-cortexa8_neon-linux-gnueabihf/sysroot/usr/local/lib olad/.libs/libolaserver.so common/.libs/libolacommon.so ola/.libs/libola.so -ldl -pthread
/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/lib/gcc/arm-cortexa8_neon-linux-gnueabihf/6.3.1/../../../../arm-cortexa8_neon-linux-gnueabihf/bin/ld.bfd: warning: liboladummy.so.0, needed by olad/.libs/libolaserver.so, not found (try using -rpath or -rpath-link)
/usr/xcc/arm-cortexa8_neon-linux-gnueabihf/lib/gcc/arm-cortexa8_neon-linux-gnueabihf/6.3.1/../../../../arm-cortexa8_neon-linux-gnueabihf/bin/ld.bfd: warning: libolaserverplugininterface.so.0, needed by olad/.libs/libolaserver.so, not found (try using -rpath or -rpath-link)
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::GetUIDs(ola::rdm::UIDSet*) const'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::SetMergeMode(ola::Universe::merge_mode)'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::Devices() const'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::GetRDMTransactionNumber()'
olad/.libs/libolaserver.so: undefined reference to `vtable for ola::FileBackedPreferences'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::RemoveSourceClient(ola::Client*)'
olad/.libs/libolaserver.so: undefined reference to `ola::Client::Client(ola::proto::OlaClientService_Stub*, ola::rdm::UID const&)'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::GetUniverse(unsigned int) const'
olad/.libs/libolaserver.so: undefined reference to `vtable for ola::FilePreferenceSaverThread'
olad/.libs/libolaserver.so: undefined reference to `vtable for ola::MemoryPreferences'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::OutputPorts(std::vector<ola::OutputPort*, std::allocator<ola::OutputPort*> >*) const'
olad/.libs/libolaserver.so: undefined reference to `ola::Client::DMXReceived(unsigned int, ola::DmxSource const&)'
olad/.libs/libolaserver.so: undefined reference to `ola::PreferencesFactory::NewPreference(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
olad/.libs/libolaserver.so: undefined reference to `ola::PortManager::PatchPort(ola::OutputPort*, unsigned int)'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::~UniverseStore()'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::UnregisterAllDevices()'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::UniverseStore(ola::Preferences*, ola::ExportMap*)'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::GetDevice(unsigned int) const'
olad/.libs/libolaserver.so: undefined reference to `ola::PreferencesFactory::~PreferencesFactory()'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::RemoveSinkClient(ola::Client*)'
olad/.libs/libolaserver.so: undefined reference to `ola::Client::SetUID(ola::rdm::UID const&)'
olad/.libs/libolaserver.so: undefined reference to `ola::FilePreferenceSaverThread::FilePreferenceSaverThread()'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::GarbageCollectUniverses()'
olad/.libs/libolaserver.so: undefined reference to `typeinfo for ola::PreferencesFactory'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::CleanStaleSourceClients()'
olad/.libs/libolaserver.so: undefined reference to `ola::PortManager::UnPatchPort(ola::OutputPort*)'
olad/.libs/libolaserver.so: undefined reference to `ola::MemoryPreferences::~MemoryPreferences()'
olad/.libs/libolaserver.so: undefined reference to `ola::PortManager::SetPriorityStatic(ola::Port*, unsigned char)'
olad/.libs/libolaserver.so: undefined reference to `ola::PluginAdaptor::PluginAdaptor(ola::DeviceManager*, ola::io::SelectServerInterface*, ola::ExportMap*, ola::PreferencesFactory*, ola::PortBrokerInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*)'
olad/.libs/libolaserver.so: undefined reference to `ola::Client::GetUID() const'
olad/.libs/libolaserver.so: undefined reference to `vtable for ola::PortBroker'
olad/.libs/libolaserver.so: undefined reference to `ola::PortManager::PatchPort(ola::InputPort*, unsigned int)'
olad/.libs/libolaserver.so: undefined reference to `ola::FilePreferenceSaverThread::Join(void*)'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::IsActive() const'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::GetList(std::vector<ola::Universe*, std::allocator<ola::Universe*> >*) const'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::AddSinkClient(ola::Client*)'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::DeviceCount() const'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::DeviceManager(ola::PreferencesFactory*, ola::PortManager*)'
olad/.libs/libolaserver.so: undefined reference to `ola::PortManager::UnPatchPort(ola::InputPort*)'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::SourceClientDataChanged(ola::Client*)'
olad/.libs/libolaserver.so: undefined reference to `vtable for ola::StringValidator'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::DeleteAll()'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::~DeviceManager()'
olad/.libs/libolaserver.so: undefined reference to `vtable for ola::plugin::dummy::DummyPlugin'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::UIDCount() const'
olad/.libs/libolaserver.so: undefined reference to `ola::UniverseStore::GetUniverseOrCreate(unsigned int)'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::SetName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::InputPorts(std::vector<ola::InputPort*, std::allocator<ola::InputPort*> >*) const'
olad/.libs/libolaserver.so: undefined reference to `ola::DeviceManager::SendTimeCode(ola::timecode::TimeCode const&)'
olad/.libs/libolaserver.so: undefined reference to `ola::Universe::RunRDMDiscovery(ola::BaseCallback1<void, ola::rdm::UIDSet const&>*, bool)'
olad/.libs/libolaserver.so: undefined reference to `ola::PortManager::SetPriorityInherit(ola::Port*)'
collect2: error: ld returned 1 exit status
Makefile:9592: recipe for target 'olad/olad' failed
make[2]: *** [olad/olad] Error 1
make[2]: Leaving directory '/work/src/ola-target'
Makefile:16503: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/work/src/ola-target'
Makefile:7316: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by peternewman** [comment]
Sorry I've not played with cross-compiling. @simark might be able to advise.

Have you tried building the version @simark had success with (i.e. ola-0.10.0) or does that have other problems which we've subsequently fixed?

**Comment by peternewman** [comment]
There's a Dockerfile here:
https://github.com/bartfeenstra/docker-ola
or
https://github.com/JustGav/docker-ola
or
https://github.com/s1lvester/docker-ola / https://github.com/jakewright/docker-ola

Although I'm guessing not doing a cross-compile is too slow?

**Comment by DragoonBoots** [comment]
Thanks for the fast response!  I had to use protobuf 2.6.1 to get very far with ola 0.10.0 (which makes sense), but no dice.  I'm beginning to suspect this problem stems from different sysroots in the entire build process.  I've got a couple of theories to simplify the build process and eliminate this entirely.  Just wanted to check in here given that the [wiki page on the process](https://wiki.openlighting.org/index.php/Cross_Compiling_OLA) says in the first paragraph that it doesn't work.

I'll try to report back so others can benefit from my frustration.

**Comment by peternewman** [comment]
I know next to nothing about cross-compiling, but I'd assume you want a single sysroot to do all your cross-compile in, so building the dependencies and then OLA itself. Or is that not what you mean by: 

> I'm beginning to suspect this problem stems from different sysroots in the entire build process. 

That wiki page was written in 2013, so I'd hope things have moved on a bit!

**Comment by DragoonBoots** [comment]
libtool doesn't understand when it's operating in a separate sysroot, so this leads to it looking for libraries in the wrong places.  It's what the `sed` line in the dockerfile is for - it corrects the directory the library is found in.

However, it turns out that the fine folks at [Buildroot](https://buildroot.org/) have figured this out already, and I've managed to create a package that works with the latest git master branch.  It builds a reasonably reasonable Raspberry Pi image in about an hour, although I have yet to test it in any serious capacity.  Is this something the project might be interested in?  The images linked on the website are ancient history (yes, you've come a long way).

**Comment by DragoonBoots** [comment]
Otherwise closing this issue since the problem has been resolved.

**Comment by peternewman** [comment]
> libtool doesn't understand when it's operating in a separate sysroot, so this leads to it looking for libraries in the wrong places. It's what the `sed` line in the dockerfile is for - it corrects the directory the library is found in.

Ah okay.

> However, it turns out that the fine folks at [Buildroot](https://buildroot.org/) have figured this out already, and I've managed to create a package that works with the latest git master branch. It builds a reasonably reasonable Raspberry Pi image in about an hour, although I have yet to test it in any serious capacity. Is this something the project might be interested in?

We were in there once, but got removed as no-one was maintaining it, we've fixed the mentioned issue, but not released yet for various reasons so it would need a patch file for the moment. See also:
https://gitlab.savoirfairelinux.com/netdsa/buildroot/commit/e692e1f2b2285c18057e2c70cc1d9d0cfdb15d5e

I'd broadly say the more packaging systems we're in the better, so it makes it easier for people to use their preferred toolchain. E.g. we added ourselves to Macports and somone else has added us to Homebrew (so multiple choices on the same OS). People will always prefer to stick with what they know, so if you're happy to add it, and I guess maintain the packaging if necessary @DragoonBoots , that would be great.

> The images linked on the website are ancient history (yes, you've come a long way).

Do you mean our website? Yeah they haven't been touched in ages. I've prioritised writing code rather than building distributions and no-one else has really stepped forward to do that.

I'd also point out if you're using Raspbian, we're in Debian now, so unless you want bleeding edge, apt-get would be my recommended option on a Raspbian-based Pi.

**Comment by hippyau** [comment]
FYI, I copied the `Config.in` and `ola.mk` files from the [https://gitlab.savoirfairelinux.com/netdsa/buildroot/commit/e692e1f2b2285c18057e2c70cc1d9d0cfdb15d5e](https://gitlab.savoirfairelinux.com/netdsa/buildroot/commit/e692e1f2b2285c18057e2c70cc1d9d0cfdb15d5e) and pasted into a buildroot I started from scratch today, and it seems to build just fine.
