### ISSUE TITLE
OLA sACN not outputting universes

### ISSUE THREAD

**Issue by mattsmithadelaide** [OpenLightingProject/ola#1577]
Hi there, I'm having an issue where I can't output all 32 universes on my raspberry pi. It works fine on my mac. I have tried updating the igmp_max_memberships to 32 but this hasn't fixed it. I can't find any more information about this issue

Does anyone have any suggestions?  Thanks in advance

**Comment by peternewman** [comment]
Hi @mattsmithadelaide ,

I guess you've sorted it as you've closed the issue? Would you mind sharing what the fix was for the benefit of other people in future please?
