### ISSUE TITLE
g++: Internal error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by ola-importer** [OpenLightingProject/ola#158]
_From [jbai...@san.rr.com](https://code.google.com/u/109697936999308686448/) on November 03, 2011 20:17:25_

What steps will reproduce the problem? 1. Download OLA
2. Install libraries per http://opendmx.net/index.php/OLA_on_Linux 3. Rune ./configure and make What is the expected output? What do you see instead? I dont know what the expected output is but it says 

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../include -Wall -Wformat -W -pthread -g -O2 -MT libolaproto_la-Ola.pb.lo -MD -MP -MF .deps/libolaproto_la-Ola.pb.Tpo -c Ola.pb.cc  -fPIC -DPIC -o .libs/libolaproto_la-Ola.pb.o
g++: Internal error: Killed (program cc1plus)
Please submit a full bug report.
See file:///usr/share/doc/gcc-4.4/README.Bugs for instructions.
make[4]: **\* [libolaproto_la-Ola.pb.lo] Error 1
make[4]: Leaving directory `/root/ola-0.8.14/common/protocol'
make[3]: *** [all] Error 2
make[3]: Leaving directory`/root/ola-0.8.14/common/protocol'
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory `/root/ola-0.8.14/common'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/root/ola-0.8.14'
make: **\* [all] Error 2 What version of the product are you using? On what operating system? 0.8.14, Debian on a armel processer Please provide any additional information below.

_Original issue: http://code.google.com/p/open-lighting/issues/detail?id=157_

**Comment by peternewman** [comment]
If anyone hits this in future, they can also try the info here https://github.com/OpenLightingProject/ola/issues/1103 .
