### ISSUE TITLE
Would be useful for USB serial to scan more names on OSX

### ISSUE THREAD

**Issue by ssilverman** [OpenLightingProject/ola#1601]
https://github.com/OpenLightingProject/ola/blob/d1010976c47de23dc6031749179f8d92596b7e8d/plugins/usbpro/UsbSerialPlugin.cpp#L60

I have some non-FTDI-based devices that show up as `cu.usbmodem*` (where `*` is some digits) and would love if these were to be scanned in addition to the `cu.usbserial-*` devices.

**Comment by ssilverman** [comment]
Well, that was easy. I found `~/.ola/ola-usbserial.conf` and added a new `device_prefix` line.

**Comment by peternewman** [comment]
I think I missed this at the time due to $work @ssilverman .

If this happens reliably for some devices, feel free to do a PR to add this additional/alternative prefix to the default config, to avoid these questions in future.
