### ISSUE TITLE
Installing OLA on Ubuntu 18.10

### ISSUE THREAD

**Issue by jochem4207** [OpenLightingProject/ola#1618]
I'm trying to follow instructions but so many packages are outdated or missing. I'm no expert in the field so i'm adding an issue.

This page i'm following: https://www.openlighting.org/ola/linuxinstall/ (for the ubuntu part). 

**Problem**
Many packages missing, not working anymore , giving me a headache

**Question**
Does anyone have a correct apt-get install .xxxx list for OLA?

**Comment by jochem4207** [comment]
configure: error: OLA currently requires protobuf < 3.2, see issue 1192
stuck at yet another issue. its fun.

**Comment by peternewman** [comment]
Just do this (unless you want the bleeding edge version):
```
apt-get update
apt-get install ola
#Optional:
apt-get install ola-python ola-rdm-tests
```

Which version of OLA source were you trying to compile when you got that error?
