### ISSUE TITLE
Makefile flake8 target

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#1619]
Add a flake8 Makefile target since it's available via pypi.

_Originally posted by @brucelowekamp in https://github.com/OpenLightingProject/ola/pull/1605/files_

Sounds good although I suspect the flake8 thing should be part of the lint target rather than check, as per https://github.com/OpenLightingProject/ola/issues/691 because it's nice to encourage people to run make check, but we don't want to force them to have flake8 installed. Although for bonus points configure could handle it all seamlessly. Although I suspect it should still be a separate target, I often write rather messy code while developing, but still running make check, which I wouldn't want to fail on that, before tidying up ready for committing.

_Originally posted by @peternewman in https://github.com/OpenLightingProject/ola/pull/1605/files_

See also #691

**Comment by peternewman** [comment]
This has likely got a lot easier now we've switched to a `.flake8` config file in #1637

**Comment by stefansiegfried** [comment]
Could I take a look at this issue?

**Comment by peternewman** [comment]
Yeah certainly, I've assigned you too.
