### ISSUE TITLE
autoreconf error AC_CONFIG_MACRO_DIRS

### ISSUE THREAD

**Issue by iFreilicht** [OpenLightingProject/ola#1626]
I just tried building from source at the current master, and hit a hurdle at the very first step:

    $ autoreconf -i
    libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
    libtoolize: copying file 'config/ltmain.sh'
    .ibtoolize:   error: AC_CONFIG_MACRO_DIRS([config]) conflicts with ACLOCAL_AMFLAGS=-I config
    autoreconf: libtoolize failed with exit status: 1

After commenting out line 13 in `Makefile.am`, `autoreconf` and `./configure` ran through from start to finish, down to "Now type 'make [<target>]' ".

**Comment by iFreilicht** [comment]
Sorry, I was building from master, not from 0.10.7

**Comment by peternewman** [comment]
Hi @iFreilicht ,

master should still work too, can you give us some more detail on OS etc?

Is it Windows by any chance? See this:
https://pete.akeo.ie/2010/12/that-darn-libtoolize-acconfigmacrodirm4.html

**Comment by iFreilicht** [comment]
No, I'm on Ubuntu 18.04 LTS. Actually I'm having trouble with the whole build, even on 0.10.7;

```
sh ./include/ola/rdm/make_rdm_codes.sh ./common/protocol/Ola.proto > ./include/ola/rdm/RDMResponseCodes.h
: not foundla/rdm/make_rdm_codes.sh: 3: ./include/ola/rdm/make_rdm_codes.sh: 
./include/ola/rdm/make_rdm_codes.sh: 80: ./include/ola/rdm/make_rdm_codes.sh: Syntax error: word unexpected (expecting "then")
```

I also saw that none of the .proto files have a `syntax =` line, which leads to a lot of warnings.

**Comment by peternewman** [comment]
Where did you get the source, via git?

What happens if you run this via the CLI:
`sh ./include/ola/rdm/make_rdm_codes.sh ./common/protocol/Ola.proto`

I think the syntax line upsets an older protobuf, they're only warnings anyway.

**Comment by iFreilicht** [comment]
Ahhh that got me onto the right track. I had incorrect line endings checked out.

Now everything compiles as it should. However, I am seeing that `ola/OlaClientTester` fails when running `make check`.

**Comment by iFreilicht** [comment]
And I just tested it @ 0.10.7, there it fails as well.

**Comment by peternewman** [comment]
> Ahhh that got me onto the right track. I had incorrect line endings checked out.

Curious, I'm surprised that happened on Linux.
 
> Now everything compiles as it should. However, I am seeing that `ola/OlaClientTester` fails when running `make check`.
> 
> EDIT: Here's the output: https://pastebin.com/XBfvQnsn
> This was @ master

As per the log, do you have another copy of olad running?:
`Check for another instance of olad running`

**Comment by iFreilicht** [comment]
> Curious, I'm surprised that happened on Linux.

I'm dualbooting and share a data drive between windows and linux. This isn't a problem, unless it is :D

> Curious, I'm surprised that happened on Linux.

There you go, after having trouble building it I installed it from `apt`. After stopping olad, all tests ran through 100%! Thanks for your help!

**Comment by peternewman** [comment]
Great, glad to hear it @iFreilicht !
