### ISSUE TITLE
Question: Why is the last release from July 2018?

### ISSUE THREAD

**Issue by kilianspeder** [OpenLightingProject/ola#1663]
I'm getting into OLA right now and found the last release being from July 2018. Since them there were many commits and my question is why there hasn't been any other release since then. Does somebody know something about this?
Thanks in advance :-)

**Comment by peternewman** [comment]
Hi @kilianspeder ,

I knew it was quite a while ago, I must admit I didn't realise we'd passed two years.

So a few reasons, firstly it takes quite a bit of effort to release, hence why we're not doing it after every commit or weekly for example. There's an eighteen step checklist which I or someone else has to do just to cut the release on GitHub.

Then people need to deal with the downstream repos (Debian, Macports and Homebrew; the latter two being particularly challenging as our test build Mac has unfortunately died. other people deal with Arch and other bits.

The other reason is that the upstream software we uses, such as compilers, Protobuf, libmicrohttpd etc seem to keep breaking things for us (by making their own new releases which don't have full backwards compatibility). You can see a big chunk of the ones of those we've fixed here:
https://github.com/OpenLightingProject/ola/milestone/17?closed=1

However there are a number still outstanding:

**Comment by peternewman** [comment]
Closing this now 0.10.8 is out. Hopefully 0.11.0 with ALL the new features won't be too far behind...
