### ISSUE TITLE
UART on Pi Issues

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#1665]
From an IRC user:

> (22:33:06) cLx: hi !
> (22:35:00) cLx: wanted to use the Native UART DMX Plugin on raspberry pi 1, but even if i state "init_uart_clock=16000000" in config.txt, i still get "Failed to set baud rate to 250k"  ... any ideas ?
> (23:41:36) cLx: copied this into a C file https://github.com/OpenLightingProject/ola/blob/master/common/io/ExtendedSerial.cpp, and managed to switch the baudrate to 250000 .
> (23:42:05) cLx: maybe #if defined(HAVE_STROPTS_H) && defined(HAVE_TERMIOS2) is disabled on debian ?
> (23:42:28) cLx: (raspbian)

Has anyone else seen this?

**Comment by peternewman** [comment]
@clx are you that user or a different one?

**Comment by FloEdelmann** [comment]
I did not have the same problem in my Bachelor's thesis, which I wrote about OLA on a Raspberry Pi 1.

You can read about my UART configuration in chapter 4.2.2: https://github.com/FloEdelmann/bachelor

**Comment by peternewman** [comment]
Thanks @FloEdelmann . When did you try, there's a bit of me wonders if this change has crept in with a newer OS release?

**Comment by FloEdelmann** [comment]
I did last check it when writing/handing in my thesis (November 2017). So, a new Raspbian version might very well have caused this new issue.

**Comment by clxjaguar** [comment]
Oh. That IRC user was me! Thanks for having forwarded it here. I had simply to recompile OLA from source to make it work. I wrote things here. http://clx.freeshell.org/ola-raspberry-uart-dmx.html

**Comment by peternewman** [comment]
Glad we got you eventually @clxjaguar .

Looking at the code a bit, it went in as part of 811, for HAVE_TERMIOS2 to be defined, you need to be able to create a termios2 struct, which means you need to include `<asm/termios.h>`. This looks to be in these files:
https://packages.debian.org/search?searchon=contents&keywords=asm%2Ftermios.h

So I'm guessing you have at least one of those on your Pi, whereas the compiled version didn't.

What version of OLA did you have on your Pi before recompiling?

@yoe might be able to advise, but I wonder if we need linux-libc-dev or linux-headers or something in our control file?

**Comment by yoe** [comment]
We shouldn't have to depend on linux-libc-dev nor include anything under asm/ directly... those are meant for libc, not for applications.

I'll have a more detailed look when I get home again later this week.

**Comment by jeweljacob387** [comment]
Installed OLA 0.10.8 in Raspberry PI 3 using `sudo apt-get install ola`.
I'm having the same issue. Do we have any update in the issue or any work around's?
Log:

> Dec 15 10:42:31 raspberrypi olad: olad/PluginManager.cpp:195: Trying to start UART native DMX
> Dec 15 10:42:31 raspberrypi olad: plugins/uartdmx/UartWidget.cpp:180: Failed to set baud rate to 250k
> Dec 15 10:42:31 raspberrypi olad: plugins/uartdmx/UartDmxPlugin.cpp:82: Unable to setup device for output, device ignored /dev/ttyAMA0

**Comment by gnosis953** [comment]
I also have this problem. Can you help please?

Same logs are shown.

**Comment by peternewman** [comment]
See also #1749 .

There's a fix in #1760 which compiles on a Pi for me, I'm just looking for someone to test and confirm it outputs DMX correctly too, which it sounds very much like it might do.

Feel free to pull that patch or branch and compile it which should do the job.

> We shouldn't have to depend on linux-libc-dev nor include anything under asm/ directly... those are meant for libc, not for applications. I'll have a more detailed look when I get home again later this week.

@yoe I'd be curious on any further input, as pulling in `asm/termbits.h` seems to be the only way round it from what we've done and from what others have worked around.

**Comment by peternewman** [comment]
I'm closing this now that's been merged, but happy to revisit/reopen if we can do it in a better way @yoe .
