### ISSUE TITLE
set all channels to 0 via terminal

### ISSUE THREAD

**Issue by magdesign** [OpenLightingProject/ola#1666]
Trying to send the "**set all channels to 0**" (blackout) command via terminal command in Linux.

Could not figure out any fast and simple way, 
running `ola_dmxconsole ` and then simulating `b` key does not look very professional for me.
Also thinking about simulating the function from the OLA webinterface (does this make sense?)

Any hints are very welcome!

**Comment by magdesign** [comment]
Finally figured out the most simple solution with a script:

```
#!/bin/bash

#this sets all 512 dmx channels on universe 1 to 0 = blackout

sudo ola_set_dmx --universe 1 --dmx 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

exit
```

**Comment by peternewman** [comment]
Hi @magdesign ,

I'm glad you've sorted this out. That's probably the simplest way currently. Although this came up recently and so this will get merged in soon:
https://github.com/OpenLightingProject/ola/pull/1607/files#diff-8b4a836dc403b1fb18a53461a767326d

You could also pull that code in and recompile yourself in the short term.

Your only other option is probably:
http://docs.openlighting.org/ola/man/man1/ola_streaming_client.1.html

But ola_set_dmx is probably better.

**Comment by magdesign** [comment]
Any nice solution to fade to black so far?
My [bash script](https://github.com/OpenLightingProject/ola/issues/1666#issuecomment-699621538)  is just turning every light to black immediately, fading over a few seconds would be nice, but with bash fading down the numbers
e.g. 30 universes with 512 channels is too slow on a raspberry... any  ideas?

**Comment by peternewman** [comment]
> Any nice solution to fade to black so far?

@magdesign this probably wants a new issue, as it's an entirely different question to what you asked before.

> My [bash script](https://github.com/OpenLightingProject/ola/issues/1666#issuecomment-699621538) is just turning every light to black immediately, fading over a few seconds would be nice, but with bash fading down the numbers

Can you give some more detail of what the source of DMX data is, and what is deciding when there should be a blackout? Are the channels continuing to change during the fade (e.g. a chase)? Do you want their levels scaled towards zero (like a grand master), or the maximum value restricted (top set)?

The best way is likely to be an OLA client receiving the source data, fading it to black if necessary, and outputting it on another universe which you then patch to your output. There was some discussion of options in the issue for the future feature of patcher v2 ( #280 ).

> e.g. 30 universes with 512 channels is too slow on a raspberry... any ideas?

Do you mean sending a blackout to 30 universes is slow, or something else? Not that I've really stress-tested it, but 30 universes on a Pi seems pretty good depending on the age of the Pi.

**Comment by magdesign** [comment]
I modified the set universes to 0 (black) bash script to be faster while scanning first how many universes exist and then setting the existing universes to 0 like this:


```
#!/bin/bash
universelist=($(ola_uni_info --list-universe-ids))

#iterate over existing universes to set dmx to 0 (black):

for i in "${universelist[@]}"
do
        sudo ola_set_dmx --universe $i --dmx 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 &

done
```
When executing the script, all lamps turn to black.
I am looking for a solution to fade them slowly to zero, for example within 2 seconds.

Since I am still no C coder I am currently trying to read out the channel values of each universe and iterate over them until they are zero, with bash, but it feels a bit stupid... ;)

**Comment by peternewman** [comment]
> I modified the set universes to 0 (black) bash script to be faster while scanning first how many universes exist and then setting the existing universes to 0

Yeah that will work, although you don't need to sudo (and indeed it may complain when you do).

> I am looking for a solution to fade them slowly to zero, for example within 2 seconds.
> 
> Since I am still no C coder I am currently trying to read out the channel values of each universe and iterate over them until they are zero, with bash, but it feels a bit stupid... ;)

You've managed to avoid actually answering any of my questions:

> Can you give some more detail of what the source of DMX data is, and what is deciding when there should be a blackout? Are the channels continuing to change during the fade (e.g. a chase)? Do you want their levels scaled towards zero (like a grand master), or the maximum value restricted (top set)?

Or more broadly what are you doing and why?

Are the values guaranteed not to change when you start trying to fade them out? Something else setting channel 1 back to 255 will make your code far more complicated.

How's your Python or Java or Javascript or Go?

You could use the Python `python/examples/ola_recv_dmx.py` and `ola_streaming_client` and some bash in between to modify the values, but as you say it will be rather heavyweight.

**Comment by magdesign** [comment]
sorry, to deep in the terminal  :-)
> Can you give some more detail of what the source of DMX data is, and what is deciding when there should be a blackout? Are the channels continuing to change during the fade (e.g. a chase)? Do you want their levels scaled towards zero (like a grand master), or the maximum value restricted (top set)?

I am playing a recorded sequence which was recorded with `ola_recorder` containing at least one universe, 
played back like `ola_recorder --no-verify-playback -i 1 -p show01`
 
when stopping the sequence somewhere, the lights will stay as they are, which causes the lights to act weird when starting another show or the same again (if there is no blackout recorded).

I need a function to set all channels to 0, which works with sending zeros, but is not so nice to watch. There comes the idea with a fade.

> Are the values guaranteed not to change when you start trying to fade them out? Something else setting channel 1 back to 255 will make your code far more complicated.

Before creating a script which reads out all 512 values and then fades them to 0 in x amount of time, I thought to ask here, maybe a "ola_soft_blackout" or something is around....

> You could use the Python python/examples/ola_recv_dmx.py and ola_streaming_client and some bash in between to modify the values, but as you say it will be rather heavyweight.

Python sounds good, will have a look into this and post here when I got some fancy solution...

**Comment by peternewman** [comment]
> sorry, to deep in the terminal :-)

:laughing: :nerd_face: 

> I am playing a recorded sequence which was recorded with `ola_recorder` containing at least one universe,
> played back like `ola_recorder --no-verify-playback -i 1 -p show01`
> 
> when stopping the sequence somewhere, the lights will stay as they are, which causes the lights to act weird when starting another show or the same again (if there is no blackout recorded).

I assume you're using `Ctrl+C` or similar to stop ola_recorder part way through the sequence, and you don't know when you want to stop it when you start it?

> Before creating a script which reads out all 512 values and then fades them to 0 in x amount of time, I thought to ask here, maybe a "ola_soft_blackout" or something is around....

Yeah it doesn't really work as a standalone command as the input could keep changing, it needs to process the incoming data and modify it. I don't believe anyone has shared anything to do that yet.
 
> > You could use the Python python/examples/ola_recv_dmx.py and ola_streaming_client and some bash in between to modify the values, but as you say it will be rather heavyweight.
> 
> Python sounds good, will have a look into this and post here when I got some fancy solution...

If you're happy writing Python you can use the OLA Python client to do the above:
https://www.openlighting.org/ola/developer-documentation/python-api/

You'll just need to get some control data into it too, which could just be another universe of DMX or something, which a channel (or channels) corresponding to the desired signal level.
