### ISSUE TITLE
protobuf compilation issue

### ISSUE THREAD

**Issue by aroffringa** [OpenLightingProject/ola#1668]
I'm trying to compile ola on an up-to-date Debian testing machine, and got an error due to protobuf. The error says that `GOOGLE_CHECK` is not defined when compiling `protoc/StrUtil.cpp`. Debian testing has version 3.12 of protobuf (3.12.3-2 currently to be exact). One way or another, with this version of protobuf, `HAVE_GOOGLE_PROTOBUF_STUBS_LOGGING_H` never gets defined, and protoc/StrUtil.cpp has this piece of code near the beginning of the file:
```
#ifdef HAVE_GOOGLE_PROTOBUF_STUBS_LOGGING_H
#include <google/protobuf/stubs/logging.h>
#endif  // HAVE_GOOGLE_PROTOBUF_STUBS_LOGGING_H
```
Therefore, logging.h never gets included, resulting in the error. I could simply avoid this error by removing the #ifdef / #endif lines, to unconditionally include logging.h . I don't know if versions of protobuf without logging.h are still around, so I don't know if this is a generic solution.

Apart from this small fix, ola compiled fine.

**Comment by peternewman** [comment]
> One way or another, with this version of protobuf, `HAVE_GOOGLE_PROTOBUF_STUBS_LOGGING_H` never gets defined

Can we see your config.log please, as that define is actually set by us:
https://github.com/OpenLightingProject/ola/blob/master/configure.ac#L845

I guess also config.h and the compile log where it fails please.

**Comment by aroffringa** [comment]
Hmm I can't reproduce it. When things didn't compile I first tried removing and/or reinstalling/updating a few dependencies like protoc. Currently, when I start from a clean dir in an effort to reproduce the issue, everything immediately works. I did take a look at the config.h beforehand, which only had these google protobuf defines:
```
/* Define to 1 if you have the <google/protobuf/io/strtod.h> header file. */
#define HAVE_GOOGLE_PROTOBUF_IO_STRTOD_H 1

/* Define to 1 if you have the <google/protobuf/stubs/logging.h> header file.
   */
#define HAVE_GOOGLE_PROTOBUF_STUBS_LOGGING_H 1

/* Define to 1 if you have the <google/protobuf/stubs/stl_util.h> header file.
   */
#define HAVE_GOOGLE_PROTOBUF_STUBS_STL_UTIL_H 1
```
I've tried removing some of the dependencies and rerunning configure, but it now always works :-/. So I can't reproduce it now anymore, maybe one of the depend packages was in a wrong state. I guess this issue can be closed, sorry for the confusion.

**Comment by peternewman** [comment]
> Currently, when I start from a clean dir in an effort to reproduce the issue, everything immediately works.

Does the dirty directory still show the same error.

> I did take a look at the config.h beforehand, which only had these google protobuf defines:

So they're all undefined,so configure couldn't see any of the headers, but it could see the package. :confused: 

> So I can't reproduce it now anymore, maybe one of the depend packages was in a wrong state. I guess this issue can be closed, sorry for the confusion.

I don't mind leaving it open for a bit longer just in case you see the issue again. Or when will this version of testing be released by Debian?

**Comment by peternewman** [comment]
I'm going to assume we've chased this away for good now @aroffringa . Obviously please comment and we'll reopen it should the error reoccur!
