### ISSUE TITLE
g++ errors running unit tests

### ISSUE THREAD

**Issue by stefansiegfried** [OpenLightingProject/ola#1671]
I am seeing the g++ output below after attempting 'make check'.
OS: Fedora release 32
g++ --version: (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)

--- 
g++ -DHAVE_CONFIG_H -I.  -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden   -DTEST_SRC_DIR=\".\" -DTEST_BUILD_DIR=\".\" -Werror -Wno-error=deprecated-declarations  -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden  -Werror -Wno-error=deprecated-declarations -g -O2 -std=gnu++11 -pthread -MT libs/acn/E131Tester-HeaderSetTest.o -MD -MP -MF libs/acn/.deps/E131Tester-HeaderSetTest.Tpo -c -o libs/acn/E131Tester-HeaderSetTest.o `test -f 'libs/acn/HeaderSetTest.cpp' || echo './'`libs/acn/HeaderSetTest.cpp
libs/acn/HeaderSetTest.cpp: In member function ‘void HeaderSetTest::testTransportHeader()’:
libs/acn/HeaderSetTest.cpp:78:29: error: implicitly-declared ‘ola::acn::TransportHeader::TransportHeader(const ola::acn::TransportHeader&)’ is deprecated [-Werror=deprecated-copy]
   78 |   TransportHeader header2 = header;
      |                             ^~~~~~
In file included from ./libs/acn/HeaderSet.h:30,
                 from libs/acn/HeaderSetTest.cpp:28:
./libs/acn/TransportHeader.h:58:8: note: because ‘ola::acn::TransportHeader’ has user-provided ‘void ola::acn::TransportHeader::operator=(const ola::acn::TransportHeader&)’
   58 |   void operator=(const TransportHeader &other) {
      |        ^~~~~~~~
libs/acn/HeaderSetTest.cpp:81:33: error: implicitly-declared ‘ola::acn::TransportHeader::TransportHeader(const ola::acn::TransportHeader&)’ is deprecated [-Werror=deprecated-copy]
   81 |   TransportHeader header3(header);
      |                                 ^
In file included from ./libs/acn/HeaderSet.h:30,
                 from libs/acn/HeaderSetTest.cpp:28:
./libs/acn/TransportHeader.h:58:8: note: because ‘ola::acn::TransportHeader’ has user-provided ‘void ola::acn::TransportHeader::operator=(const ola::acn::TransportHeader&)’
   58 |   void operator=(const TransportHeader &other) {
      |        ^~~~~~~~
In file included from libs/acn/HeaderSetTest.cpp:28:
./libs/acn/HeaderSet.h: In copy constructor ‘ola::acn::HeaderSet::HeaderSet(const ola::acn::HeaderSet&)’:
./libs/acn/HeaderSet.h:35:7: error: implicitly-declared ‘ola::acn::TransportHeader::TransportHeader(const ola::acn::TransportHeader&)’ is deprecated [-Werror=deprecated-copy]
   35 | class HeaderSet {
      |       ^~~~~~~~~
In file included from ./libs/acn/HeaderSet.h:30,
                 from libs/acn/HeaderSetTest.cpp:28:
./libs/acn/TransportHeader.h:58:8: note: because ‘ola::acn::TransportHeader’ has user-provided ‘void ola::acn::TransportHeader::operator=(const ola::acn::TransportHeader&)’
   58 |   void operator=(const TransportHeader &other) {
      |        ^~~~~~~~
libs/acn/HeaderSetTest.cpp: In member function ‘void HeaderSetTest::testHeaderSet()’:
libs/acn/HeaderSetTest.cpp:245:24: note: synthesized method ‘ola::acn::HeaderSet::HeaderSet(const ola::acn::HeaderSet&)’ first required here
  245 |   HeaderSet headers2 = headers;
      |                        ^~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [Makefile:14346: libs/acn/E131Tester-HeaderSetTest.o] Error 1
make[3]: Leaving directory '/home/stefan/git/ola'
make[2]: *** [Makefile:18199: check-am] Error 2
make[2]: Leaving directory '/home/stefan/git/ola'
make[1]: *** [Makefile:17129: check-recursive] Error 1
make[1]: Leaving directory '/home/stefan/git/ola'
make: *** [Makefile:18203: check] Error 2

**Comment by peternewman** [comment]
Ah, so seeing the errors that's a duplicate of #1553 which has been fixed in #1583 but hasn't quite made it into master yet. For now if you pull those changes in should do the trick to get you going, and I'll sort out getting them merged into master too properly.

**Comment by stefansiegfried** [comment]
Thanks, that did the trick.  Will close this issue as duplicate.

**Comment by peternewman** [comment]
Sounds good and glad to hear it @stefansiegfried ! Also particularly good to know given https://github.com/OpenLightingProject/ola/pull/1583#issuecomment-693196292
