### ISSUE TITLE
DMX with RS232  USB

### ISSUE THREAD

**Issue by Summer88** [OpenLightingProject/ola#1709]
Hi, 
I've a couple of RS232 USB UARTs, one works fine, the other no:

- Bus 001 Device 006: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC 
With ola-ftdidmx.conf works fine.

- Bus 001 Device 007: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter
With ola-uartdmx.conf can change color but got side effects (constant flicker of all DMX devices)

How can I debug to get the second adapter to work as first?

**Comment by peternewman** [comment]
As per the uartdmx docs ( http://docs.openlighting.org/ola/conf/ola-uartdmx.conf.html ):

> Using USB-serial adapters is not supported (try the ftdidmx plugin instead).

@richardash1981 may be able to advise, but I'd imagine it's timing issues.

You could try changing these lines and compiling to see if your other interface works with libftdi:
https://github.com/OpenLightingProject/ola/blob/9a280438091d8b619f42a5e7e51c13a135420584/plugins/ftdidmx/FtdiWidget.cpp#L65-L67

If you've got access to an oscilloscope/logic analyser or similar it might be possible to look at the output from the HL-340 and make sense of what it's doing wrong with the UART plugin (and/or the FTDI if it works with those changes).

**Comment by Summer88** [comment]
Thank you, I've changed the parrameters:

vid (int) – Vendor ID (USB 16-bit identifier)
pid (int) – Product ID (USB 16-bit identifier)
pidname (str) – Product name (arbitrary string)

```
const uint16_t FtdiWidgetInfo::FTDI_VID = 0x1a86;
const uint16_t FtdiWidgetInfo::FT232_PID = 0x7523;
const uint16_t FtdiWidgetInfo::FT4232_PID = 0x6011;

```

Recompiled everyting but the device is not shown in the list:

```

 ola_dev_info 
Device 1: ArtNet []
  port 0, IN, priority 100, RDM supported
  port 1, IN, priority 100, RDM supported
  port 2, IN, priority 100, RDM supported
  port 3, IN, priority 100, RDM supported
  port 0, OUT, RDM supported
  port 1, OUT, RDM supported
  port 2, OUT, RDM supported
  port 3, OUT, RDM supported
Device 2: E1.31 (DMX over ACN) []
  port 0, IN, priority inherited
  port 1, IN, priority inherited
  port 2, IN, priority inherited
  port 3, IN, priority inherited
  port 4, IN, priority inherited
  port 0, OUT, priority inherited
  port 1, OUT, priority inherited
  port 2, OUT, priority inherited
  port 3, OUT, priority inherited
  port 4, OUT, priority inherited

```

**Comment by peternewman** [comment]
Can you share your olad -l 4 logs please:
https://www.openlighting.org/ola/get-help/ola-faq/#How_do_I_get_olad_-l_4_logs

Also can you confirm you're definitely running your new code, which in your case should be easy as the previously working FTDI device presumably now isn't detected?

**Comment by Summer88** [comment]
Sorry cannot test it any more, I've switched to an hardware converter from rasberry serial to rs-485 and works out of box with .ola/ola-uartdmx.conf
