### ISSUE TITLE
Webinterface: dimmer flickers; commandline: device goes off after a few seconds

### ISSUE THREAD

**Issue by JsBergbau** [OpenLightingProject/ola#1721]
Setup:
- Raspberry PI 4, ola version  OLA olad version: 0.10.7
- Interface FTDI `Bus 001 Device 003: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC` udev rule added according to  https://www.openlighting.org/ola/getting-started/device-specific-configuration/#Linux_FTDI
- ola-ftdidmx plugin enabled, serial usb and enttec open DMX is disabled
- DMX Device is Stairville DS-2 RF DMX 1 channel Dimmer, Link https://www.thomann.de/de/stairville_ds2_rf_dmx_1ch_dimmer.htm
- Changing this slider works, I can change the brightness of the device

![grafik](https://user-images.githubusercontent.com/37013344/116806430-379f5900-ab2d-11eb-9f4c-cf283b3513c2.png)

However every few seconds light is shortly off and goes to dimmed value then again.

Using `ola_streaming_client -u 1 -d 254` it sets the device on but after a few seconds it goes off again. Time varies a lot. Sometimes it stays on for about 12 seconds, sometimes it goes off in less then 2 seconds again.

What am I missing?

**Comment by JsBergbau** [comment]
Very strange. After removing power from all devices and trying again everything works as expected.

**Comment by peternewman** [comment]
Hi @JsBergbau ,

I suspect this was it merging data from two places, which is what normally happens in these cases (e.g. the web UI and Art-Net or something), or the streaming client and the web UI. You'll need to close the tab on the web view to stop it.
