### ISSUE TITLE
Stylelint task broken

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#1733]
See e,g, https://travis-ci.com/github/OpenLightingProject/ola/jobs/520694836

```
Running "stylelint:all" (stylelint) task

[D] Task source: /home/travis/build/OpenLightingProject/ola/javascript/new-src/node_modules/grunt-stylelint/tasks/grunt-stylelint.js

Verifying property stylelint.all exists in config...OK

Files: css/style.css, ../../olad/www/console_values.html, ../../olad/www/landing.html, ../../olad/www/mobile.html, ../../olad/www/ola.html, ../../tools/rdm/static/rdmtests.html, ../../tools/rdm/static/common.css, ../../tools/rdm/static/ui.multiselect.css -> all

Options: (none)

Warning: Unexpected token { Use --force to continue.
```

I've tried various things such as upgrading or downgrading the package versions without success. We've also switched from amd64 to arm64 on Travis, and from .org to .com. I've also tried turning on various debug, but haven't got anymore more useful out of it. :disappointed:

**Comment by peternewman** [comment]
Help @FloEdelmann if you've got any ideas...

**Comment by peternewman** [comment]
I think it may be down to this:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#using-a-specific-npm-version

As we're currently running with npm v8, whereas we used to be on v10, but I can't currently get it to correctly switch versions:
https://travis-ci.com/github/OpenLightingProject/ola/jobs/520705450

**Comment by FloEdelmann** [comment]
There is no `npm` v8 or v10, the latest version is [v7.19.1](https://www.npmjs.com/package/npm). There are Node.js versions v8 and v10 though, but the latest stable Node version is v14 already.

**Comment by peternewman** [comment]
Doh!

So here's an old working run:
https://travis-ci.org/github/OpenLightingProject/ola/jobs/773150006

Progress, of sorts, now I've turned on the optional stack traces for grunt :facepalm: 
```
Running "stylelint:all" (stylelint) task
[D] Task source: /home/travis/build/OpenLightingProject/ola/javascript/new-src/node_modules/grunt-stylelint/tasks/grunt-stylelint.js
Verifying property stylelint.all exists in config...OK
Files: css/style.css, ../../olad/www/console_values.html, ../../olad/www/landing.html, ../../olad/www/mobile.html, ../../olad/www/ola.html, ../../tools/rdm/static/rdmtests.html, ../../tools/rdm/static/common.css, ../../tools/rdm/static/ui.multiselect.css -> all
Options: (none)
Warning: Unexpected token { Use --force to continue.
/home/travis/build/OpenLightingProject/ola/javascript/new-src/node_modules/stylelint/lib/getPostcssResult.js:122
		} catch {
		        ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/OpenLightingProject/ola/javascript/new-src/node_modules/stylelint/lib/createStylelint.js:7:26)
Aborted due to warnings.
```

You gave me a prod in the correct direction though, our node.js was too old, but apparently that only warrants a warning (unless you set some other config) and it only works in newer npm than we were using! Anyway it's now all working since https://github.com/OpenLightingProject/ola/pull/1732/commits/34303f4f61f08fe66d3230245c924aa9f9929789
