### ISSUE TITLE
No input Eurolite USB-DMX512-Pro MK2 

### ISSUE THREAD

**Issue by Schaggo** [OpenLightingProject/ola#1748]
Hi. I'm pretty new to OLA and still trying to figure stuff out. 
While I managed to control lights via the web interface faders / CLI  I am still having trouble finding devices with the Eurolite MK2.
The Interface shows 0 input. 

Is that device-specific or did I miss something during setup?

Thanks for your time

**Comment by peternewman** [comment]
From a quick look online, this device is output only, and doesn't support input. Unlike the Enttec Mk2 (similar name, very different looking box).

Can you share a link to where input is mentioned for the device (in general, not OLA specific).

**Comment by Schaggo** [comment]
Thanks for your answer! 
I can't find any reference that mentions input for my device. The earlier model Eurolite USB-DMX512-Pro (mk1) does have input and is capable of RDM, though. I simply assumed the vendor wouldn't remove functionality with the next iteration ... I mean it would be more than odd.

**Comment by peternewman** [comment]
Are you really sure you're not talking about an Enttec, which looks pretty similar.

I can't find any mention of input and/or RDM for any of the Eurolite dongles listed:
https://www.steinigke.de/en/mpn51860120-eurolite-usb-dmx512-pro-interface.html
https://www.steinigke.de/en/mpn51860118-eurolite-usb-dmx512-interface-update-adaptor.html
https://www.steinigke.de/en/mpn51860121-eurolite-usb-dmx512-pro-interface-mk2.html


Compared to:
https://www.enttec.com/product/lighting-communication-protocols/dmx512/dmx-usb-interface/

**Comment by Schaggo** [comment]
Yes, I am sure. The Eurolite pro seems to switch between RX and TX at intervals.

This video [video](https://www.youtube.com/watch?v=nX_yhK6_JTg&t=331s&ab_channel=SebastianHahner-skate702) (in German) demonstates device discovery.

**Comment by peternewman** [comment]
Can I first point you to here:
https://www.openlighting.org/ola/get-help/ola-faq/#What_are_the_recommended_USB_Device_to_use_with_OLA

I may be wrong, but I'd be surprised if much stuff on XLR 3 is RDM capable (if that's what you want).

Thanks for the video link though, I found it slightly surreal watching some (poorly) auto-translated subtitles of a German video which has had ~23k views where someone just sets up and uses some software I've had quite a large part in working on! But I did love the universal glee when you type something in the terminal and something happens on the other side of the room!

At least you can do two universes now!

**Comment by Schaggo** [comment]
Thanks! 
I was checking the page just the other day. 
And thank you in general for contributing to this project! You're right, it's definitely something that brings joy to a lot of people.
Sorry, for the unnecessary post.

**Comment by peternewman** [comment]
> And thank you in general for contributing to this project! You're right, it's definitely something that brings joy to a lot of people. 

Your welcome. It always feels rather abstract how many people know about a relatively minor project like this aside from the Debian popularity contest and some similar MacPorts reporting. The industry in general feels fairly niche.

Let us know how you get on anyway and good luck second time around!
