### ISSUE TITLE
Configuring Eurolite USB-DMX512 Pro on Ubuntu 21.10 - What is a serial

### ISSUE THREAD

**Issue by bsinou** [OpenLightingProject/ola#1752]
Hi, 

I am totally new in ola / DMX / python and it seems that i might have chosen the toughest interface to plug in Linux...

But anyway:

- I have cloned the git repo and followed these instruction https://github.com/OpenLightingProject/ola/blob/master/README.debian
- Switched to v0.10.8 tag
- I went through the _dependency hell_ :) and could perform the various command to configure and make.
- The card is plugged and seems to be correctly seen

```sh
bsinou@vox:~/.ola$ lsusb -s 3:11
Bus 003 Device 011: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
 ``` 
- I have disable most of the plugins and enabled usbdmx:

```sh
bsinou@vox:~/.ola$ cat ola-usbdmx.conf 
enable_eurolite_mk2 = true
enabled = true
libusb_debug_level = 4
nodle-FT232R-mode = 2
```

And when I start the program I got stuck here:

```
bsinou@vox:/tmp/ola-0.10.8/olad$ ./olad -l 2
common/rdm/PidStoreLoader.cpp:230: Manufacturer id 8377(ARRI -- Arnold & Richter Cine Technik GmbH & Co. Betriebs KG) listed more than once in the PIDs file
olad/OlaServer.cpp:173: No PID definitions loaded
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.002703] [0002db5f] libusb: debug [libusb_hotplug_register_callback] new hotplug cb 0x55c67748f880 with handle 1
[ 0.002711] [0002db5f] libusb: debug [libusb_get_device_list]  
[ 0.002720] [0002db5f] libusb: debug [discovered_devs_append] need to increase capacity
[ 0.002732] [0002db5f] libusb: debug [libusb_get_device_descriptor]  
... same line 10 times more
[ 0.002769] [0002db5f] libusb: debug [libusb_get_device_descriptor]  
[ 0.002810] [0002db72] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.002817] [0002db72] libusb: debug [handle_events] event sources modified, reallocating event data
[ 0.002828] [0002db72] libusb: debug [usbi_wait_for_events] poll() 2 fds with timeout in 60000ms
```

And I am kind of stuck here.

My last idea is that I have this line wrong  in my conf:
`nodle-<serial>-mode = {0,1,2,3,4,5,6,7}`

And here comes my question, _What is the serial?_ 

Any hint would be greatly appreciated, thanks!

Bruno

PS: I quickly tried on Windows and the cable / interface / led beamer all work
PS2: First posting was a unwanted shortcut use, sorry

**Comment by peternewman** [comment]
> * I have disable most of the plugins and enabled usbdmx:
> ```shell
> bsinou@vox:~/.ola$ cat ola-usbdmx.conf 
> enable_eurolite_mk2 = true
> enabled = true
> libusb_debug_level = 4
> nodle-FT232R-mode = 2
> ```

You only need the following, the other setting isn't relevant to you:
```shell
enable_eurolite_mk2 = true
enabled = true
libusb_debug_level = 4
```


> And when I start the program I got stuck here:
> ```
> bsinou@vox:/tmp/ola-0.10.8/olad$ ./olad -l 2
> ```

Can you share -l 4 version of that log.

Can you also uninstall the version of OLA you probably installed via apt first:
`sudo apt-get purge olad libola-dev`

And share the output of:
`dpkg -l | grep -i ola`

**Comment by bsinou** [comment]
Hi, 

Thanks for the prompt reply (and also the nice work with ola!!).
I have adapted the `ola-usbdmx.conf` file and made the suggested checks but I am still stuck at the same point.

Here is a pastebin link for the starting verbose logs:  https://pastebin.com/raw/EhYegzvn

And the list of _ola-like_ packages:
```sh
bsinou@vox:~$ dpkg -l | grep -i ola
ii  libccolamd2:amd64                                           1:5.8.1+dfsg-2                      amd64        constrained column approximate library for sparse matrices
ii  libcolamd2:amd64                                            1:5.8.1+dfsg-2                      amd64        column approximate minimum degree ordering library for sparse matrices
ii  libtwolame0:amd64                                           0.4.0-2build1                       amd64        MPEG Audio Layer 2 encoding library
```

**Comment by peternewman** [comment]
Ah, so it's easier than I thought, just don't switch to v0.10.8 tag. The code for that device ( #1556 ) is only in our master branch.

You may also need to do this:
https://wiki.openlighting.org/index.php/OLA_Device_Specific_Configuration#Eurolite_USB_DMX512_PRO
https://www.openlighting.org/ola/getting-started/device-specific-configuration/#Eurolite_USB_DMX512_PRO

**Comment by bsinou** [comment]
You were right, I have simply switched to the head and done:

```sh
autoreconf -i
./configure
make all
```

I then could start the server and the `examples/ola_dev_info` command showed the newly added USB interface.

Many thanks for the hint.  
If I may asked, how did you spot it in the verbose log? 

It was not obvious to me when I tried to do it by myself last week-end...

**Comment by peternewman** [comment]
> You were right, I have simply switched to the head and done:
> I then could start the server and the `examples/ola_dev_info` command showed the newly added USB interface.

Great, glad to hear it.

> Many thanks for the hint. If I may asked, how did you spot it in the verbose log?
> 
> It was not obvious to me when I tried to do it by myself last week-end...

Just the fact that it had logged this:
```
libs/usb/HotplugAgent.cpp:172: USB hotplug event: 3:10 @0x5610ebb87db0 [add]
[ 0.083982] [00015911] libusb: debug [libusb_get_device_descriptor]  
plugins/usbdmx/AsyncPluginImpl.cpp:272: USB device added, checking for widget support, vendor 0x0403, product 0x6001
```

So it had found the device, but hadn't logged anything else (e.g. the fact mk2 wasn't enabled) or something else didn't match.
