### ISSUE TITLE
E1.31 aSCN working but no ArtNet

### ISSUE THREAD

**Issue by Gwedo** [OpenLightingProject/ola#1765]
When I use QLC+ I can use E1.31 aSCN, but when I use ArtNet it doesnt work. I also tested with resolume arena and it doesnt output any value?

**Comment by Gwedo** [comment]
I still can't seem to get ArtNet working while SaCN works fine? how do I fix this??

**Comment by peternewman** [comment]
What OS? What versions of QLC+ and OLA? Are QLC+ and OLA on the same machine? Can you share a screenshot of the QLC+ config and the OLA config.

Also olad -l 4 logs please.

What does Wireshark show if listening to the Art-Net port?

**Comment by Gwedo** [comment]
> What OS? What versions of QLC+ and OLA? Are QLC+ and OLA on the same machine? Can you share a screenshot of the QLC+ config and the OLA config.
> 
> Also olad -l 4 logs please.
> 
> What does Wireshark show if listening to the Art-Net port?

I fixed it by changing the setting to Unicast and insert the IP instead of it broadcasting

**Comment by Gwedo** [comment]
But when I do the same in Resolume for pixelmapping it doesnt work while it does using QLC+ for fixtures

**Comment by Gwedo** [comment]
For some odd reason it works now..... hmmm

**Comment by peternewman** [comment]
Glad to hear you've fixed it. You've still offered no diagnostics info so I can't really comment further.
