### ISSUE TITLE
CPPLint build fail

### ISSUE THREAD

**Issue by rodb70** [OpenLightingProject/ola#1820]
I'm getting this build failre with the latest master branch:

21:53:51 -------------------------------------------------------
21:53:51 OLA Version 0.10.8
21:53:51 
21:53:51 Prefix: '/usr/local'
21:53:51 Compiler: 'g++ -g -O2 -std=gnu++11 -pthread '
21:53:51 Linker: '/usr/bin/ld -m elf_x86_64   -ldl '
21:53:51 Python: /usr/bin/python
21:53:51 
21:53:51 Python API: yes
21:53:51 Java API: no
21:53:51 Enable HTTP Server: yes
21:53:51 RDM Responder Tests: yes
21:53:51 Ja Rule: no
21:53:51 Enabled Plugins: artnet dummy e131 espnet ftdidmx gpio karate kinet milinst nanoleaf opendmx openpixelcontrol osc pathport renard sandnet shownet spi spidmx stageprofi uartdmx usbdmx usbpro
21:53:51 UUCP Lock Directory: /var/lock
21:53:51 
21:53:51 Now type 'make [<target>]'
21:53:51   where the optional <target> is:
21:53:51     all          - build everything
21:53:51     check        - run the tests
21:53:51     doxygen-doc  - generate the HTML documentation
21:53:51     lint         - run the linters
21:53:51 -------------------------------------------------------
21:53:51 [Open_Lighting_Architecture_-_Linux] $ /bin/bash -xe /tmp/jenkins6349608851020370006.sh
21:53:51 + make all
21:53:51 Makefile:20124: *** cpplint not found. Install forked cpplint (e.g. via pip for the latest version) and re-run configure.. Stop.

Git hash is 95b8cbecd9bd18a2b4436cd799c0cc80c4795b95
build commands from fresh clone are:
autoreconf -i
./configure --enable-rdm-tests --disable-root-check --disable-dependency-tracking
make all

Looking at the generated makefile I should be able to build without cpplint, but this does not seem possible at the moment?

**Comment by peternewman** [comment]
Hi @rodb70 ,

Sorry for this. See some discussion in https://github.com/OpenLightingProject/ola/pull/1812#issuecomment-1439167801 . We're aware of it and looking at a fix when we get time shortly.

In the short term, I think installing cpplint (e.g. via pip or deb) or simply touching an executable file into your path called codespell should fix the issue...

**Comment by peternewman** [comment]
I think we've fixed this @rodb70 but I've only tested on GitHub Actions so far. Fancy giving this PR a go? #1821
