### ISSUE TITLE
ola_rdm_get issue: Manufacturer id [..] is listed more than once in the PIDs file

### ISSUE THREAD

**Issue by hyren5** [OpenLightingProject/ola#1837]
Hello!

I am getting familiar with running ola from the command line.

Build 0.10.9 (latest) 
Running on Ubuntu 22.04.2 (latest)

I enabled the dummy devices as well as Art-Net in my `test` universe

I am able to run the web interface, meaning OLA should be running well, but I am running into an error when I enter the following command `ola_rdm_get` into my terminal 

`common/rdm/PidStoreLoader.cpp:250: Manufacturer id 549(Northern Lights Electronic Design, LLC) listed more than once in the PIDs file`

this message pops up whenever I reference the ola_rdm_get and ola_rdm_set programs.

Although calling: `ola_rdm_discover -u 1` will output the correct result: 
`7a70:ffffff00`
`7a70:ffffff01`
`7a70:ffffff02`
`7a70:ffffff03`
`7a70:ffffff04`
`7a70:ffffff05`

Thank you for taking the time to look at the issue that I am facing. Have a great day and I very much appreciate your work on this project.

Brian

**Comment by peternewman** [comment]
Hi Brian,

Sorry about that, that's my error and it seems our tests didn't catch it unfortunately.

The quickest fix will be if you edit the file data/rdm/manufacturer_names.proto to remove the duplicate entry:
https://github.com/OpenLightingProject/ola/blob/38cbeaebbf098b73c2f9c5a314cdcd0c899e40ce/data/rdm/manufacturer_names.proto#L3577-L3584

That should fix it for you. I'll push a fully fixed file (and hopefully a test fix to catch this in future) very soon.

**Comment by peternewman** [comment]
I can confirm our C++ tests in data/rdm catch this, although the Python ones don't currently...
