### ISSUE TITLE
SetDmxStartupMode sends wrong PID in Responder Test

### ISSUE THREAD

**Issue by jensgol** [OpenLightingProject/ola#1843]
SetDmxStartupMode sends DMX_FAIL_MODE instead of DMX_STARTUP_MODE.

OLA RDM Responder Tests

GetSupportedParameters: PASSED
GET supported parameters.
 GET: uid: 4c53:530f002f, pid: SUPPORTED_PARAMETERS (0x0050), sub device: 0, args: []
 Response: RDMResponse(type=ACK, command_class=GET), PID: 0x0050, TN: 39, PDL: 122, data: {'params': [{'param_id': 21}, {'param_id': 32}, {'param_id': 48}, {'param_id': 49}, {'param_id': 50}, {'param_id': 81}, {'param_id': 112}, {'param_id': 128}, {'param_id': 129}, {'param_id': 130}, {'param_id': 144}, {'param_id': 160}, {'param_id': 176}, {'param_id': 193}, {'param_id': 194}, {'param_id': 224}, {'param_id': 225}, {'param_id': 288}, {'param_id': 289}, {'param_id': 290}, {'param_id': 321}, {'param_id': 512}, {'param_id': 513}, {'param_id': 514}, {'param_id': 1024}, {'param_id': 1025}, {'param_id': 1026}, {'param_id': 1027}, {'param_id': 1028}, {'param_id': 1029}, {'param_id': 1280}, {'param_id': 1281}, {'param_id': 1536}, {'param_id': 1537}, {'param_id': 1538}, {'param_id': 1539}, {'param_id': 1600}, {'param_id': 1601}, {'param_id': 1602}, {'param_id': 4097}, {'param_id': 4112}, {'param_id': 4128}, {'param_id': 4129}, {'param_id': 4144}, {'param_id': 4145}, {'param_id': 4160}, {'param_id': 4161}, {'param_id': 4162}, {'param_id': 4163}, {'param_id': 4164}, {'param_id': 61443}, {'param_id': 61444}, {'param_id': 61664}, {'param_id': 61665}, {'param_id': 61667}, {'param_id': 61668}, {'param_id': 61669}, {'param_id': 61670}, {'param_id': 61671}, {'param_id': 61672}, {'param_id': 61673}]}
Advisory: PARAMETER_DESCRIPTION listed in supported parameters

GetDmxStartupMode: PASSED
Get DMX_STARTUP_MODE.
 GET: uid: 4c53:530f002f, pid: DMX_STARTUP_MODE (0x0142), sub device: 0, args: []
 Response: RDMResponse(type=NACK, reason="Unknown PID"), PID: 0x0142, TN: 41

SetDmxStartupMode: FAILED
Set DMX_STARTUP_MODE without changing the settings.
 SET: uid: 4c53:530f002f, pid: DMX_FAIL_MODE (0x0141), sub device: 0, args: [0, 0, 0, 0]
 Response: RDMResponse(type=NACK, reason="Data out of range"), PID: 0x0141, TN: 43
 Failed: expected one of:
  CC: Set, PID 0x0141, NACK RDMNack(value=4, desc="Write protect")
  CC: Set, PID 0x0141, ACK, fields [], values {}
  CC: Set, PID 0x0141, NACK RDMNack(value=5, desc="Unsupported command class")

OLA Version: 0.10.9
Test Run: 2023-03-22 11:42:37 AM 
UID: 4c53:530f002f

**Comment by peternewman** [comment]
Good spot @jensgol . This has actually been broken since it went in as part of 5369e339be9cb19315f4f5400b0da5371d1c851a .

I guess you mostly found it as you support one PID but not the other.

**Comment by peternewman** [comment]
Let us know if this doesn't fix it for you @jensgol .
