### ISSUE TITLE
Remove package dependency on Avahi

### ISSUE THREAD

**Issue by phinnay** [OpenLightingProject/ola#1846]
When running the packages pushed to Debian via Docker, OLA constantly streams an error that it cannot create an Avahi client:

 olad/AvahiDiscoveryAgent.cpp:371: Failed to create Avahi client: Daemon not running

![image](https://user-images.githubusercontent.com/12052908/227580906-43cb3005-c998-4685-a7de-164abb936096.png)

I understand the instructions on the website specify the Avahi package in the ```apt install``` line however failing in this manner if that package is not found makes it tricky to containerize for modern use cases. 

I understand a custom build from source in my container could be a solution however that increases complexity VS using the package pushed up to distributions for the sake of a feature that's not essential for OLA to operate. 

It would be nice to either tie the Avahi dependency to whatever plugin it's used for, so, you can simply leave that out -or- fail gracefully if it is not found.

Thanks!

**Comment by DaAwesomeP** [comment]
Have you tried running `olad` with `--no-register-with-dns-sd`?

**Comment by phinnay** [comment]
Woah, thank you!! I hadn't seen that flag on the documentation located at https://www.openlighting.org/ola/.  Worked like a charm :)

**Comment by DaAwesomeP** [comment]
Happy to help! I didn't actually know it was there either but I had a feeling it was. I ran `olad --help`.

**Comment by peternewman** [comment]
> Woah, thank you!! I hadn't seen that flag on the documentation located at https://www.openlighting.org/ola/. Worked like a charm :)

Our man pages are also available on the website here:
http://docs.openlighting.org/ola/man/man1/olad.1.html

> I understand a custom build from source in my container could be a solution however that increases complexity VS using the package pushed up to distributions for the sake of a feature that's not essential for OLA to operate.
> 
> It would be nice to either tie the Avahi dependency to whatever plugin it's used for, so, you can simply leave that out -or- fail gracefully if it is not found.

FWIW from the error I think it found the Avahi/Bonjour dependencies but not the server to connect/register with.

Glad you've sorted it anyway!

**Comment by peternewman** [comment]
Oh and another thought, there's also a `--without-dns-sd` option for configure if you want it to ignore the presence of any libraries on your machine during compilation, but then you won't be able to toggle it at runtime...
