### ISSUE TITLE
How to connect ArtNet IP settings for OLA for Raspberry Pi.

### ISSUE THREAD

**Issue by hyren5** [OpenLightingProject/ola#1873]
Hello,

I am running OLA on the latest release of Raspbian and I am having trouble configuring the IP settings required to have the ArtNet plugin working for my raspberry pi.

I have Artnet enabled in the OLA config files (at /home/pi3/.ola/ola-artnet.conf)

And I am running into a config issue with configuring the static ipv4 address `2.0.0.1` and the netmask as `255.0.0.0`
when I enter the following lines into my /etc/dhcpcd.conf file 
`interface eth0
static ip_adress=2.0.0.1/24
static routers=2.0.0.1
static domain_name_servers=2.0.0.1 255.0.0.0
inform 2.0.0.1`

Please let me know if these settings are incorrect and/or how to configure the ArtNet IP settings to run OLA on my Raspberry Pi. Thanks!

**Comment by DaAwesomeP** [comment]
Hi @hyren5,

What is the output of the command `ip a` on the Pi? On the OLA web interface (typically `http://localhost:9090` from the Pi) what IP is shown? What are the contents of `/home/pi3/.ola/ola-artnet.conf` and `/etc/ola/ola-artnet.conf` (if it exists)?

**Comment by hyren5** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether e4:5f:01:2e:6d:18 brd ff:ff:ff:ff:ff:ff
    inet 2.0.0.1/8 brd 2.255.255.255 scope global deprecated noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::1dc8:180e:a60e:ca05/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000   
    link/ether e4:5f:01:2e:6d:19 brd ff:ff:ff:ff:ff:ff
    inet 10.21.116.229/21 brd 10.21.119.255 scope global dynamic noprefixroute wlan0
       valid_lft 85110sec preferred_lft 74310sec
    inet6 fe80::3f5b:1f84:2680:e381/64 scope link
       valid_lft forever preferred_lft forever

the ip adderss shown on the ola web interface is:
![5e17689eca21935302bf054ba4cfe234](https://github.com/OpenLightingProject/ola/assets/111248441/73e496bc-49c6-4f08-afd8-c14eff7556a2)

contents of `/home/pi3/.ola/ola-artnet.conf`:
![image](https://github.com/OpenLightingProject/ola/assets/111248441/816b66c2-1300-47c8-b1d6-29c08b0ca2e6)

contents of `/etc/ola/ola-artnet.conf`: (path does not exist)

Thank you for your quick response Perry

**Comment by DaAwesomeP** [comment]
> Thank you for your quick response Perry

Always happy to help!

OK, it seems the Pi correctly has the address `2.0.0.1` so that takes out a big possible variable.

May you share the manufacturer/model of the device you are trying to send ArtNet to? May you share the IP address, CIDR/subnet mask, ArtNet net, and ArtNet subnet configured on this other device? Have you created a universe in OLA from the web interface and patched an ArtNet output to it?

**Comment by hyren5** [comment]
The manufacturer of the device that I am trying to send ArtNet to is Chroma Q, I am able to connect to this device when using a Linux machine and configuring the settings there. I have double checked and I have created a universe in OLA from the web interface and patched an ArtNet output plugin to it.

For more information the Linux machine is also a Pi board running the same io and hardware settings.

**Comment by peternewman** [comment]
Hi @hyren5 ,

Glad to see you presumably resolved this issue, would you mind either leaving a note about what the fix was if it was an OLA issue, or just a pointer to others if it was an issue with the Chroma Q device (e.g. make sure you've turned off the foo option, or remember to double-check the subnet masks match or whatever).

Just to save the next poor soul from getting here and being equally stumped. Plus there's nothing worse than Googling for a problem, finding your OWN question and not having the answer you found last time!

**Comment by hyren5** [comment]
Absolutely. After some tinkering around, I found that it was not due to any errors on fixtures that I was using or because of the OLA codebase. 

The issue was actually that the following line `static ip_address=2.0.0.1`
in the file `/etc/dhcpcd.conf`

needed to be changed to `static ip_address=2.0.0.1/8` to include the netmask `255.0.0.0` in accordance with the ArtNet protocol. 

calculations:
![image](https://github.com/OpenLightingProject/ola/assets/111248441/e3bb8097-5110-4618-88c0-d9fe8ab20fdc)

This was a silly mistake nonetheless, but something important to note when you are using ArtNet. The GUI in Raspian does not have an option to fill in the netmask, where on the Linux Ubuntu OS I had used, the GUI had provided a space to fill in the netmask.

Thank you for your continued work on the OLA libraries.

**Comment by peternewman** [comment]
Ah I see, although it looks like you'd already fixed it by your second post:

> I enter the following lines into my /etc/dhcpcd.conf file `interface eth0 static ip_adress=2.0.0.1/24 static routers=2.0.0.1 static domain_name_servers=2.0.0.1 255.0.0.0 inform 2.0.0.1`

> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000 link/ether e4:5f:01:2e:6d:18 brd ff:ff:ff:ff:ff:ff inet 2.0.0.1/8 brd 2.255.255.255 scope global deprecated noprefixroute eth0 valid_lft forever preferred_lft forever inet6 fe80::1dc8:180e:a60e:ca05/64 scope link valid_lft forever preferred_lft forever
