### ISSUE TITLE
How to send LED RGB data (stored in a dat file ) over artnet

### ISSUE THREAD

**Issue by jagspaul** [OpenLightingProject/ola#1893]
I have LED RGB data stored in a dat file. I want to send this RGB data over a artnet network. How cat I do this on Raspberry Pi?  

How OLA can be used in this purpose?

Is there any sample code available?

How can I use libartnet In this purpose?

**Comment by peternewman** [comment]
Hi @jagspaul ,

Where did the dat file come from? Do you know the format of it internally? Is it just one universe of DMX/Art-Net data, or multiple? Is it a static state, or lots of frames/scenes?

Either OLA or libartnet could do this in a few different ways.

The most versatile one would probably be to just convert the .dat files to OLA Recorder ones. The file format is described here and you could just use those classes to write the files:
https://github.com/OpenLightingProject/ola/blob/96aa95e1ced41ab8093ffaff619ec3b875f2384e/examples/ShowSaver.cpp#L20-L23

Then you can use all the features of ola_recorder to play them back:
http://docs.openlighting.org/ola/man/man1/ola_recorder.1.html

Alternatively you could essentially write your own playback code and fire it into ola_streaming_client's STDIN:
http://docs.openlighting.org/ola/man/man1/ola_streaming_client.1.html

Or you could write the whole thing from scratch and use one of our client APIs:
http://docs.openlighting.org/ola/doc/latest/cpp_client_tutorial.html
http://docs.openlighting.org/ola/doc/latest/dmx_cpp_client_tutorial.html
https://www.openlighting.org/ola/apis/

Or likewise the last option but using libartnet directly (personally I wouldn't recommend this, as it restricts you to only Art-Net in future).

**Comment by jagspaul** [comment]
[Where did the dat file come from? Do you know the format of it internally? Is it just one universe of DMX/Art-Net data, or multiple? Is it a static state, or lots of frames/scenes?]

The dat file build by my own code. It is having large numbers of pixels in each frames, and the file consist of 60000 frames.

The frame can be divided in 60 Universes and each universe has 510 channels (170 RGB LEDs).

pls give me sample c code for this purpose.

Thanks

**Comment by jagspaul** [comment]
Thanks for you response and great explanation. I think now I understand how OLA works.

[So presumably it's pre-generating all the data in advance? In which case the easiest way would be to just generate an ola_recorder file instead then, no interfacing directly with OLA required, you'd just have a file you could playback as desired.]

Yes it is pre-generating all the data in advance. I understand you point, let me code to convert my DAT file as ola_recorder file format.

Before that I want to test my Artnet node with OLA, Pls help me in this regards.

Test setup of my node as follows.
a. I setup my node with 4 universe (universe no. 0,1,2 & 3) having each universe 510 channels (170 RGB leds)
b.  Universe numbering scheme :

    Universe No.     Net    Subnet    Universe 
         0                    0          0              0
         1                    0          0              1
         2                    0          0              2
         3                    0          0              3

I want to send artnet data from OLA to my artenet Node for testing.

Please tell me how to setup above 4 universes in OLA to send artnet data.

pls show me the config setup of ola-artnet.conf.

pls note I have not found anything on OLA to set universe channels to 510 instead 512.

Thanks 
jags

**Comment by peternewman** [comment]
> Before that I want to test my Artnet node with OLA, Pls help me in this regards.

Personally I'd have not written the node to use Art-Net because of all these issues. sACN/E1.31 is so much better for many reasons.

> I want to send artnet data from OLA to my artenet Node for testing.
> 
> Please tell me how to setup above 4 universes in OLA to send artnet data. Also tell me how to setup more than 16 universes (artnet output)?

I think its limited to 16 universes because of how we calculate the Art-Net port numbers.

See here for example:
https://groups.google.com/g/open-lighting/c/WF-SHn-Czx0/m/8Bm4DLu2AQAJ

> pls show me the config setup of ola-artnet.conf.

It's documented here (or in the plugin's readme section). You'll need to stop olad before you make the changes though:
https://docs.openlighting.org/ola/conf/ola-artnet.conf.html

> pls note I have not found anything on OLA to set universe channels to 510 instead 512.

OLA, and indeed DMX lets you send up to 512 channels per universe. Just send OLA the data you need to for that universe and it will transmit whatever the relevant standard/interface requires (which might be 510 or 512 depending on the output).

**Comment by jagspaul** [comment]
Hello,

OLA is a great software but still it has many limitations.

Like artnet has only 16 universes.

So I would like to request OLA team add my requirment to todo list to
remove the limitations of artnet from OLA.

Artnet config file should support multiple artnet declaration with
different IP address and subnet as follows.

Artnet config

[Artnet 1]
IP: x.x.x.x
Net: 0
Subnet:0
Start universe:0
No. Of universe:16

[Artnet 2]
IP: x.x.x.x
Net: 0
Subnet:1
Start universe:0
No. Of universe:16

[Artnet 3]
IP: x.x.x.y
Net: 0
Subnet:0
Start universe:0
No. Of universe:16


In this config
Total 48 universes declare.
32 (0-31) for node with IP x.x.x.x
16 (32-47) for node with IP x x.x.y

Hope OLA team will accept my request and will provide this feature in next
release very soon.

Thanks
Jags

**Comment by peternewman** [comment]
I'm going to close this issue @jagspaul as I think your remaining issue is covered by #1894 which I'll rename. I think you're now aware of the various options for getting data into OLA from your tool.

Let us know if you disagree though and we can reopen this issue.

**Comment by peternewman** [comment]
I'm going to close this issue @jagspaul as I think your remaining issue is covered by #1894 which I'll rename. I think you're now aware of the various options for getting data into OLA from your tool.

Let us know if you disagree though and we can reopen this issue.

**Comment by jagspaul** [comment]
So finally the outcome is OLA is not able to fulfill my requirment, thought OLA has capability, it can do anything people want. But some how many limitations keep maintained.

People uses many Arduino based open source artnet node with ola just like me. That node doesn't support node discovery. Ofcourse we don't need discovery. It is batter to set IP and universe manually atleast i prefer.

I don't understand if OLA support manual configuration then what is wrong with it?

OLA wants people has to follow how ola works but people wants more from OLA. People wants OLA must have flexibility and and be configured how people wants.

Still I keep hope that one day OLA will understand my pain.

However I must say come out from legacy not right choice everytime. You go with new technology but keep support of legacy.

Thanks and regards
Jags

**Comment by peternewman** [comment]
> People uses many Arduino based open source artnet node with ola just like me. That node doesn't support node discovery. Ofcourse we don't need discovery. It is batter to set IP and universe manually atleast i prefer.

Have you tried swapping out your Arduino Art-Net implementation for this sACN one:
https://reference.arduino.cc/reference/en/libraries/sacn/

**Comment by jagspaul** [comment]
I couldn't find stable Arduino Library of ESP32 sACN over Ethernet.

Rather I test Arduino ESP32 artnet over Ethernet and working with a
capacity of 5000 pixels @25fps.

Regards
Jags
