### ISSUE TITLE
Unused but active plugins can cause performance issues

### ISSUE THREAD

**Issue by mxa** [OpenLightingProject/ola#1899]
Unused, but active plugins (pecifically the SPI interface) can cause undesired load which makes light control choppy and unreliable.

**Comment by peternewman** [comment]
Hi @mxa ,

Can we have some more details please.

What OS and approximate hardware spec.

Do you mean the SPI output or DMX input driver?

Was it enabled? Was it patched? Were you sending DMX to the universe it was patched to at the time?

Also olad -l4 logs:
https://www.openlighting.org/ola/get-help/ola-faq/#How_do_I_get_olad_-l_4_logs

Aproximately how much load, what does top or similar say?

Does disabling the plugin resolve the issue?

Is it repeatable if you e.g. reboot?

**Comment by mxa** [comment]
Looks like this issue is caused by a busy SPI interface which the kernel was not aware of on the specific embedded system I'm using, not OLAs fault after all.

**Comment by peternewman** [comment]
Excellent @mxa . Thanks very much for getting back to us and I'm glad you've got to the bottom of it!
