### ISSUE TITLE
Python API : No module named 'ola'

### ISSUE THREAD

**Issue by PaoloRondot** [OpenLightingProject/ola#1909]
Hi there,

I'm trying to learn about DMX, and bought a BitWizard DMX shield for my RPi4. I am running Raspbian.
I installed ola first by cloning the repo, running `autoreconf -i`, `./configure --enable-python-libs` and finally `make` and `make install`.
I tried to use the Python API but I am getting `No module named 'ola'` error when running the DMXsend example. I understand that running `pip install ola` won't work, but I am missing the steps I should do to run the examples smoothly.

I also ran these commands, I guess it could help to find out my issue:

```
pi@raspberrypi:~/ola $ grep ^pythondir config.log
pythondir='${prefix}/lib/python3.9/site-packages'
pi@raspberrypi:~/ola $ python -c "import sys; print(sys.path)"
['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/pi/.local/lib/python3.9/site-packages', '/usr/local/lib/python3.9/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.9/dist-packages']
pi@raspberrypi:~/ola $ ls /usr/local/lib/python3.9/site-packages/
ola
```

I hope you can help me.
Cheers,
Dorton

**Comment by kengruven** [comment]
Your default Python path doesn't appear to include the path where you installed ola.  Does it work if you add that path manually?

**Comment by peternewman** [comment]
Yeah what @kengruven said. If you don't want to touch the OLA code, but just use it's libraries, installing the Debian packages is often a lot easier (depending on which exact version of Raspbian you're on).

`sudo apt-get install ola ola-python`
