### ISSUE TITLE
Protoc header files

### ISSUE THREAD

**Issue by JimmyBinoculars** [OpenLightingProject/ola#1921]
I realize this issue has been created before but I could not understand how to fix it.

Here is the console output:
```
checking for libprotobuf... yes
checking protobuf library version... 3.12.4
checking for protoc... /usr/bin/protoc
checking protoc version... 3.12.4
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: Cannot find the protoc header files
```

System details:
OS: Ubuntu 22.04.3 LTS
CPU: AMD Ryzen 5 4500U
GPU: Intergrated
RAM: 8 gb no idea what brand

Commands I used to install ola:
```
git clone https://github.com/OpenLightingProject/ola.git ola
cd ola
autoreconf -i
./configure
```

**Comment by peternewman** [comment]
Hi @JimmyBinoculars ,

What does:
`dpkg -l`
Say?

Can you upload your `config.log` please.

Does following the steps here help:
https://github.com/OpenLightingProject/website/blob/f68f1b08d5046f34a0cf0ffc14db51c5d5a3f925/download_and_install/compiling_from_source.md

Specifically installing all dependencies first:
```
sudo apt-get install \
    autoconf \
    automake \
    bison \
    flex \
    g++ \
    libavahi-client-dev \
    libcppunit-dev \
    libftdi-dev \
    liblo-dev \
    libmicrohttpd-dev \
    libncurses-dev \
    libprotobuf-dev \
    libprotoc-dev \
    libtool \
    libusb-1.0.0-dev \
    make \
    protobuf-compiler \
    pkg-config \
    uuid-dev \
    zlib1g-dev
```

Then re-running configure?

**Comment by JimmyBinoculars** [comment]
Thanks @peternewman installing all of the dependencies worked and I will close the issue with this comment.

**Comment by peternewman** [comment]
Excellent, I'm glad that sorted it. Thanks for a very clear fault report too.
