### ISSUE TITLE
USB to DMX interface

### ISSUE THREAD

**Issue by JimmyBinoculars** [OpenLightingProject/ola#1923]
Hello, can anyone recommend me a USB to DMX inteface (preferably under £100 or $100) that would work with ola.

Please note I live in the UK so I would like to buy from places like [amazon](amazon.co.uk), [gear4music](gear4music.com), [pmt](pmtonline.co.uk) or any other brand that will ship here for relatively cheap (under £30).

**Comment by JimmyBinoculars** [comment]
Oh, and I forgot to mention that it has to be DMX512

**Comment by peternewman** [comment]
We've an FAQ for that @JimmyBinoculars 
https://www.openlighting.org/ola/get-help/ola-faq/#What_are_the_recommended_USB_Device_to_use_with_OLA

If you want further opinion, then people would need to know whether you want DMX input, output or both and whether you need RDM support or not?

**Comment by JimmyBinoculars** [comment]
Oh yeah looks good, thanks.

**Comment by peternewman** [comment]
No worries. The list is quite old now, but I suspect most of those manufacturers will make equivalent devices now (although a chunk of stuff is going more IP than USB based). Do get in touch if you need further clarity around interfaces.
