### ISSUE TITLE
Example C++ script not returning anything

### ISSUE THREAD

**Issue by JimmyBinoculars** [OpenLightingProject/ola#1924]
Hello, I was reading the C++ client api docs and tried running the example program with a dummy universe but it does not return anything, not even an error.

### Code:
```cpp
#include <ola/DmxBuffer.h>
#include <ola/io/SelectServer.h>
#include <ola/Logging.h>
#include <ola/client/ClientWrapper.h>
#include <ola/Callback.h>
using std::cout;
using std::endl;
bool SendData(ola::client::OlaClientWrapper *wrapper) {
 static unsigned int universe = 1;
 static unsigned int i = 0;
 ola::DmxBuffer buffer;
 buffer.Blackout();
 buffer.SetChannel(0, i);
 wrapper->GetClient()->SendDMX(universe, buffer, ola::client::SendDMXArgs());
 if (++i == 100) {
 wrapper->GetSelectServer()->Terminate();
 }
 return true;
}
int main(int, char *[]) {
 ola::InitLogging(ola::OLA_LOG_WARN, ola::OLA_LOG_STDERR);
 ola::client::OlaClientWrapper wrapper;
 if (!wrapper.Setup()) {
 std::cerr << "Setup failed" << endl;
 exit(1);
 }
 // Create a timeout and register it with the SelectServer
 ola::io::SelectServer *ss = wrapper.GetSelectServer();
 ss->RegisterRepeatingTimeout(25, ola::NewCallback(&SendData, &wrapper));
 // Start the main loop
 ss->Run();
}
```

### **Here is a screenshot of both my code and the console:**
![Screenshot from 2023-11-05 15-21-28](https://github.com/OpenLightingProject/ola/assets/91781252/88920249-cdbd-4ad0-8037-a001d0bbe534)

### **Here is a screenshot of the admin panel:**
![image](https://github.com/OpenLightingProject/ola/assets/91781252/b9c016cc-961f-457e-aed5-13221e5e55eb)

### System info:
CPU: AMD Ryzen 5 4500U
GPU: Intergrated
RAM: 8 GB (IDK what brand)
OS: Ubuntu 22.04.3

**Comment by peternewman** [comment]
Did you try looking at the DMX Monitor tab on the admin panel for universe 1 @JimmyBinoculars ? Although you might need to do them in different windows to see both.

What were you expecting it to return? It should have run for 100 frames (at 25 milliseconds between frames), with the first DMX channel incrementing from 0 to 100 (of the 255 possible values).

If you'd like to see more output from it, if you change line 21's OLA_LOG_WARN to OLA_LOG_DEBUG it will become a lot more chatty! Or chuck some output to cout or cerr in the SendData function.

**Comment by JimmyBinoculars** [comment]
Oh, thanks
