### ISSUE TITLE
Lumenradio CRMX Nova TX USB detected as Enttec USB Pro Device

### ISSUE THREAD

**Issue by gobo-ws** [OpenLightingProject/ola#1970]
I have tested a Lumenradio CRMX Nova TX USB device with OLA using the "Serial USB" plugin.
It works fine but the device is listed as:
> Enttec USB Pro Device, Serial #: 00004230  

In OLA with both an input and output option, even though the device only supports DMX output.

The LumenRadio CRMX Nova TX USB is listed as supported at https://docs.openlighting.org/ola/conf/ola-usbserial.conf.html, 
but the device is not mentioned in the plugin information for "Serial USB" in OLA 0.10.9

Device information:

> ID_MODEL=CRMX_Nova_USB_TX
> ID_MODEL_ENC=CRMX\x20Nova\x20USB\x20TX
> ID_MODEL_ID=6015
> ID_VENDOR=LumenRadio_AB
> ID_VENDOR_ENC=LumenRadio\x20AB
> ID_VENDOR_ID=0403
> ID_USB_MODEL=CRMX_Nova_USB_TX
> ID_USB_MODEL_ENC=CRMX\x20Nova\x20USB\x20TX
> ID_USB_MODEL_ID=6015
> ID_USB_VENDOR=LumenRadio_AB
> ID_USB_VENDOR_ENC=LumenRadio\x20AB
> ID_USB_VENDOR_ID=0403

**Comment by gobo-ws** [comment]
I updated the Nova USB TX firmware from version 1.0.3.4 to 1.0.5.0, and now it shows 'LumenRadio' as a device in OLA

**Comment by gobo-ws** [comment]
I updated the Nova USB TX firmware from version 1.0.3.4 to 1.0.5.0, and now it shows 'LumenRadio' as a device in OLA

**Comment by peternewman** [comment]
Looks like that will be due to:

> v1.0.4.0 (2017-03-05)
> =====================
> * Added support for dongle identity in Enttec protocol for Nova USB TX

Out of interest did it work with the older firmware? Did the newer firmware only show DMX in?

In theory it could do DMX in I'd think if it does RDM.

FWIW there's also an even newer update to the USB TX:

> v1.0.6.0 (2018-02-27)
> =====================
> * Added support for alternate start codes (ACS) in USB TX

**Comment by gobo-ws** [comment]
1.0.5.0 was the last firmware version for Nova TX USB device (other CRMX chip-based devices continued to receive updates) 
Nova TX USB does not officially support RDM though.
The newer firmware did only show DMX out. Which is correct.
