### ISSUE TITLE
RFC: Add DMX Keypad from mobile site onto main webpage too

### ISSUE THREAD

**Issue by ola-importer** [OpenLightingProject/ola#226]
_From [peterjne...@gmail.com](https://code.google.com/u/113693767617232683655/) on March 03, 2013 15:13:45_

Is there any reason this hasn't been done/isn't currently present on the non-mobile site? If not, I don't mind doing the honours and refactoring as necessary, but I don't want to just dive in if it's a deliberate choice.

_Original issue: http://code.google.com/p/open-lighting/issues/detail?id=225_

**Comment by daveol** [comment]
The new UI includes one so this can be closed
