### ISSUE TITLE
Write a UDP socket that dispatches based on iface number.

### ISSUE THREAD

**Issue by ola-importer** [OpenLightingProject/ola#228]
_From [si...@nomis52.net](https://code.google.com/u/100927661077854655312/) on March 09, 2013 17:07:28_

From http://www.opendmx.net/index.php/OLA_ArtNet_Roadmap We need a way to identify which interface UDP datagrams arrive on, and send to the correct instance of an ArtNet node. 

recvmsg() is our friend here since it provides the interface number which the packet arrived on.

This would allow us to support multiple E1.31 / ArtNet nodes (one per logical interface).

_Original issue: http://code.google.com/p/open-lighting/issues/detail?id=227_

**Comment by xseignard** [comment]
Hello,

I use OLA for the first time, and this feature is my primary need. 
So I can send artnet on a given interface (wifi) and OLA takes care to send it to my other interface (ethernet). This way I can use OLA like a plain old artnet node.

My usage seems very classical and I'm confused by the "wontfix" status, maybe I'm missing something?

Regards

**Comment by peternewman** [comment]
Hi @xseignard ,

This should only be relevant in terms of directing input from different interfaces. OLA should be quite happy just sending and receiving regardless of the interface.

The only requirement for directing based on interfaces is if you had two ArtNet nodes on the same device on the same universe. If you just use different universes it should all be fine.
