### ISSUE TITLE
Collect parameter descriptions in the model collector script

### ISSUE THREAD

**Issue by ola-importer** [OpenLightingProject/ola#240]
_From [nomis52](https://code.google.com/u/nomis52/) on June 12, 2013 07:50:39_

We should update the collectors to fetch param descriptions of any manufacturer pids. That way we can at least get the simple ones in without waiting for manufacturers to update the site.

_Original issue: http://code.google.com/p/open-lighting/issues/detail?id=239_

**Comment by peternewman** [comment]
Parameter description collection was added in https://github.com/OpenLightingProject/ola/commit/5353a029ef3086d5df8b5c463bff7cf0cbf8dd66 .

The RDM site still needs updating to make use of the data.
