### ISSUE TITLE
High RPC Lateny (40ms) - TCP_NODELAY ?

### ISSUE THREAD

**Issue by ola-importer** [OpenLightingProject/ola#252]
_From [michudr...@gmail.com](https://code.google.com/u/105403477772297339336/) on September 06, 2013 16:39:55_

What steps will reproduce the problem? 1. use a RPCclient (I use JAVA)
2. make a client, use it
3. see slow RPC queries
(only the dummy device is enabled) What is the expected output? What do you see instead? My application communicate with the OLAD RPC server (google protobuf), here is a primitive communication schema:
 -Client send a command to Server
 -Server reply with size (4 bytes)
 -Server reply with answer

Sending the command to the server is fast (max 2ms), getting the size reply too (max 2ms) but getting the payload takes up to 40ms! Even if the payload is empty.

I tested the application on my OSX system, the whole communication needs less than 5ms. I also tested the application on a Ubuntu system where the same 40ms delay occurred. What version of the product are you using? On what operating system? 0.8.31 Please provide any additional information below. If you search for 40ms and socket, you get alot of similar reports. TCP_NODELAY is one possible solution, some Links: http://stackoverflow.com/a/2253620 http://marc.info/?l=festival-talk&m=108603560214325 http://smalltalk.gnu.org/project/issue/119 ,

_Original issue: http://code.google.com/p/open-lighting/issues/detail?id=251_

**Comment by peternewman** [comment]
Fixed in https://github.com/OpenLightingProject/ola/commit/c1a5793555caeed430aada6409d2645b158ebc53
