### ISSUE TITLE
cross compilation error  [libolaacn_la-CIDImpl.lo] Error 1

### ISSUE THREAD

**Issue by nephaste** [OpenLightingProject/ola#312]
Can someone help me with this error 

I am trying compile ola-8.33 for Thecus NAS  with the following

ossp_uuid_CFLAGS="-O2 -I/raid/data/module/ffmpeg/sys/include" \
ossp_uuid_LIBS="-L/raid/data/module/ffmpeg/sys/lib" \
PYTHON=/raid/data/module/ffmpeg/sys/bin/python \
CXX=${HOST}-g++                 \
LD=${HOST}-ld                   \
AS=${HOST}-as                   \
AR=${HOST}-ar                   \
CC=${HOST}-gcc \
CROSS_COMPILE=${HOST} \
PKG_CONFIG_PATH="/raid/data/module/ffmpeg/sys/lib/pkgconfig"  \
CXXFLAGS="-O2 -I/raid/data/module/ffmpeg/sys/include"     \
LDFLAGS="-L/raid/data/module/ffmpeg/sys/lib -Wl,-rpath,/raid/data/module/ffmpeg/sys/lib" \
CPPFLAGS="-O2 -I/raid/data/module/ffmpeg/sys/include"     \
CFLAGS="-O2 -I/raid/data/module/ffmpeg/sys/include" \
./configure --prefix=/raid/data/module/ffmpeg/sys \
--host=${HOST} \
--bindir=/raid/data/module/ffmpeg/sys/bin \
--sbindir=/raid/data/module/ffmpeg/sys/bin \
--libdir=/raid/data/module/ffmpeg/sys/lib \
--datadir=/raid/data/module/ffmpeg/sys/share \
--datarootdir=/raid/data/module/ffmpeg/sys/share \
--sysconfdir=/raid/data/module/ffmpeg/sys/etc \
--sharedstatedir=/raid/data/module/ffmpeg/sys/com \
--localstatedir=/raid/data/module/ffmpeg/sys/var \
--includedir=/raid/data/module/ffmpeg/sys/include \
--oldincludedir=/raid/data/module/ffmpeg/sys/include \
--infodir=/raid/data/module/ffmpeg/sys/share/info \
--libexecdir=/raid/data/module/ffmpeg/sys/libexec \
--localedir=/raid/data/module/ffmpeg/sys/share/locale \
--with-protoc=/raid/data/module/ffmpeg/sys/bin/protoc \
--with-cppunit-prefix=/raid/data/module/ffmpeg/sys

but on make got an error that dont know how resolve 

make[4]: Entering directory `/raid/SRC/ola-0.8.33/plugins/e131/e131'
/bin/bash ../../../libtool  --tag=CXX   --mode=compile x86_64-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../..   -O2 -I/raid/data/module/ffmpeg/sys/include -I../../../include -Wall -Wformat -W -pthread -isystem /raid/data/module/ffmpeg/sys/include -Werror -Wconversion -I/raid/data/module/ffmpeg/sys/include  -O2 -I/raid/data/module/ffmpeg/sys/include -MT libolaacn_la-CID.lo -MD -MP -MF .deps/libolaacn_la-CID.Tpo -c -o libolaacn_la-CID.lo`test -f 'CID.cpp' || echo './'`CID.cpp
libtool: compile:  x86_64-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../.. -O2 -I/raid/data/module/ffmpeg/sys/include -I../../../include -Wall -Wformat -W -pthread -isystem /raid/data/module/ffmpeg/sys/include -Werror -Wconversion -I/raid/data/module/ffmpeg/sys/include -O2 -I/raid/data/module/ffmpeg/sys/include -MT libolaacn_la-CID.lo -MD -MP -MF .deps/libolaacn_la-CID.Tpo -c CID.cpp  -fPIC -DPIC -o .libs/libolaacn_la-CID.o
libtool: compile:  x86_64-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../.. -O2 -I/raid/data/module/ffmpeg/sys/include -I../../../include -Wall -Wformat -W -pthread -isystem /raid/data/module/ffmpeg/sys/include -Werror -Wconversion -I/raid/data/module/ffmpeg/sys/include -O2 -I/raid/data/module/ffmpeg/sys/include -MT libolaacn_la-CID.lo -MD -MP -MF .deps/libolaacn_la-CID.Tpo -c CID.cpp -o libolaacn_la-CID.o >/dev/null 2>&1
mv -f .deps/libolaacn_la-CID.Tpo .deps/libolaacn_la-CID.Plo
/bin/bash ../../../libtool  --tag=CXX   --mode=compile x86_64-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../..   -O2 -I/raid/data/module/ffmpeg/sys/include -I../../../include -Wall -Wformat -W -pthread -isystem /raid/data/module/ffmpeg/sys/include -Werror -Wconversion -I/raid/data/module/ffmpeg/sys/include  -O2 -I/raid/data/module/ffmpeg/sys/include -MT libolaacn_la-CIDImpl.lo -MD -MP -MF .deps/libolaacn_la-CIDImpl.Tpo -c -o libolaacn_la-CIDImpl.lo`test -f 'CIDImpl.cpp' || echo './'`CIDImpl.cpp
libtool: compile:  x86_64-unknown-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../.. -O2 -I/raid/data/module/ffmpeg/sys/include -I../../../include -Wall -Wformat -W -pthread -isystem /raid/data/module/ffmpeg/sys/include -Werror -Wconversion -I/raid/data/module/ffmpeg/sys/include -O2 -I/raid/data/module/ffmpeg/sys/include -MT libolaacn_la-CIDImpl.lo -MD -MP -MF .deps/libolaacn_la-CIDImpl.Tpo -c CIDImpl.cpp  -fPIC -DPIC -o .libs/libolaacn_la-CIDImpl.o
CIDImpl.cpp: In copy constructor 'ola::acn::CIDImpl::CIDImpl(const ola::acn::CIDImpl&)':
CIDImpl.cpp:43:37: error: 'uuid_clone' was not declared in this scope
CIDImpl.cpp: In destructor 'ola::acn::CIDImpl::~CIDImpl()':
CIDImpl.cpp:48:24: error: 'uuid_destroy' was not declared in this scope
CIDImpl.cpp: In member function 'bool ola::acn::CIDImpl::IsNil() const':
CIDImpl.cpp:57:29: error: 'uuid_isnil' was not declared in this scope
CIDImpl.cpp: In member function 'void ola::acn::CIDImpl::Pack(uint8_t*) const':
CIDImpl.cpp:71:25: error: 'UUID_FMT_BIN' was not declared in this scope
CIDImpl.cpp:71:57: error: 'uuid_export' was not declared in this scope
CIDImpl.cpp: In member function 'ola::acn::CIDImpl& ola::acn::CIDImpl::operator=(const ola::acn::CIDImpl&)':
CIDImpl.cpp:82:26: error: 'uuid_destroy' was not declared in this scope
CIDImpl.cpp:85:39: error: 'uuid_clone' was not declared in this scope
CIDImpl.cpp: In member function 'bool ola::acn::CIDImpl::operator==(const ola::acn::CIDImpl&) const':
CIDImpl.cpp:95:42: error: cannot convert 'unsigned char (* const)[16]' to 'const unsigned char*' for argument '1' to 'int uuid_compare(const unsigned char*, const unsigned char*)'
CIDImpl.cpp: In member function 'std::string ola::acn::CIDImpl::ToString() const':
CIDImpl.cpp:106:12: error: 'UUID_LEN_STR' was not declared in this scope
CIDImpl.cpp:107:34: error: 'cid' was not declared in this scope
CIDImpl.cpp:109:23: error: 'UUID_FMT_STR' was not declared in this scope
CIDImpl.cpp:109:50: error: 'uuid_export' was not declared in this scope
CIDImpl.cpp: In member function 'void ola::acn::CIDImpl::Write(ola::io::OutputBufferInterface*) const':
CIDImpl.cpp:119:25: error: 'UUID_FMT_BIN' was not declared in this scope
CIDImpl.cpp:119:57: error: 'uuid_export' was not declared in this scope
CIDImpl.cpp: In static member function 'static ola::acn::CIDImpl* ola::acn::CIDImpl::Generate()':
CIDImpl.cpp:129:20: error: 'uuid_create' was not declared in this scope
CIDImpl.cpp:130:19: error: 'UUID_MAKE_V4' was not declared in this scope
CIDImpl.cpp:130:31: error: 'uuid_make' was not declared in this scope
CIDImpl.cpp: In static member function 'static ola::acn::CIDImpl* ola::acn::CIDImpl::FromData(const uint8_t*)':
CIDImpl.cpp:137:20: error: 'uuid_create' was not declared in this scope
CIDImpl.cpp:138:21: error: 'UUID_FMT_BIN' was not declared in this scope
CIDImpl.cpp:138:55: error: 'uuid_import' was not declared in this scope
CIDImpl.cpp: In static member function 'static ola::acn::CIDImpl* ola::acn::CIDImpl::FromString(const string&)':
CIDImpl.cpp:145:20: error: 'uuid_create' was not declared in this scope
CIDImpl.cpp:146:21: error: 'UUID_FMT_STR' was not declared in this scope
CIDImpl.cpp:146:59: error: 'uuid_import' was not declared in this scope
CIDImpl.cpp: In member function 'std::string ola::acn::CIDImpl::ToString() const':
CIDImpl.cpp:111:1: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
make[4]: *** [libolaacn_la-CIDImpl.lo] Error 1
make[4]: Leaving directory`/raid/SRC/ola-0.8.33/plugins/e131/e131'
make[3]: **\* [all-recursive] Error 1
make[3]: Leaving directory `/raid/SRC/ola-0.8.33/plugins/e131'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/raid/SRC/ola-0.8.33/plugins'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/raid/SRC/ola-0.8.33'
make: **\* [all] Error 2

--disable-e131 has no effect 

thanks for your help...

**Comment by peternewman** [comment]
Hi @nephaste , is this still an issue for you with the latest build?

**Comment by peternewman** [comment]
Did you fix the issue then @nephaste ? What was the fix, or did our later build resolve it?
