### ISSUE TITLE
OLA configure fails on osx 10.9.2

### ISSUE THREAD

**Issue by klankschap** [OpenLightingProject/ola#376]
The latest version fails to compile on OSX 10.9.2
The ./configure complains about a missing file

...
checking for python module: google.protobuf... yes
checking for libprotobuf... yes
checking for protoc... /opt/local/bin/protoc
checking protoc version... 2.5.0
checking google/protobuf/compiler/command_line_interface.h usability... no
checking google/protobuf/compiler/command_line_interface.h presence... no
checking for google/protobuf/compiler/command_line_interface.h... no
configure: error: Cannot find the protoc header files

**Comment by rewolff** [comment]
Google finds this when I search for 'Cannot find the protoc header files'
On Ubuntu the answer is to install the package called libprotoc-dev .
