### ISSUE TITLE
Support the FadeCandy USB interface

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#503]
https://github.com/scanlime/fadecandy/blob/master/doc/fc_protocol_usb.md

No real need, just it looked interesting.

**Comment by peternewman** [comment]
Closing this now the core support is in, feature request for improvements opened as #604 .

**Comment by peternewman** [comment]
Two devices confirmed working https://groups.google.com/d/msg/open-lighting/zMHZtAqFXzQ/LTPACwA8AgAJ .

**Comment by johnmastri** [comment]
Did this ever get the full 512 led implementation?  Thanks

**Comment by peternewman** [comment]
Hi @johnmastri ,

Not yet unfortunately. That task, and the other related ones are being tracked in https://github.com/OpenLightingProject/ola/issues/604 . As always PRs welcome... :smile:
