### ISSUE TITLE
Export a list of plugins, the enabled & active state via the HTTP API

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#617]
Dave would like this for the new web API.

**Comment by nomis52** [comment]
We should also add a handler to enable / disable a plugin.

**Comment by peternewman** [comment]
Still need to add a handler to enable/disable a plugin.

**Comment by peternewman** [comment]
Over to @daveol to implement what I've offered in the web UI.

**Comment by peternewman** [comment]
@daveol used the new features in #677. I've raised a new issue, #682 to cover the enabling/disabling handler.
