### ISSUE TITLE
Unable to update to 0.9.4 with raspberry pi

### ISSUE THREAD

**Issue by MathieuMH** [OpenLightingProject/ola#619]
Hi Guys,

I'm using a raspberry PI B+ to run OLA. My current version is 0.9.3 and I'm not able to upgrade to 0.9.4?
I used the most simple way:
sudo apt-get update
sudo apt-get upgrade

When it executes I see a few Ign open lighting.org messages, but no explicit error messages. I'm I doing something wrong? Or forgetting something?

(Is this the right directory to post such issue's, this issue is more user related I suppose)

**Comment by peternewman** [comment]
Hi @MathieuMH what you're doing is fine, it's just no-one has got round to building debs for 0.9.4 on the Pi yet. We'll post in https://groups.google.com/forum/#!topic/open-lighting/pizt3hqDuBc when they're done, and I'll try and remember to post here/close this too.

**Comment by nomis52** [comment]
You can always check the current package versions at http://apt.openlighting.org/Package_Summary.txt 

I've built the 0.9.4 .debs for Ras Pi and they are on the site now.

**Comment by MathieuMH** [comment]
Thank you! Now I got it.
However I'm not able to add my fade candy device to the output list. :-( Have no clue why, but it is just nog listed. (nowhere actually)
When is the wiki pagina going to be update?

**Comment by peternewman** [comment]
The Fadecandy issue was down to https://github.com/peternewman/ola/commit/4cabbfd6b17facc69ff0eda7f340b198d7580869 and is now fixed.
