### ISSUE TITLE
ola fail to build on big-endian

### ISSUE THREAD

**Issue by juricast** [OpenLightingProject/ola#631]
Hello,

package ola_0.9.1-1.1 fail to build on big-endian archs on Debian.
https://buildd.debian.org/status/package.php?p=ola&suite=sid

I have tried peternewman fix
https://github.com/OpenLightingProject/ola/pull/467
package does build further and then fail again.

Additionally I did try to build upstream version of package and following tests fail on big-endian (mips):
FAIL: common/messaging/DescriptorTester
FAIL: common/network/NetworkTester
FAIL: common/rdm/RDMMessageTester
FAIL: plugins/shownet/ShowNetTester

Any ideas?

I will provide logs from tests that fail during build.

Regards,
Jurica

**Comment by nomis52** [comment]
I see test failures for testMACAddress & testIPV4SocketAddress but that should have been fixed with #467 .

Have you tried 0.9.4 ? 

Any logs you can provide will be helpful.

Simon

**Comment by juricast** [comment]
#467 do resolve those 2 failures (testMACAddress & testIPV4SocketAddress), but there a 4 additional failures.

I will try with 0.9.4, and will post results here.
The version that I have tested is 0.9.3.

**Comment by juricast** [comment]
Hi,
0.9.4 was built successfully on my mips board.
I need to check this one more time so I could confirm that this issue is fixed in 0.9.4.
Thanks!

**Comment by peternewman** [comment]
That's sounding promising @juricast , thanks for getting back to us.

**Comment by juricast** [comment]
Hello, 
I have retried 0.9.3, 0.9.4.
Everything build fine for both versions on mips big-endian.

I will back port changes for Debian package ola_0.9.1-1.1

**Comment by peternewman** [comment]
Great thanks @juricast . I know @yoe had been doing some work on packaging in the past too. Out of interest is there any reason you don't want to update to a later upstream version, or is it just because it's a lot more work than backporting a fix?

So essentially this is closed apart from you doing stuff external to OLA now?

**Comment by nomis52** [comment]
0.9.4 is a much better codebase to pick up. For starters all the issues found by coverity have been fixed.

**Comment by juricast** [comment]
@peternewman 
I would like to have fix for Debian jessie release.
Curently debian is in freeze.
We could ask for new version to be uploaded to experimental, but not for jessie (sid).

Yes this is closed.
Thanks!

**Comment by peternewman** [comment]
Ah okay, so you can get the patch into Jessie? That sounds good, and if we can have a new version for experimental, probably worth waiting for https://github.com/OpenLightingProject/ola/milestones/0.9.5, that would be great.

**Comment by yoe** [comment]
On Sat, Feb 21, 2015 at 12:19:00PM -0800, Peter Newman wrote:
>    Ah okay, so you can get the patch into Jessie?

Into Jessie is unlikely, sorry. I wanted to do so, but something
happened late last year in my personal life, which meant I had to
postpone all my volunteer stuff. It's too late now for such changes.

I might look at using "backports", a separate repository meant for
uploading newer versions ready to be used with Debian's stable or
oldstable branches. It's not perfect, but it is the next best thing to
actually having a good version in Debian itself.

>    That sounds good, and if we can have a new version for
>    experimental, probably worth waiting for
>    [1]https://github.com/OpenLightingProject/ola/milestones/0.9.5,
>    that would be great.

I'll probably upload that into unstable then :-)

-- 
It is easy to love a country that is famous for chocolate and beer

  -- Barack Obama, speaking in Brussels, Belgium, 2014-03-26

**Comment by peternewman** [comment]
I thought you can get later fixes in, or is that only for security issues @yoe , I know we see some updates on Ubuntu, but normally not full version updates. No worries if not.

Backports is fine too. Ultimately we've got our own debs, but its nice to have the range of hardware support the Debian debs offer, and being directly in Debian is nice.

**Comment by yoe** [comment]
On Sun, Feb 22, 2015 at 07:48:57AM -0800, Peter Newman wrote:
>    I thought you can get later fixes in, or is that only for security
>    issues [1]@yoe ,

For security issues and bugs which qualify as "release-critical", which
this doesn't (it would if it would be a regression, but since this is a
new package as far as Debian is concerned, it can't be. Long story...).

> I know we see some updates on Ubuntu, but normally not full version
> updates. No worries if not.

Exactly.

>    Backports is fine too. Ultimately we've got our own debs, but its nice
>    to have the range of hardware support the Debian debs offer, and being
>    directly in Debian is nice.

Yup. I failed you a bit here, and for that I'm sorry. It can't be
helped.

-- 
It is easy to love a country that is famous for chocolate and beer

  -- Barack Obama, speaking in Brussels, Belgium, 2014-03-26

**Comment by peternewman** [comment]
Ah okay, thanks for the clarification @yoe . I guess big-endian is proably a bit niche anyway.

Don't worry about it at all, none of us is getting paid and we all have other work and life to deal with.
