### ISSUE TITLE
Universe names are not remembered across olad restarts

### ISSUE THREAD

**Issue by simark** [OpenLightingProject/ola#661]
If you give a universe a name in the web UI, it will stay as long as you don't shut down olad. If you restart olad (either with ctrl-c or the shutdown button in the web UI), the universes are preserved but not their names.

**Comment by peternewman** [comment]
Good spot @simark I think we must not be calling safe prefs when we change it.

**Comment by nomis52** [comment]
It looks like  UniverseStore::SaveUniverseSetting() is missing the call to m_preferences->Save().

**Comment by peternewman** [comment]
I don't think this has ever worked looking at the code, but I suspect we haven't noticed in the past as people often do other stuff after naming a universe before closing.

**Comment by simark** [comment]
Thanks!

**Comment by peternewman** [comment]
Thanks for spotting it simark!
