### ISSUE TITLE
Switch to markdown in all the Plugin info strings

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#678]
Right now the plugin info text is free form.

If we switched to markdown, then we could use a Javascript markdown renderer to make the description in web UI look prettier.

Maybe we can use https://code.google.com/p/pagedown/ ?

**Comment by daveol** [comment]
I agree because it's kindof a mess right now. how about: https://github.com/Hypercubed/angular-marked ?

**Comment by nomis52** [comment]
That looks good.

**Comment by peternewman** [comment]
Sounds good, as long as it doesn't make it look odd in the CLI and other stuff. I think we'll need to use Github Flavoured Markdown though, for the underscores in variable names among other things:
https://help.github.com/articles/github-flavored-markdown/

The autolinking URLs would be good too.

Thankfully, it looks like it does:
https://github.com/Hypercubed/angular-marked#set-default-options-optional

**Comment by peternewman** [comment]
Question, if we're doing this, can/do we also seperate the plugin readme into another file, merged in/generated at configure time, so GitHub can also show the plugin info as markdown?

**Comment by daveol** [comment]
I'm all for it @peternewman, but isn't it a better idea to just let the plugin read the file?

**Comment by nomis52** [comment]
Yeah, I'm fine with that. We can have a .sh script that takes a .md file and produces a .h with a single static const char[] variable.
