### ISSUE TITLE
Java API doesn't build properly

### ISSUE THREAD

**Issue by simark** [OpenLightingProject/ola#693]
When using `--enable-java-libs`, I get this.
http://pastebin.com/ERnsEDHt

I noticed in the pom.xml that we are depending on protobuf 2.4.1, which is rather old. I tried for fun switching it to 2.6.1 and it makes the build work for me. I don't know what are the other impacts of that change though.

**Comment by nomis52** [comment]
I'm fine if you want to send a patch bumping it to 2.6.1
