### ISSUE TITLE
The macport ports file doesn't provide an option for installing the RDM tests

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#719]
This was required by someone at the Gatwick plugfest

**Comment by nomis52** [comment]
Portfile.diff has been posted: https://trac.macports.org/attachment/ticket/47557/

**Comment by nomis52** [comment]
Portfile was merged.

**Comment by peternewman** [comment]
@nomis52 you got the description wrong, it also says "Enable the Python 2.7 API" rather than "Enable the RDM Tests".

If we can't do OneOf, what about having an rdm_tests26 which requires python26 and conflicts rdm_tests/python27?

**Comment by nomis52** [comment]
Meh, I'll fix it in the next release. I don't think anyone still uses Python 2.6 anyway.

**Comment by peternewman** [comment]
I'm going to be awkward and re-open this again, so we can at least get the incorrect option title fixed, and as a note to ensure we do it during the next release,

**Comment by nomis52** [comment]
Fixed in the latest release.
