### ISSUE TITLE
Need of dummy proxy device (to simulate wireless solutions)

### ISSUE THREAD

**Issue by RenZ0** [OpenLightingProject/ola#729]
I understand that wireless solutions are kind of proxy devices, and due to physical limitations, replies to rdm requests are ACK_TIMER, and we can grab the response asking for QUEUED_MESSAGE.
We may need a dummy proxy device to help in software development, dealing with wireless solutions.

**Comment by peternewman** [comment]
I believe @nightrune had already done some work on this and was mostly there, just needing the UI side sorted. Is that right, or am I getting mixed up with splitters?

We also need the web UI to be able to cope with ACK_TIMER responses.

**Comment by nightrune** [comment]
I want to say I had the core of it done, but it needed plumbing through the
api, and working out how to dynamically add dummy responders to the tree
essentially.

On Wed, May 13, 2015 at 7:09 PM, Peter Newman <notifications@github.com>
wrote:

> I believe @nightrune <https://github.com/nightrune> had already done some
> work on this and was mostly there, just needing the UI side sorted. Is that
> right, or am I getting mixed up with splitters?
>
> We also need the web UI to be able to cope with ACK_TIMER responses.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLightingProject/ola/issues/729#issuecomment-101844638>
> .
>



-- 
Sean Sill
Electronic Systems Consultant/Contractor
Electrical and Computer Engineering Alumni from
Missouri University of Science and Technology(Missouri S&T)

**Comment by nomis52** [comment]
There already is an AckTimer Responder, in  ola-dummy.conf set ack_timer_count = 1 to enable it.

**Comment by peternewman** [comment]
Oops, I completely forgot about that @nomis52 . Splitters (or I guess proxies with multiple endpoints, where the other thing I was thinking of that @nightrune had been working on.

**Comment by nomis52** [comment]
Can we close this on then? Since it's all virtual, I don't think splitters are as interesting as responders that return ACK_TIMER (which we have).

**Comment by RenZ0** [comment]
Yes we can close, since there is already the responder I asked for ! Thanks.
