### ISSUE TITLE
OlaClient example

### ISSUE THREAD

**Issue by sl1200mk2** [OpenLightingProject/ola#731]
Hi,
for those who play with API, it would be great to have an exemple of how to use OlaClient.
if you ack this request, please don't put everything in main()...
also, please use ola::thread::Thread as it's a very good feature...
hope you'll echo this request...

++
Nicolas

**Comment by nomis52** [comment]
Is this not sufficient:

https://docs.openlighting.org/ola/doc/latest/client_tutorial.html#sec_CallbackClient

**Comment by sl1200mk2** [comment]
well these example does not contain closing channel, terminate server, cleanup (if necessary), neither a threaded example of how about to use an OlaClient.
the exemple StreamingClientTest is way better regarding these points.

best regards

**Comment by nomis52** [comment]
I think the new docs cover all the cases you asked for.

**Comment by sl1200mk2** [comment]
thank you very much!!
++
