### ISSUE TITLE
Display the conf file location in the new web UI

### ISSUE THREAD

**Issue by nomis52** [OpenLightingProject/ola#743]
It'll be useful for people to see where the config files are coming from.

**Comment by nomis52** [comment]
We should probably display this in the UI as well. @daveol  FYI.

**Comment by peternewman** [comment]
I thought the web UI already shows the config file within the plugin info?

**Comment by nomis52** [comment]
Indeed, it would be good to show it on /debug as well though.

**Comment by peternewman** [comment]
Actually, having checked, the old UI shows it. @daveol should update his UI so it shows it too on the plugin page.

**Comment by nomis52** [comment]
Fixed title, assigning to Dave

**Comment by peternewman** [comment]
@nomis52 I don't think you have fixed the title.

**Comment by peternewman** [comment]
We should also show the conf dir from ola_plugin_info.

**Comment by daveol** [comment]
where do you want me to put it? on the "home" page?

**Comment by nomis52** [comment]
Yeah that sounds fine.
