### ISSUE TITLE
adding device

### ISSUE THREAD

**Issue by skatun** [OpenLightingProject/ola#745]
I have the same problem as in https://groups.google.com/d/msg/open-lighting/Up2T5Da-iGg/IEEtpam4x8sJ My device is  http://www.kwmatik.cba.pl the kw-d-01 The Log is:

olad/PluginManager.cpp:108: Trying to start FTDI USB DMX
plugins/ftdidmx/FtdiWidget-libftdi.cpp:291: Found FTDI device. Vendor: 'KWMATIK'                                                                                        , Name: 'kw-D-01', Serial: 'RTS1910'
plugins/ftdidmx/FtdiWidget-libftdi.cpp:299: Unknown FTDI device with vendor stri                                                                                        ng: 'KWMATIK'

Could you please add my device to plugins/ftdidmx/FtdiWidget-libftdi.cpp?

**Comment by peternewman** [comment]
@skatun what version are you running, KWMATIK is already supported:
https://github.com/OpenLightingProject/ola/blob/master/plugins/ftdidmx/FtdiWidget.cpp#L180

**Comment by kripton** [comment]
According to the mailing list, this issue is solved. Can it be closed here?

**Comment by nomis52** [comment]
That device has been supported since 0.9.4 (29/1/2015)
