### ISSUE TITLE
Disable kqueue / epoll as the default for 0.9.6

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#761]
(17:46:55) nomis52: when used with the webserver
(17:47:14) nomis52: there is a race condition that can lead to the wrong fds being used

**Comment by nomis52** [comment]
To capture the bug:

Right now we call MHD_get_fdset each loop cycle and then call Add/Remove Descriptors on the SelectServer to make sure we're listening on the correct set of descriptors.

The problem occurs when MHD closes a fd. On the next call to MHD_get_fdset we notice the fd is not longer in the listen list, so we call RemoveReadDescriptor, that in turn calls kqueue with EV_DELETE but it's too late - the fd number is already invalid.

We either try to remove a fd that's not in use, and get the warning or remove the wrong fd.

**Comment by peternewman** [comment]
How come this isn't an issue with Select itself then?

Also, and I'm guessing this would just cause a memory leak, could we avoid doing any deletes just for the HTTPServer thread?

**Comment by nomis52** [comment]
select() is stateless - we rebuild the fdset each time before the call to select, so if a fd was closed we just don't add it to the set.

This isn't a memory leak problem, it's more of a 'file descriptor resource mismanagement' issue.

**Comment by nomis52** [comment]
Fixed (or at least worked around)
