### ISSUE TITLE
Tests fail when no non-loopback interfaces are present

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#763]
See the Debian bug here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769670

It probably makes sense to fix this locally, in which case we can remove testGetLoopbackInterfaces, we just need to work out what we do on Windows given: https://github.com/OpenLightingProject/ola/blob/master/common/network/InterfacePickerTest.cpp#L99

Do we skip the test on Windows, or let it run, possibly with a log line on Windows, for the tiny userbase who will run Windows with no network interface. Or ideally fix it up so the loopback interface is reported on Windows too.

**Comment by peternewman** [comment]
Thoughts/preferences @nomis52 . @yoe we'll get this into this release so we can close it upstream.

**Comment by nomis52** [comment]
The debian patch was

This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
--- a/common/network/InterfacePickerTest.cpp
+++ b/common/network/InterfacePickerTest.cpp
@@ -63,7 +63,7 @@ CPPUNIT_TEST_SUITE_REGISTRATION(Interfac
  */
 void InterfacePickerTest::testGetInterfaces() {
   auto_ptr<InterfacePicker> picker(InterfacePicker::NewPicker());
-  vector<Interface> interfaces = picker->GetInterfaces(false);
+  vector<Interface> interfaces = picker->GetInterfaces(true);
   OLA_ASSERT_TRUE(interfaces.size() > 0);
 
   vector<Interface>::iterator iter;


I'll go ahead and apply the same change.

**Comment by peternewman** [comment]
Yes, but just applying this patch as is makes testGetLoopbackInterfaces a bit of a pointless duplicate test, given we'll then already be checking we can find an interface, of some type, in testGetInterfaces.

**Comment by nomis52** [comment]
They do slightly different things.

The first test ensures that GetInterfaces doesn't fail, and that there is at least one interface.

The second ensures that there is a loopback interface. 

We could combine the two tests but I think the coverage is correct.

**Comment by peternewman** [comment]
Okay. I see your point.

Playing Devil's advocate though, perhaps on *nix we're guaranteed a loopback interface, and hence at least one, on Windows where we don't have one, it's not inconceivable to have a device with no network interfaces (a Pi A running Windows 10 perhaps), but the device could still be doing something worthwhile, e.g. DMX to Fadecandy or Renard. It's probably an extreme example, and I don't know the right solution (a configure flag to tell make check you don't expect network interfaces perhaps)? I just wonder if we should handle that case too somehow, to try and fix the issue once and for all, rather than just waiting for the next edge case to arrive.

Anyway you've convinced me, I'm happy for the patch to be merged, I just wonder if we should leave the issue open to ponder some more.

**Comment by nomis52** [comment]
The configure time test is going to be just as complex as the unit test itself and doesn't provide any value

"If host doesn't not have a loopback, expect host does not have a loopback".

**Comment by peternewman** [comment]
I didn't mean a test, just a configure argument like --disable-root-check and --disable-fatal-warnings. --disable-network-checks perhaps, or some better wording, which still makes the checks run, but doesn't expect any interfaces to be returned from them, so skips the tests after each check.

**Comment by nomis52** [comment]
Nope, lets not make it more complex than it needs to be. We'll fix it when it becomes a problem.
