### ISSUE TITLE
Switch to gcc 5.x when running the travis build

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#764]
See downstream Debian bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778038

I suspect running GCC 5 on Travis if we can may be the easiest solution to work through these issues and catch future ones.

A nice to have for https://github.com/OpenLightingProject/ola/milestones/0.9.6 but happy to drop if it proves challenging.

**Comment by peternewman** [comment]
A suitable PPA:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=precise

**Comment by nomis52** [comment]
Updating title to reflect what needs to be done next.

**Comment by peternewman** [comment]
Closed via #769

**Comment by peternewman** [comment]
Coverity doesn't seem to be working with g++-5, so need to switch just Coverity back to g++-4.9 where it did work.

**Comment by peternewman** [comment]
Done in https://github.com/OpenLightingProject/ola/pull/777 .
