### ISSUE TITLE
add jscs style checking

### ISSUE THREAD

**Issue by daveol** [OpenLightingProject/ola#766]
I setup a [gist](https://gist.github.com/daveol/8ac59462be488b0c2993) with most of the presets picked already. Input is appreciated

**Comment by nomis52** [comment]
"tabSize": 1, // We want to get this switched over to 2. 

  "requireSpacesInFunction": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  },

^^ Not sure about this one. The style I'm after is

var foo = function(arg1, arg2) {
  ...

The rest looks reasonable though. Can you set it up and then see how it affects the existing code?

**Comment by daveol** [comment]
sure,
The documentation about "requireSpacesInFunction" is [here](http://jscs.info/rule/requireSpacesInFunctionDeclaration.html)
Also there where some rules I didn't know how to setup but seem useful
 - [requireSpaceBeforeKeywords](http://jscs.info/rule/requireSpaceBeforeKeywords.html)
 - [disallowSpaceAfterKeywords](http://jscs.info/rule/disallowSpaceAfterKeywords.html)
 - [disallowSpacesInFunctionDeclaration](http://jscs.info/rule/disallowSpacesInFunctionDeclaration.html)
 - [disallowSpacesInFunctionExpression](http://jscs.info/rule/disallowSpacesInFunctionExpression.html)

The full list of rules are [here](http://jscs.info/rules.html)

**Comment by peternewman** [comment]
A general question, why do we use anonymous functions/functions as variables rather than traditional ones?

**Comment by daveol** [comment]
since we mostly use angular, so functions tend to be in the $scope object and it's better for consistency then

**Comment by nomis52** [comment]
Thanks for the example. beforeOpeningRoundBrace should be false then.
