### ISSUE TITLE
Building with Ja Rule requires the usbdmx plugin

### ISSUE THREAD

**Issue by simark** [OpenLightingProject/ola#773]
I just tried building with "--enable-rdm-tests --enable-ja-rule" to try to mimic what Travis does. However, I also add "--disable-all-plugins --enable-dummy", so that my build iterations are faster. It gave me this:

```
libtool: link: g++ -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -Werror -I/usr/include/libusb-1.0 -g -O2 -pthread -o tools/ja-rule/.libs/ja-rule tools/ja-rule/tools_ja_rule_ja_rule-JaRuleEndpoint.o tools/ja-rule/tools_ja_rule_ja_rule-USBDeviceManager.o tools/ja-rule/tools_ja_rule_ja_rule-ja-rule.o  -lusb-1.0 common/.libs/libolacommon.so -lresolv -lprotobuf -lpthread plugins/usbdmx/.libs/libolausbdmxwidget.a -ldns_sd -ldl -pthread -Wl,-rpath -Wl,/usr/local/lib
tools/ja-rule/tools_ja_rule_ja_rule-JaRuleEndpoint.o: In function `JaRuleEndpoint::Init()':
/home/simark/src/gridss/ola/tools/ja-rule/JaRuleEndpoint.cpp:121: undefined reference to `ola::plugin::usbdmx::LibUsbAdaptor::ErrorCodeToString(int)'
tools/ja-rule/tools_ja_rule_ja_rule-JaRuleEndpoint.o: In function `JaRuleEndpoint::SubmitInTransfer()':
/home/simark/src/gridss/ola/tools/ja-rule/JaRuleEndpoint.cpp:280: undefined reference to `ola::plugin::usbdmx::LibUsbAdaptor::ErrorCodeToString(int)'
tools/ja-rule/tools_ja_rule_ja_rule-JaRuleEndpoint.o: In function `JaRuleEndpoint::_InTransferComplete()':
/home/simark/src/gridss/ola/tools/ja-rule/JaRuleEndpoint.cpp:183: undefined reference to `ola::plugin::usbdmx::LibUsbAdaptor::ErrorCodeToString(int)'
tools/ja-rule/tools_ja_rule_ja_rule-JaRuleEndpoint.o: In function `JaRuleEndpoint::MaybeSendRequest()':
/home/simark/src/gridss/ola/tools/ja-rule/JaRuleEndpoint.cpp:250: undefined reference to `ola::plugin::usbdmx::LibUsbAdaptor::ErrorCodeToString(int)'
tools/ja-rule/tools_ja_rule_ja_rule-JaRuleEndpoint.o: In function `JaRuleEndpoint::_OutTransferComplete()':
/home/simark/src/gridss/ola/tools/ja-rule/JaRuleEndpoint.cpp:164: undefined reference to `ola::plugin::usbdmx::LibUsbAdaptor::ErrorCodeToString(int)'
tools/ja-rule/tools_ja_rule_ja_rule-USBDeviceManager.o: In function `USBDeviceManager::Start()':
/home/simark/src/gridss/ola/tools/ja-rule/USBDeviceManager.cpp:93: undefined reference to `ola::plugin::usbdmx::LibUsbHotplugThread::LibUsbHotplugThread(libusb_context*, int (*)(libusb_context*, libusb_device*, libusb_hotplug_event, void*), void*)'
/home/simark/src/gridss/ola/tools/ja-rule/USBDeviceManager.cpp:84: undefined reference to `ola::plugin::usbdmx::LibUsbAdaptor::ErrorCodeToString(int)'
collect2: error: ld returned 1 exit status
```

Perhaps configure should fail if Ja Rule is enabled but usbdmx is not?

**Comment by simark** [comment]
I think there is already an intent to do this, this change would probably do the trick:

```diff
diff --git a/configure.ac b/configure.ac
index ae254fa..b6f6081 100644
--- a/configure.ac
+++ b/configure.ac
@@ -710,9 +710,9 @@ AC_SUBST(OLA_CLIENT_LIBS)
 # Extra tools
 #####################################################
 AM_CONDITIONAL([BUILD_JA_RULE],
-               [test "x$enable_ja_rule" = xyes && test "x$have_libusb" = xyes \
+               [test "x$enable_ja_rule" = xyes && test "x$enable_usbdmx" = xyes \
                 && test "x$have_libusb_hotplug_api" = xyes])
```

**Comment by simark** [comment]
Though, if a prerequisite (e.g. usbdmx) is not enabled, I think it would be more user friendly to output an error explaining what is missing, rather than silently disabling the feature. If the user types --enable-ja-rule, it's because they want it, so it would be more valuable to fail the configure than to succeed without it.

Same would go for http. Currently, if the user types --enable-http but does not have libmicrohttpd headers installed, it will be disabled. Do you think it would be preferable to fail and say "You are missing libmicrohttpd"? The default behaviour would stay the same. When --{enable,disable}-http are not specified, we just enable it if the lib is found.

**Comment by nomis52** [comment]
Your last proposal seems reasonable. You can print an error and exit with AC_MSG_ERROR . Do you mind sending a patch?

**Comment by simark** [comment]
Opened #775.

**Comment by peternewman** [comment]
Funnily enough I was looking at libmicrohttpd the other day which works around similar issues and thinking we should copy it. They have the concept of three states for an option, yes, no and auto:
https://github.com/nomis52/libmicrohttpd/blob/master/configure.ac#L309

With no, it's not required, with yes it is, and will error if its missing, and with auto it will try and use it but fail silently. We can then tweak/force states for plugins appriately depending on what options are requested. Regarding your patch @simark I'd be tempted to go belt and braces and keep "x$have_libusb" = xyes and add enable_usbdmx too, just in case our have_libusb_hotplug_api logic ever breaks. I think there's also a stronger version of enable_usbdmx, from memory, that is just the configure flag, whereas there should be something that says all the pre-requisites are present too.

I guess once this is in, we can decide on the default state of each option, I'd say all the plugins should be auto, but personally I feel http should default to yes, as I think most/all users expect it to be there (and hence would want the build to fail if it wasn't going to be), unless they explicitly disable it. Just so they don't spend ages building on a Pi say, only to find out that it's missing when they finish.

**Comment by simark** [comment]
> Funnily enough I was looking at libmicrohttpd the other day which works around similar issues and thinking we should copy it. They have the concept of three states for an option, yes, no and auto:
https://github.com/nomis52/libmicrohttpd/blob/master/configure.ac#L309

> With no, it's not required, with yes it is, and will error if its missing, and with auto it will try and use it but fail silently. We can then tweak/force states for plugins appriately depending on what options are requested. 

Agreed with the yes/no/auto thing, that's pretty much what I implemented in the PR for the dependency on libmicrohttpd. Example 1.2 in [here](https://autotools.io/autoconf/arguments.html) provides a pretty good example, although I did not follow it exactly.

> Regarding your patch @simark I'd be tempted to go belt and braces and keep "x$have_libusb" = xyes and add enable_usbdmx too, just in case our have_libusb_hotplug_api logic ever breaks. I think there's also a stronger version of enable_usbdmx, from memory, that is just the configure flag, whereas there should be something that says all the pre-requisites are present too.
Ok, I'll add the have_libusb back. 

About the "enable_$plugin", if you look at config/ola.m4, function PLUGIN_SUPPORT, you will see that enable_plugin is forced to "no" if the prerequisites of the plugin are not met <sup>1</sup>. So it's safe to check against that. I don't see anything else relevant.

> I guess once this is in, we can decide on the default state of each option, I'd say all the plugins should be auto, but personally I feel http should default to yes, as I think most/all users expect it to be there (and hence would want the build to fail if it wasn't going to be), unless they explicitly disable it. Just so they don't spend ages building on a Pi say, only to find out that it's missing when they finish.

Agreed.

<sup>1</sup> It would be nice to use the yes/no/auto semantic for plugins as well. If I specify --enable-usbdmx, I don't want it to silently fail.

**Comment by peternewman** [comment]
Yes, you're quite correct @simark .

Feel free to submit a patch for yes/no/auto for plugins. I think we could cover it at a basic level by just extending PLUGIN_SUPPORT, possibly adding another arg for the log failure message, or simply dieing with a generic message if a manually enabled plugin is missing a dependency.

**Comment by simark** [comment]
Ok, I'll do this this in another commit in the same PR. But not tonight, it's getting late. :crescent_moon:

**Comment by nomis52** [comment]
We can close this now correct?

**Comment by simark** [comment]
I think so, that's what sparked the configure refactor.
