### ISSUE TITLE
OLAD switched file descriptor after detection. 

### ISSUE THREAD

**Issue by rewolff** [OpenLightingProject/ola#876]
After detecting my "usb widget" and reporting its name and version number olad -l 3 reports: 
UsbProWidgetDetector.cpp:312: Usb Widget didn't respond to messages, esta id 0, device id 0

I used strace to see what is going on: 

`7824  write(27, "~M\0\0\347", 5)        = 5
7824  write(9, "a", 1)                  = 1
7824  select(28, [8 26 27], [], NULL, {0, 193023}) = 2 (in [8 26], left {0,
+193018})
7824  ioctl(8, FIONREAD, [1])           = 0
7824  ioctl(26, FIONREAD, [10])         = 0
7824  ioctl(8, FIONREAD, [1])           = 0
7824  read(8, "a", 100)                 = 1
7824  read(8, 0x7fe9b79b2341, 99)       = -1 EAGAIN (Resource temporarily
+unavailable)
7824  ioctl(8, FIONREAD, [0])           = 0
7824  futex(0x1eed61c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x1eed618, {FUTEX_OP_SET, 0,
+FUTEX_OP_CMP_GT, 1}) = 1
7824  ioctl(26, FIONREAD <unfinished ...>
7824  <... ioctl resumed> , [10])       = 0
7824  read(26,  <unfinished ...>
7824  <... read resumed> "~", 1)        = 1
7824  read(26,  <unfinished ...>
7824  <... read resumed> "M", 1)        = 1
7824  read(26,  <unfinished ...>
7824  <... read resumed> "\5", 1)       = 1
7824  read(26, "\0", 1)                 = 1
7824  read(26,  <unfinished ...>
7824  <... read resumed> "\360\177AvV", 5) = 5
7824  read(26,  <unfinished ...>
7824  <... read resumed> "\347", 1)     = 1
`
This is the detection sequence where in the end the AvV string is seen which is part of the name returned by the device. 

But then: 
`7824  write(27, "~N\0\0\347", 5)        = 5
7824  select(28, [8 27], [], NULL, {0, 2712}) = 0 (Timeout)`

a similar 5=byte request is sent to the device, but now fd26 is no longer monitored for the reply. The previous request was answered on fd=26, so why wouldn't this one? To me that makes it entirely clear that no reply will be seen on fd=27. 

The complete strace is available, but github won't let me upload it. 

I've sold the hardware involved in this specific incident. But I'll be making more today (provided the chips do show up this time).... :-) 

This was with the source from github: commit 62a8908c68adbf2e6e5e7f744f890c5ada6a75a7

I then tried with a precompiled version on my raspberry pi and this issue didn't show up.

**Comment by nomis52** [comment]
Please attach or upload  the olad logs running at -l 4 .

It's very odd that a device replies on a different FD from the one the request was sent on. I've never seen this before. What USB devices is this?

**Comment by peternewman** [comment]
I don't see AvV listed anywhere in our plugins as a string, unless we're matching by ID. Is this another clone device?

**Comment by nomis52** [comment]
The response message decodes to:

Manufacturer ID 0x7ff0    
Manufacturer Name: AvV

I suspect this is a bad implementation of the Enttec USB DMX protocol

**Comment by rewolff** [comment]
No, it is a GOOD implementation of the Enttec USB DMX protocol.

Using an older pre-compiled version of OLA on the raspberry pi, the "further" requests do get answered. The device seems to be fine. There seem to be two filedescriptors referring to the device, and .......

OK. Found it! I had two /dev/ttyUSBx devices connected. ONE is properly detected and the other is not a DMX device and gets the complaints. 

Sorry for the confusion. Thanks for helping.

**Comment by peternewman** [comment]
@rewolff would it help if the log message included the path of the device to narrow down which one is which?

Also you can use ignore_device = /dev/ttyUSB in the ola-usbserial.conf to "Ignore the device matching this string. Multiple keys are allowed." and banish the log messages.

**Comment by rewolff** [comment]
Yes: tttyUSB0: found AvV device 
and: ttyUSB1: device is not responding 
would've allowed me to see in the logmessage itself which device it was talking about. 

The ignore device is of course now an option. But it didn't occur to me that it had found TWO /dev/ttyUSBx devices and was talking about one and then about another. Of course stupid of me that while debugging I forgot to check the origin of the 26 and 27 file descriptors...

YES! it would help to mention the path of the device, when logging messages.
