### ISSUE TITLE
Sending Different Lighting Commands to different Light Sources

### ISSUE THREAD

**Issue by jtl2018** [OpenLightingProject/ola#881]
So I have now configured ola to work on my os x.  I tested the program on a single light, and it worked fine.  Now I'm hooking it up to this system, the D4DMX-MD5 4channel programmable  dimmer pack.  I ran the same setup:
(bash)
ola_patch -d 10 -p 0 -u 2
which is the name of my device, the port 0, and the universe I chose (2).  I'm using almost the same code in the section of the wiki that describes how to send lighting commands.  How do I now apply this for the different lights?  There are 4 channels but I am not sure how to reach them.  Also, I am using the Enttec DMX USB Pro Mk2 if that helps whatsover.

**Comment by nomis52** [comment]
It's better to ask these sort of question on the mailing list rather than opening issues. There are many more people reading the list than looking at issues.

To control your device you'll need to send (at least) 4 bytes of data. Each byte is used to control a single channel on the dimmer.

**Comment by jtl2018** [comment]
ok, I added myself to the ola mailing group, hopefully it's the moderator approves soon.  I apologize for asking this in the wrong place.
