### ISSUE TITLE
ola_rdm_get.py throws AttributeError when attempting to load additional PIDs

### ISSUE THREAD

**Issue by rmull** [OpenLightingProject/ola#889]
I am attempting to load some manufacturer specific PIDs so that I can GET/SET them using ola_rdm_get.py in interactive mode. The PID file I have in my working directory is the same as data/rdm/manufacturer_pids.proto in the OLA distribution. When I issue the 'uid' instruction, the script crashes when attempting to fetch queued messages.

```
$ ./ola_rdm_get.py -u 1 -p . -i
Available Uids:
1234:12000001
> uid 1234:12000001
Fetching queued messages...
Traceback (most recent call last):
  File "./ola_rdm_get.py", line 486, in <module>
    main()
  File "./ola_rdm_get.py", line 468, in main
    controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./ola_rdm_get.py", line 157, in do_uid
    self._FetchQueuedMessages()
  File "./ola_rdm_get.py", line 334, in _FetchQueuedMessages
    ['error'])
  File "/usr/lib/python2.7/dist-packages/ola/RDMAPI.py", line 104, in Get
    PidStore.RDM_GET)
  File "/usr/lib/python2.7/dist-packages/ola/RDMAPI.py", line 178, in _SendRequest
    data = pid.Pack(args, request_type)
AttributeError: 'NoneType' object has no attribute 'Pack'
```

**Comment by nomis52** [comment]
Do you have the file containing the standard PLASA pids in the same directory? This stack trace would make sense if the QUEUED_MESSAGE PID was missing.

**Comment by rmull** [comment]
You are correct. My error was assuming that the PID directory would allow us to specify PIDs in addition to the base set of PLASA and known manufacturer-specific PIDs. I pointed the PID dir to the data/rdm directory, and added my own PIDs to a new file in there, and all is well.

**Comment by nomis52** [comment]
At the very least we should print a more useful error if the PLASA pids aren't found.

@peternewman  can you take this on?
