### ISSUE TITLE
Issue installing on Mac OSX10.10.5

### ISSUE THREAD

**Issue by heslop** [OpenLightingProject/ola#967]
Ive just about to get Ola installed, but anywhere I try and get it to run just fails. Ive tried both python2.7 and python3.4 as well as in XCode, using  C++/objectiveC

I need this to get up and running for a school project, but just keep hitting dead ends. 

Anyone have any ideas where I should begin in trying to get this to work?

**Comment by daveol** [comment]
can you post the output of the error?

**Comment by heslop** [comment]
When simply running in python 2.7:
import array
from ola.ClientWrapper import ClientWrapper

I get: 
Traceback (most recent call last):
  File "/Users/benheslop/Desktop/Test.py", line 2, in <module>
    from ola.ClientWrapper import ClientWrapper
ImportError: No module named ola.ClientWrapper

Similar issues are found in Xcode, as the frameworks aren't available in the "Linked Frameworks and Libraries" area

![screen shot 2015-11-06 at 18 01 56](https://cloud.githubusercontent.com/assets/15692195/11004492/78d9148c-84b0-11e5-9ef9-7df5ce0ad421.png)

**Comment by nomis52** [comment]
For Python, it sounds like your PYTHONPATH variable isn't set correctly.  The correct settings will depend on how you installed ola on your system (from source, macports, homebrew etc.) 

I don't use XCode so I'm not much help, but try looking at https://wiki.openlighting.org/index.php/Using_OLA_with_Xcode

**Comment by heslop** [comment]
Ok, i'll see if i can fix it that way.

As a temporary fix, I've managed to get it up and running on my Pi, so ill work on it on there!

Thank you for the help :)
